//! build.rs — generates `CardDef` consts from the official-format card JSON (roadmap D2/E4).
//!
//! Input: `cards/cards.json` — the official HearthstoneJSON-derived card database
//! (the classic-era constructed sets: EXPERT1 + CORE + LEGACY, deduplicated by ID).
//! Output: `OUT_DIR/cards_generated.rs` — one `pub const <ID>: CardDef` per card,
//! the `pub const GENERATED_IDS: &[&str]` registry, and `find_by_id`/`find_by_name`
//! lookup helpers.
//!
//! The official JSON only carries static attributes and keywords; scripted
//! effects (Battlecry/Deathrattle/Auras, etc.) are still handwritten — the
//! corresponding `Option` fields are `None` in the generated code. The
//! handwritten pool uses custom IDs (CLASSIC_001, NEUTRAL_...), so the
//! verification tests match generated vs handwritten cards by NAME
//! (see `cards/mod.rs`).

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

/// The official JSON card fields used by the generator (subset of HearthstoneJSON).
/// Extended in 2025–2026 expansions M0.2 with `race` (tribe) and `set`
/// (collection membership) — both flow into the generated code. The remaining
/// schema fields (`text`, `cardClass`, `classes`, `collectible`) stay in the
/// JSON layer: they are metadata for hand-wiring effects, not game attributes.
#[derive(serde::Deserialize)]
struct JsonCard {
    id: String,
    name: String,
    #[serde(default)]
    cost: Option<i32>,
    #[serde(default)]
    attack: Option<i32>,
    #[serde(default)]
    health: Option<i32>,
    #[serde(default)]
    durability: Option<i32>,
    #[serde(default)]
    #[serde(rename = "type")]
    card_type: String,
    #[serde(default)]
    mechanics: Vec<String>,
    #[serde(default)]
    race: Option<String>,
    #[serde(default)]
    set: Option<String>,
}

/// Maps a HearthstoneJSON race code to a generated `Race::X` expression.
/// `None` for untribed cards and for codes without a single-tribe mapping
/// (e.g. "ALL" — Crater Experiment counts as every race).
fn race_expr(race: &Option<String>) -> Option<&'static str> {
    match race.as_deref() {
        Some("BEAST") => Some("Race::Beast"),
        Some("MURLOC") => Some("Race::Murloc"),
        Some("DEMON") => Some("Race::Demon"),
        Some("DRAGON") => Some("Race::Dragon"),
        Some("ELEMENTAL") => Some("Race::Elemental"),
        Some("MECHANICAL") => Some("Race::Mechanical"),
        Some("PIRATE") => Some("Race::Pirate"),
        Some("TOTEM") => Some("Race::Totem"),
        Some("UNDEAD") => Some("Race::Undead"),
        Some("QUILBOAR") => Some("Race::Quilboar"),
        Some("DRAENEI") => Some("Race::Draenei"),
        Some("NAGA") => Some("Race::Naga"),
        _ => None,
    }
}

/// Maps a HearthstoneJSON set code to a generated `CardSet::X` expression.
/// The 2025–2026 expansion codes land here as M0.3 registers the per-set data.
fn set_expr(set: &Option<String>) -> &'static str {
    match set.as_deref() {
        Some("EXPERT1" | "LEGACY" | "VANILLA") => "CardSet::Classic",
        Some("CORE" | "CORE_HIDDEN") => "CardSet::Core",
        Some("EMERALD_DREAM") => "CardSet::EmeraldDream",
        Some("THE_LOST_CITY") => "CardSet::TheLostCity",
        Some("TIME_TRAVEL") => "CardSet::TimeTravel",
        Some("CATACLYSM") => "CardSet::Cataclysm",
        Some("ESCAPEFROM_VIOLET_HOLD") => "CardSet::EscapeFromVioletHold",
        _ => "CardSet::Other",
    }
}

/// Turns a card ID into a legal Rust const name (IDs that are already valid
/// identifiers are used as-is).
fn const_name(id: &str) -> String {
    let sanitized: String = id
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if sanitized.is_empty() || sanitized.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("CARD_{sanitized}")
    } else {
        sanitized
    }
}

fn main() {
    println!("cargo:rerun-if-changed=cards/cards.json");
    let json_path = Path::new("cards/cards.json");
    let raw = fs::read_to_string(json_path).expect("read cards/cards.json");
    let cards: Vec<JsonCard> = serde_json::from_str(&raw).expect("parse cards/cards.json");

    let mut code =
        String::from("// Auto-generated by build.rs — do not edit (source: cards/cards.json).\n\n");
    let mut ids = Vec::new();
    let mut sets = Vec::new();
    let mut by_id = String::new();
    let mut by_name = String::new();
    let mut seen_names = HashSet::new();
    for card in &cards {
        let name = const_name(&card.id);
        let is_weapon = card.card_type == "WEAPON";
        let card_type = match card.card_type.as_str() {
            "SPELL" => "CardType::Spell",
            "WEAPON" => "CardType::Weapon",
            "HERO" => "CardType::Hero",
            _ => "CardType::Minion",
        };
        let race = race_expr(&card.race);
        let set = set_expr(&card.set);
        let taunt = card.mechanics.iter().any(|m| m == "TAUNT");
        let stealth = card.mechanics.iter().any(|m| m == "STEALTH");
        let elusive = card.mechanics.iter().any(|m| m == "ELUSIVE");
        let divine_shield = card.mechanics.iter().any(|m| m == "DIVINE_SHIELD");
        let windfury = card.mechanics.iter().any(|m| m == "WINDFURY");
        let charge = card.mechanics.iter().any(|m| m == "CHARGE");
        let spell_damage = card.mechanics.iter().filter(|m| *m == "SPELLPOWER").count() as i32;
        // HearthstoneJSON stores weapon durability in the health field
        let durability = if is_weapon {
            card.health.unwrap_or(0)
        } else {
            card.durability.unwrap_or(0)
        };
        let health = if is_weapon {
            0
        } else {
            card.health.unwrap_or(0)
        };

        code.push_str(&format!(
            "/// Generated card const (official JSON): {} — {}\n",
            card.id, card.name
        ));
        code.push_str(&format!("pub const {name}: CardDef = CardDef {{\n"));
        code.push_str(&format!("    id: \"{}\",\n", card.id));
        code.push_str(&format!("    name: \"{}\",\n", card.name));
        code.push_str(&format!("    card_type: {card_type},\n"));
        code.push_str(&format!("    cost: {},\n", card.cost.unwrap_or(0)));
        code.push_str(&format!("    attack: {},\n", card.attack.unwrap_or(0)));
        code.push_str(&format!("    health: {health},\n"));
        code.push_str(&format!("    durability: {durability},\n"));
        code.push_str("    battlecry: None,\n    deathrattle: None,\n");
        code.push_str(&format!("    taunt: {taunt},\n"));
        code.push_str(&format!("    stealth: {stealth},\n"));
        code.push_str(&format!("    elusive: {elusive},\n"));
        code.push_str(&format!(
            "    race: {},\n",
            race.map_or("None".to_string(), |r| format!("Some({r})"))
        ));
        code.push_str("    hero_power: None,\n    aura: None,\n    secret: None,\n");
        code.push_str(&format!("    divine_shield: {divine_shield},\n"));
        code.push_str(&format!("    windfury: {windfury},\n"));
        code.push_str(&format!("    charge: {charge},\n"));
        code.push_str(&format!("    spell_damage: {spell_damage},\n"));
        code.push_str("    cant_attack: false,\n    end_turn_effect: None,\n");
        code.push_str("    start_turn_effect: None,\n    spell_effect: None,\n");
        code.push_str("    spell_trigger: None,\n    death_trigger: None,\n");
        code.push_str("    summon_trigger: None,\n    choose_one_effect: None,\n");
        code.push_str("    combo_effect: None,\n    attack_equals_health: false,\n};\n\n");
        ids.push(card.id.clone());
        sets.push((card.id.clone(), set));
        by_id.push_str(&format!("        \"{}\" => Some({name}),\n", card.id));
        // The name index prefers real cards over enchantment tokens
        if card.card_type != "ENCHANTMENT" && seen_names.insert(card.name.clone()) {
            by_name.push_str(&format!("        \"{}\" => Some({name}),\n", card.name));
        }
    }

    code.push_str("/// The IDs of all generated cards.\n");
    code.push_str("pub const GENERATED_IDS: &[&str] = &[\n");
    for id in &ids {
        code.push_str(&format!("    \"{id}\",\n"));
    }
    code.push_str("];\n");

    code.push_str(
        "\n/// Looks up a generated card definition by official ID.\n#[must_use]\npub fn find_by_id(id: &str) -> Option<CardDef> {\n    match id {\n",
    );
    code.push_str(&by_id);
    code.push_str("        _ => None,\n    }\n}\n");

    code.push_str(
        "\n/// Looks up a generated card definition by name.\n#[must_use]\npub fn find_by_name(name: &str) -> Option<CardDef> {\n    match name {\n",
    );
    code.push_str(&by_name);
    code.push_str("        _ => None,\n    }\n}\n");

    code.push_str("\n/// Card set membership by official ID (2025–2026 expansions M0.2).\n");
    code.push_str("/// Unknown/custom IDs default to `CardSet::Classic` — the custom-ID\n");
    code.push_str(
        "/// handwritten pool is a classic-era collection.\n#[must_use]\npub fn card_set(id: &str) -> CardSet {\n    match id {\n",
    );
    for (id, set) in &sets {
        code.push_str(&format!("        \"{id}\" => {set},\n"));
    }
    code.push_str("        _ => CardSet::Classic,\n    }\n}\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("cards_generated.rs");
    fs::write(&dest, code).expect("write generated cards");
}
