//! Event system — the Event enum, EventQueue, and priorities.
//!
//! The game rules engine is event-driven: an Action produces Events, and an Event may
//! trigger more Events until the queue is drained. Events are both a record of "what
//! happened" (for replay) and the driver of state changes (`apply_event` mutates GameState).
//!
//! The Phase 2+ Trigger system hooks into `apply_event`, matching event types and
//! enqueueing triggered effects.

use crate::core::entity::Entity;
use crate::core::player::PlayerId;
use std::collections::VecDeque;

/// Game event — an atomic event processed by the rules engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Event {
    /// Turn start — reset attack counts, update active_player, etc.
    TurnStarted {
        /// The player whose turn begins
        player: PlayerId,
    },
    /// Turn end
    TurnEnded {
        /// The player whose turn ends
        player: PlayerId,
    },
    /// A card is played
    CardPlayed {
        /// The player who played the card
        player: PlayerId,
        /// The played card entity
        card: Entity,
        /// Explicit target (passed in by `Action::PlayCard`; the engine picks randomly when `None`)
        target: Option<Entity>,
        /// Summon position on the board (roadmap G6); `None` = rightmost
        position: Option<u8>,
    },
    /// A minion is summoned to the battlefield
    MinionSummoned {
        /// The summoning player
        player: PlayerId,
        /// The summoned minion entity
        minion: Entity,
    },
    /// An attack is declared
    AttackDeclared {
        /// The attacker
        attacker: Entity,
        /// The defender
        defender: Entity,
    },
    /// Attack resolution — the attack step in the unified damage pipeline.
    ///
    /// Processed after `AttackDeclared` (including the secret reaction point): enqueues the
    /// attacker's damage and the defender's retaliation. Attacker damage is computed at
    /// enqueue time (the weapon may be destroyed during `AttackDeclared`, so the damage must
    /// include the weapon bonus at attack time); retaliation damage is recomputed at
    /// resolution time from the current state (a new target after secret redirection
    /// automatically retaliates, no per-card special handling needed).
    ResolveAttack {
        /// The attacker
        attacker: Entity,
        /// The defender
        defender: Entity,
        /// Damage dealt by the attacker (computed at enqueue time)
        attacker_damage: i32,
        /// Whether the attacker is immune to retaliation (Gladiator's Longbow — the hero is immune while attacking)
        retaliation_immune: bool,
    },
    /// Damage is dealt
    DamageDealt {
        /// The damage source
        source: Entity,
        /// The damage target
        target: Entity,
        /// Damage amount
        amount: i32,
    },
    /// A minion dies
    MinionDied {
        /// The dead minion entity
        minion: Entity,
    },
    /// A card is drawn into hand
    CardDrawn {
        /// The drawing player
        player: PlayerId,
        /// The drawn card entity
        card: Entity,
    },
    /// Game over
    GameOver {
        /// The winner
        winner: PlayerId,
    },
    /// A weapon is equipped
    WeaponEquipped {
        /// The player who equipped the weapon
        player: PlayerId,
        /// The weapon entity
        weapon: Entity,
    },
    /// A weapon is destroyed (durability depleted or replaced)
    WeaponDestroyed {
        /// The player who lost the weapon
        player: PlayerId,
        /// The destroyed weapon entity
        weapon: Entity,
    },
    /// A spell is cast
    SpellCast {
        /// The player who cast the spell
        player: PlayerId,
        /// The spell entity
        spell: Entity,
    },
    /// A hero power is activated
    HeroPowerActivated {
        /// The player who used the power
        player: PlayerId,
        /// The hero entity
        hero: Entity,
        /// Explicit target (roadmap G6); `None` = engine random
        target: Option<Entity>,
    },
    /// A secret is revealed and triggered
    SecretRevealed {
        /// The player who owns the secret
        player: PlayerId,
        /// The secret entity
        secret: Entity,
    },
    /// A pending choice is resolved (roadmap G6) — generated by `Action::Choose`.
    ChoiceResolved {
        /// The pending choice's id
        choice_id: u64,
        /// The chosen option index
        option: u8,
    },
}

/// Event priority — smaller values are processed first.
///
/// All events have Normal priority in Phase 1.
/// Phase 2+ Secret/Trigger events are enqueued at different priorities.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u8)]
pub enum Priority {
    /// Highest priority (used for secret triggers in Phase 2+, etc.)
    Highest = 0,
    /// Standard priority
    Normal = 1,
    /// Lowest priority
    Lowest = 2,
}

/// Event queue — a FIFO queue ordered by priority.
///
/// Within the same priority, enqueue order is preserved (FIFO), which keeps game logic deterministic.
/// `BinaryHeap` is unsuitable because it does not preserve the order of equal-priority elements.
///
/// Internally uses three `VecDeque`s (one per priority);
/// both enqueue and dequeue are O(1) — the event loop is the engine's hottest path.
#[derive(Debug, Default, Clone)]
pub struct EventQueue {
    buckets: [VecDeque<Event>; 3],
}

impl EventQueue {
    /// Create an empty event queue.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            buckets: [
                const { VecDeque::new() },
                const { VecDeque::new() },
                const { VecDeque::new() },
            ],
        }
    }

    /// Enqueue an event with Normal priority.
    pub fn push(&mut self, event: Event) {
        self.push_with_priority(event, Priority::Normal);
    }

    /// Enqueue an event with the given priority.
    ///
    /// Appends to the end of the same-priority queue (keeping FIFO).
    pub fn push_with_priority(&mut self, event: Event, priority: Priority) {
        self.buckets[priority as usize].push_back(event);
    }

    /// Pop and remove the front event (the earliest enqueued among the highest priority).
    ///
    /// Checks the buckets from highest to lowest priority and returns the front of the first non-empty bucket. O(1).
    pub fn pop_front(&mut self) -> Option<Event> {
        for bucket in &mut self.buckets {
            if let Some(event) = bucket.pop_front() {
                return Some(event);
            }
        }
        None
    }

    /// Returns `true` if the queue is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.buckets.iter().all(VecDeque::is_empty)
    }

    /// Returns the number of events in the queue.
    #[must_use]
    pub fn len(&self) -> usize {
        self.buckets.iter().map(VecDeque::len).sum()
    }

    /// Peek the next event without popping it.
    #[must_use]
    pub fn front(&self) -> Option<Event> {
        for bucket in &self.buckets {
            if let Some(event) = bucket.front() {
                return Some(*event);
            }
        }
        None
    }

    /// Drain the queue and return all events (in processing order).
    pub fn drain(&mut self) -> Vec<Event> {
        let mut events = Vec::with_capacity(self.len());
        for bucket in &mut self.buckets {
            events.extend(bucket.drain(..));
        }
        events
    }

    /// Redirect the first queued attack matching `ResolveAttack { attacker, defender }`.
    ///
    /// The unified primitive for attack-redirecting secrets (Misdirection, Noble Sacrifice):
    /// both the attack's damage and its retaliation are computed from the current state at
    /// `ResolveAttack` resolution time, so replacing the event's defender fully redirects it
    /// (the new target's automatic retaliation is handled by the resolution logic).
    /// Returns whether a matching attack was found and redirected.
    pub fn redirect_attack(
        &mut self,
        attacker: Entity,
        old_defender: Entity,
        new_defender: Entity,
    ) -> bool {
        // Scan the buckets in processing order (highest to lowest priority) and find the first match
        for bucket in &mut self.buckets {
            for event in bucket {
                if let Event::ResolveAttack {
                    attacker: a,
                    defender: d,
                    attacker_damage,
                    retaliation_immune,
                } = *event
                {
                    if a == attacker && d == old_defender {
                        *event = Event::ResolveAttack {
                            attacker,
                            defender: new_defender,
                            attacker_damage,
                            retaliation_immune,
                        };
                        return true;
                    }
                }
            }
        }
        false
    }

    /// Redirect all `DamageDealt` events satisfying the predicate to `new_target`.
    ///
    /// The predicate receives the event's source and target. Used by secrets that need to
    /// redirect in bulk by source, such as Spellbender (spell damage is enqueued against the
    /// source spell during effect resolution; secrets intercept it here uniformly).
    /// Returns the number of redirects.
    pub fn redirect_damages(
        &mut self,
        predicate: impl Fn(Entity, Entity) -> bool,
        new_target: Entity,
    ) -> usize {
        let mut count = 0;
        for bucket in &mut self.buckets {
            for event in bucket {
                if let Event::DamageDealt { source, target, .. } = event {
                    if predicate(*source, *target) {
                        *target = new_target;
                        count += 1;
                    }
                }
            }
        }
        count
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fifo_within_same_priority() {
        let mut q = EventQueue::new();
        q.push(Event::TurnStarted {
            player: PlayerId::Player1,
        });
        q.push(Event::AttackDeclared {
            attacker: Entity::new(1, 0),
            defender: Entity::new(2, 0),
        });
        q.push(Event::TurnEnded {
            player: PlayerId::Player1,
        });

        assert_eq!(
            q.pop_front(),
            Some(Event::TurnStarted {
                player: PlayerId::Player1
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::AttackDeclared {
                attacker: Entity::new(1, 0),
                defender: Entity::new(2, 0)
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::TurnEnded {
                player: PlayerId::Player1
            })
        );
        assert!(q.is_empty());
    }

    #[test]
    fn priority_ordering() {
        let mut q = EventQueue::new();
        q.push_with_priority(
            Event::MinionDied {
                minion: Entity::new(10, 0),
            },
            Priority::Lowest,
        );
        q.push_with_priority(
            Event::GameOver {
                winner: PlayerId::Player1,
            },
            Priority::Highest,
        );
        q.push_with_priority(
            Event::DamageDealt {
                source: Entity::new(1, 0),
                target: Entity::new(2, 0),
                amount: 3,
            },
            Priority::Normal,
        );

        // Highest first
        assert_eq!(
            q.pop_front(),
            Some(Event::GameOver {
                winner: PlayerId::Player1
            })
        );
        // Then Normal
        assert_eq!(
            q.pop_front(),
            Some(Event::DamageDealt {
                source: Entity::new(1, 0),
                target: Entity::new(2, 0),
                amount: 3
            })
        );
        // Finally Lowest
        assert_eq!(
            q.pop_front(),
            Some(Event::MinionDied {
                minion: Entity::new(10, 0)
            })
        );
    }

    #[test]
    fn fifo_within_same_priority_stable() {
        let mut q = EventQueue::new();
        q.push(Event::CardPlayed {
            player: PlayerId::Player1,
            card: Entity::new(1, 0),
            target: None,
            position: None,
        });
        q.push(Event::CardPlayed {
            player: PlayerId::Player1,
            card: Entity::new(2, 0),
            target: None,
            position: None,
        });
        q.push(Event::CardPlayed {
            player: PlayerId::Player1,
            card: Entity::new(3, 0),
            target: None,
            position: None,
        });

        assert_eq!(
            q.pop_front(),
            Some(Event::CardPlayed {
                player: PlayerId::Player1,
                card: Entity::new(1, 0),
                target: None,
                position: None
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::CardPlayed {
                player: PlayerId::Player1,
                card: Entity::new(2, 0),
                target: None,
                position: None
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::CardPlayed {
                player: PlayerId::Player1,
                card: Entity::new(3, 0),
                target: None,
                position: None
            })
        );
    }

    #[test]
    fn drain_returns_all_in_order() {
        let mut q = EventQueue::new();
        q.push(Event::TurnStarted {
            player: PlayerId::Player2,
        });
        q.push(Event::TurnEnded {
            player: PlayerId::Player2,
        });
        let events = q.drain();
        assert_eq!(events.len(), 2);
        assert!(q.is_empty());
    }

    #[test]
    fn empty_queue_pop_returns_none() {
        let mut q = EventQueue::new();
        assert_eq!(q.pop_front(), None);
    }

    #[test]
    fn interleaved_priorities_preserve_fifo() {
        let mut q = EventQueue::new();
        // Interleaved enqueue: Lowest → Normal → Highest → Normal → Lowest
        q.push_with_priority(
            Event::MinionDied {
                minion: Entity::new(1, 0),
            },
            Priority::Lowest,
        );
        q.push_with_priority(
            Event::DamageDealt {
                source: Entity::new(2, 0),
                target: Entity::new(3, 0),
                amount: 1,
            },
            Priority::Normal,
        );
        q.push_with_priority(
            Event::GameOver {
                winner: PlayerId::Player1,
            },
            Priority::Highest,
        );
        q.push_with_priority(
            Event::DamageDealt {
                source: Entity::new(4, 0),
                target: Entity::new(5, 0),
                amount: 2,
            },
            Priority::Normal,
        );
        q.push_with_priority(
            Event::MinionDied {
                minion: Entity::new(6, 0),
            },
            Priority::Lowest,
        );

        // Order: Highest, Normal FIFO, Lowest FIFO
        assert_eq!(
            q.pop_front(),
            Some(Event::GameOver {
                winner: PlayerId::Player1
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::DamageDealt {
                source: Entity::new(2, 0),
                target: Entity::new(3, 0),
                amount: 1
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::DamageDealt {
                source: Entity::new(4, 0),
                target: Entity::new(5, 0),
                amount: 2
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::MinionDied {
                minion: Entity::new(1, 0)
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::MinionDied {
                minion: Entity::new(6, 0)
            })
        );
        assert!(q.is_empty());
    }

    #[test]
    fn redirect_attack_matches_processing_order() {
        let mut q = EventQueue::new();
        // Within the same priority, earlier enqueued events are processed first — redirection should hit the first match
        let first = Entity::new(1, 0);
        let second = Entity::new(2, 0);
        let attacker = Entity::new(3, 0);
        q.push(Event::ResolveAttack {
            attacker,
            defender: first,
            attacker_damage: 3,
            retaliation_immune: false,
        });
        q.push(Event::ResolveAttack {
            attacker,
            defender: second,
            attacker_damage: 3,
            retaliation_immune: false,
        });

        assert!(q.redirect_attack(attacker, second, Entity::new(9, 0)));
        // The second attack is redirected; the first is unchanged (attacker_damage/retaliation_immune preserved too)
        assert_eq!(
            q.pop_front(),
            Some(Event::ResolveAttack {
                attacker,
                defender: first,
                attacker_damage: 3,
                retaliation_immune: false,
            })
        );
        assert_eq!(
            q.pop_front(),
            Some(Event::ResolveAttack {
                attacker,
                defender: Entity::new(9, 0),
                attacker_damage: 3,
                retaliation_immune: false,
            })
        );
    }

    #[test]
    fn redirect_attack_preserves_attack_fields() {
        let mut q = EventQueue::new();
        let attacker = Entity::new(5, 0);
        q.push(Event::ResolveAttack {
            attacker,
            defender: Entity::new(6, 0),
            attacker_damage: 7,
            retaliation_immune: true,
        });

        assert!(q.redirect_attack(attacker, Entity::new(6, 0), Entity::new(8, 0)));
        assert_eq!(
            q.pop_front(),
            Some(Event::ResolveAttack {
                attacker,
                defender: Entity::new(8, 0),
                attacker_damage: 7,
                retaliation_immune: true,
            })
        );
    }

    #[test]
    fn redirect_attack_no_match() {
        let mut q = EventQueue::new();
        q.push(Event::ResolveAttack {
            attacker: Entity::new(1, 0),
            defender: Entity::new(2, 0),
            attacker_damage: 1,
            retaliation_immune: false,
        });
        assert!(!q.redirect_attack(Entity::new(9, 0), Entity::new(2, 0), Entity::new(3, 0)));
        assert!(!q.redirect_attack(Entity::new(1, 0), Entity::new(9, 0), Entity::new(3, 0)));
        assert_eq!(q.len(), 1);
    }
}
