//! Classic set — Shaman.
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget};

// Classic set — Shaman
// ============================================================

pub const EARTH_SHOCK: CardDef = CardDef {
    id: "SHAMAN_001",
    name: "Earth Shock",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const LIGHTNING_BOLT: CardDef = CardDef {
    id: "SHAMAN_002",
    name: "Lightning Bolt",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ROCKBITER_WEAPON: CardDef = CardDef {
    id: "SHAMAN_003",
    name: "Rockbiter Weapon",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainHeroAttack {
        attack: 3,
        armor: 0,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FLAMETONGUE_TOTEM: CardDef = CardDef {
    id: "SHAMAN_004",
    name: "Flametongue Totem",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(2), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const HEX: CardDef = CardDef {
    id: "SHAMAN_005",
    name: "Hex",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const LIGHTNING_STORM: CardDef = CardDef {
    id: "SHAMAN_006",
    name: "Lightning Storm",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AllEnemyMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FIRE_ELEMENTAL: CardDef = CardDef {
    id: "SHAMAN_007",
    name: "Fire Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const BLOODLUST: CardDef = CardDef {
    id: "SHAMAN_008",
    name: "Bloodlust",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 3,
        health: 0,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FERAL_SPIRIT: CardDef = CardDef {
    id: "SHAMAN_009",
    name: "Feral Spirit",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const MANA_TIDE_TOTEM: CardDef = CardDef {
    id: "SHAMAN_010",
    name: "Mana Tide Totem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 0,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::DrawCard { count: 1 }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Doomhammer — Windfury. Overload: (2) (simplified: no Overload)
pub const DOOMHAMMER: CardDef = CardDef {
    id: "SHAMAN_011",
    name: "Doomhammer",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 2,
    health: 0,
    durability: 8,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ALAKIR_THE_WINDLORD: CardDef = CardDef {
    id: "SHAMAN_012",
    name: "Al'Akir the Windlord",
    card_type: CardType::Minion,
    cost: 8,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: true,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Shaman additions
pub const TOTEMIC_MIGHT: CardDef = CardDef {
    id: "SHAMAN_013",
    name: "Totemic Might",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 0,
        health: 2,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const FROST_SHOCK: CardDef = CardDef {
    id: "SHAMAN_014",
    name: "Frost Shock",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const DUST_DEVIL: CardDef = CardDef {
    id: "SHAMAN_015",
    name: "Dust Devil",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Forked Lightning — deal 2 damage to 2 random enemy minions. Overload: (2) (simplified: Overload amount 1, not 2 — id collision with Windfury, see fidelity-debt F-A8)
pub const FORKED_LIGHTNING: CardDef = CardDef {
    id: "SHAMAN_016",
    name: "Forked Lightning",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const LAVA_BURST: CardDef = CardDef {
    id: "SHAMAN_017",
    name: "Lava Burst",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 5,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Stormforged Axe — 2/3 weapon. Overload: (1) (simplified: no Overload)
pub const STORMFORGED_AXE: CardDef = CardDef {
    id: "SHAMAN_018",
    name: "Stormforged Axe",
    card_type: CardType::Weapon,
    cost: 2,
    attack: 2,
    health: 0,
    durability: 3,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const EARTH_ELEMENTAL: CardDef = CardDef {
    id: "SHAMAN_019",
    name: "Earth Elemental",
    card_type: CardType::Minion,
    cost: 5,
    attack: 7,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Windfury — give a friendly minion Windfury
pub const WINDFURY: CardDef = CardDef {
    id: "SHAMAN_016",
    name: "Windfury",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GrantWindfury {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Windspeaker — Battlecry: give a friendly minion Windfury
pub const WINDSPEAKER: CardDef = CardDef {
    id: "SHAMAN_017",
    name: "Windspeaker",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GrantWindfury {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Ancestral Healing — restore a minion to full Health and give it Taunt
pub const ANCESTRAL_HEALING: CardDef = CardDef {
    id: "SHAMAN_018",
    name: "Ancestral Healing",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::FullHealAndTaunt {
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Ancestral Spirit — give a minion "Deathrattle: resummon this minion"
pub const ANCESTRAL_SPIRIT: CardDef = CardDef {
    id: "SHAMAN_019",
    name: "Ancestral Spirit",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Far Sight
// ============================================================

/// Far Sight — draw a card; it costs (3) less.
pub const FAR_SIGHT: CardDef = CardDef {
    id: "SHAMAN_020",
    name: "Far Sight",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCardAndReduceCost { amount: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Unbound Elemental
// ============================================================

/// Unbound Elemental — whenever you play a card with Overload, gain +1/+1.
pub const UNBOUND_ELEMENTAL: CardDef = CardDef {
    id: "SHAMAN_021",
    name: "Unbound Elemental",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
