//! 怀旧系列 — 猎人 (Hunter)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget};
use crate::vanilla;

// 怀旧系列 — 猎人 (Hunter)
// ============================================================

pub const ARCANE_SHOT: CardDef = CardDef {
    id: "HUNTER_001",
    name: "Arcane Shot",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 2, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const HUNTERS_MARK: CardDef = CardDef {
    id: "HUNTER_002",
    name: "Hunter's Mark",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack { attack: 0, target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const TRACKING: CardDef = CardDef {
    id: "HUNTER_003",
    name: "Tracking",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const KILL_COMMAND: CardDef = CardDef {
    id: "HUNTER_004",
    name: "Kill Command",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const UNLEASH_THE_HOUNDS: CardDef = CardDef {
    id: "HUNTER_005",
    name: "Unleash the Hounds",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion { card_id: "HUNTER_t" }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const SAVANNAH_HIGHMANE: CardDef = CardDef {
    id: "HUNTER_006",
    name: "Savannah Highmane",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "HUNTER_006t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const HYENA: CardDef = vanilla!("HUNTER_006t", "Hyena", 2, 2, 2);


pub const EAGLEHORN_BOW: CardDef = CardDef {
    id: "HUNTER_007",
    name: "Eaglehorn Bow",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 3,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const DEADLY_SHOT: CardDef = CardDef {
    id: "HUNTER_008",
    name: "Deadly Shot",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion { target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const EXPLOSIVE_SHOT: CardDef = CardDef {
    id: "HUNTER_009",
    name: "Explosive Shot",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 5, target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 多重射击 — 对两个随机敌方随从各造成3点伤害（简化：对一个随机敌方随从造成3点伤害）
pub const MULTI_SHOT: CardDef = CardDef {
    id: "HUNTER_012",
    name: "Multi-Shot",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamageToTwo { amount: 3 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

// 猎人补全
pub const TIMBER_WOLF: CardDef = CardDef {
    id: "HUNTER_010",
    name: "Timber Wolf",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::OtherFriendlyMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const KING_KRUSH: CardDef = CardDef {
    id: "HUNTER_011",
    name: "King Krush",
    card_type: CardType::Minion,
    cost: 9,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};


/// 食腐土狼 — 每当友方随从死亡，获得+2/+1
pub const SCAVENGING_HYENA: CardDef = CardDef {
    id: "HUNTER_013",
    name: "Scavenging Hyena",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: Some(CardEffect::GainStats { attack: 2, health: 1, target: EffectTarget::Self_ }),
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 饥饿的秃鹫 — 每当你召唤随从，抽一张牌
pub const STARVING_BUZZARD: CardDef = CardDef {
    id: "HUNTER_014",
    name: "Starving Buzzard",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: Some(CardEffect::DrawCard { count: 1 }),
    choose_one_effect: None,
    combo_effect: None,
};
