//! 怀旧系列 — 战士 (Warrior)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};
use crate::vanilla;

// 怀旧系列 — 战士 (Warrior)
// ============================================================

pub const EXECUTE: CardDef = CardDef {
    id: "WARRIOR_001",
    name: "Execute",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::DamagedEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const WHIRLWIND: CardDef = CardDef {
    id: "WARRIOR_002",
    name: "Whirlwind",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AllMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const SHIELD_BLOCK: CardDef = CardDef {
    id: "WARRIOR_003",
    name: "Shield Block",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainArmor { amount: 5, target: EffectTarget::Self_ }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const CRUEL_TASKMASTER: CardDef = CardDef {
    id: "WARRIOR_004",
    name: "Cruel Taskmaster",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const KORKRON_ELITE: CardDef = CardDef {
    id: "WARRIOR_005",
    name: "Kor'kron Elite",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ARATHI_WEAPONSMITH: CardDef = CardDef {
    id: "WARRIOR_006",
    name: "Arathi Weaponsmith",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::EquipWeapon {
        card_id: "WARRIOR_006t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const BATTLE_AXE: CardDef = CardDef {
    id: "WARRIOR_006t",
    name: "Battle Axe",
    card_type: CardType::Weapon,
    cost: 1,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const FROTHING_BERSERKER: CardDef = vanilla!("WARRIOR_007", "Frothing Berserker", 3, 2, 4);


pub const WARSONG_COMMANDER: CardDef = CardDef {
    id: "WARRIOR_008",
    name: "Warsong Commander",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const GOREHOWL: CardDef = CardDef {
    id: "WARRIOR_009",
    name: "Gorehowl",
    card_type: CardType::Weapon,
    cost: 7,
    attack: 7,
    health: 0,
    durability: 1,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const GROMMASH_HELLSCREAM: CardDef = CardDef {
    id: "WARRIOR_010",
    name: "Grommash Hellscream",
    card_type: CardType::Minion,
    cost: 8,
    attack: 4,
    health: 9,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const SLAM: CardDef = CardDef {
    id: "WARRIOR_011",
    name: "Slam",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamageAndDraw {
        damage: 2,
        target: EffectTarget::AnyEnemyMinion,
        draw: 1,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const CLEAVE: CardDef = CardDef {
    id: "WARRIOR_012",
    name: "Cleave",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamageToTwo { amount: 2 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ARMORSMITH: CardDef = CardDef {
    id: "WARRIOR_013",
    name: "Armorsmith",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GainArmor { amount: 1, target: EffectTarget::Self_ }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

// 战士补全
pub const INNER_RAGE: CardDef = CardDef {
    id: "WARRIOR_014",
    name: "Inner Rage",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageAndGainAttack {
        damage: 1,
        attack_bonus: 2,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

// Hero attack cards
pub const HEROIC_STRIKE: CardDef = CardDef {
    id: "WARRIOR_015",
    name: "Heroic Strike",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainHeroAttack {
        attack: 4,
        armor: 0,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};


/// 冲锋 — 使一个友方随从获得+2攻击力和冲锋
pub const CHARGE_SPELL: CardDef = CardDef {
    id: "WARRIOR_016",
    name: "Charge",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GrantCharge {
        target: EffectTarget::FriendlyMinion,
        attack_bonus: 2,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 盾牌猛击 — 对一个随从造成等同于你护甲值的伤害
pub const SHIELD_SLAM: CardDef = CardDef {
    id: "WARRIOR_017",
    name: "Shield Slam",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealArmorDamage {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 升级！ — 如果你有武器，使其获得+1/+1；否则装备一把1/3的武器
pub const UPGRADE: CardDef = CardDef {
    id: "WARRIOR_018",
    name: "Upgrade!",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::BuffWeapon {
        attack: 1,
        durability: 1,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 绝命乱斗 — 随机消灭所有随从，只留下一个
pub const BRAWL: CardDef = CardDef {
    id: "WARRIOR_020",
    name: "Brawl",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAllExceptOne),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 致死打击 — 造成4点伤害；如果你的生命值≤12，改为造成6点伤害（简化：造成4点伤害）
pub const MORTAL_STRIKE: CardDef = CardDef {
    id: "WARRIOR_021",
    name: "Mortal Strike",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 战斗怒火 — 每有一个受伤的友方角色，抽一张牌（简化：抽2张牌）
pub const BATTLE_RAGE: CardDef = CardDef {
    id: "WARRIOR_022",
    name: "Battle Rage",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 2 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 狂暴 — 使一个受伤的随从获得+3/+3（简化：给友方随从+3/+3）
pub const RAMPAGE: CardDef = CardDef {
    id: "WARRIOR_023",
    name: "Rampage",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 3,
        health: 3,
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
