//! 怀旧系列 — 萨满 (Shaman)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget};

// 怀旧系列 — 萨满 (Shaman)
// ============================================================

pub const EARTH_SHOCK: CardDef = CardDef {
    id: "SHAMAN_001",
    name: "Earth Shock",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion { target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const LIGHTNING_BOLT: CardDef = CardDef {
    id: "SHAMAN_002",
    name: "Lightning Bolt",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ROCKBITER_WEAPON: CardDef = CardDef {
    id: "SHAMAN_003",
    name: "Rockbiter Weapon",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainHeroAttack { attack: 3, armor: 0 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const FLAMETONGUE_TOTEM: CardDef = CardDef {
    id: "SHAMAN_004",
    name: "Flametongue Totem",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(2), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const HEX: CardDef = CardDef {
    id: "SHAMAN_005",
    name: "Hex",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion { target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const LIGHTNING_STORM: CardDef = CardDef {
    id: "SHAMAN_006",
    name: "Lightning Storm",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 2, target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const FIRE_ELEMENTAL: CardDef = CardDef {
    id: "SHAMAN_007",
    name: "Fire Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const BLOODLUST: CardDef = CardDef {
    id: "SHAMAN_008",
    name: "Bloodlust",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 3, health: 0, target: EffectTarget::AllFriendlyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};


pub const FERAL_SPIRIT: CardDef = CardDef {
    id: "SHAMAN_009",
    name: "Feral Spirit",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const MANA_TIDE_TOTEM: CardDef = CardDef {
    id: "SHAMAN_010",
    name: "Mana Tide Totem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 0,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::DrawCard { count: 1 }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const DOOMHAMMER: CardDef = CardDef {
    id: "SHAMAN_011",
    name: "Doomhammer",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 2,
    health: 0,
    durability: 8,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ALAKIR_THE_WINDLORD: CardDef = CardDef {
    id: "SHAMAN_012",
    name: "Al'Akir the Windlord",
    card_type: CardType::Minion,
    cost: 8,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: true,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

// 萨满补全
pub const TOTEMIC_MIGHT: CardDef = CardDef {
    id: "SHAMAN_013",
    name: "Totemic Might",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 0, health: 2, target: EffectTarget::AllFriendlyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const FROST_SHOCK: CardDef = CardDef {
    id: "SHAMAN_014",
    name: "Frost Shock",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 1, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const DUST_DEVIL: CardDef = CardDef {
    id: "SHAMAN_015",
    name: "Dust Devil",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const FORKED_LIGHTNING: CardDef = CardDef {
    id: "SHAMAN_016",
    name: "Forked Lightning",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const LAVA_BURST: CardDef = CardDef {
    id: "SHAMAN_017",
    name: "Lava Burst",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 5, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const STORMFORGED_AXE: CardDef = CardDef {
    id: "SHAMAN_018",
    name: "Stormforged Axe",
    card_type: CardType::Weapon,
    cost: 2,
    attack: 2,
    health: 0,
    durability: 3,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const EARTH_ELEMENTAL: CardDef = CardDef {
    id: "SHAMAN_019",
    name: "Earth Elemental",
    card_type: CardType::Minion,
    cost: 5,
    attack: 7,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};


/// 风怒 — 使一个友方随从获得风怒
pub const WINDFURY: CardDef = CardDef {
    id: "SHAMAN_016",
    name: "Windfury",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GrantWindfury {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 风语者 — 战吼：使一个友方随从获得风怒
pub const WINDSPEAKER: CardDef = CardDef {
    id: "SHAMAN_017",
    name: "Windspeaker",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GrantWindfury {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 先祖治疗 — 为一个随从恢复所有生命值并使其获得嘲讽（简化：恢复生命+嘲讽）
pub const ANCESTRAL_HEALING: CardDef = CardDef {
    id: "SHAMAN_018",
    name: "Ancestral Healing",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::FullHeal {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
