//! 怀旧系列 — 中立随从。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget};
use crate::vanilla;

// ============================================================
// 怀旧系列 — 中立随从
// ============================================================

pub const BLOODFEN_RAPTOR: CardDef = vanilla!("CLASSIC_001", "Bloodfen Raptor", 2, 3, 2);
pub const BLUEGILL_WARRIOR: CardDef = CardDef {
    id: "CLASSIC_002",
    name: "Bluegill Warrior",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ACIDIC_SWAMP_OOZE: CardDef = CardDef {
    id: "CLASSIC_003",
    name: "Acidic Swamp Ooze",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DestroyWeapon),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const IRONBEAK_OWL: CardDef = CardDef {
    id: "CLASSIC_004",
    name: "Ironbeak Owl",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const KOBOLD_GEOMANCER: CardDef = CardDef {
    id: "CLASSIC_005",
    name: "Kobold Geomancer",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};

pub const MURLOC_TIDEHUNTER: CardDef = CardDef {
    id: "CLASSIC_006",
    name: "Murloc Tidehunter",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_006t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const MURLOC_SCOUT: CardDef = vanilla!("CLASSIC_006t", "Murloc Scout", 1, 1, 1);

pub const HARVEST_GOLEM: CardDef = CardDef {
    id: "CLASSIC_007",
    name: "Harvest Golem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_007t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const DAMAGED_GOLEM: CardDef = vanilla!("CLASSIC_007t", "Damaged Golem", 1, 2, 1);

pub const SENJIN_SHIELDMASTA: CardDef = CardDef {
    id: "CLASSIC_008",
    name: "Sen'jin Shieldmasta",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const DARK_IRON_DWARF: CardDef = CardDef {
    id: "CLASSIC_009",
    name: "Dark Iron Dwarf",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 2,
        health: 0,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const DEFENDER_OF_ARGUS: CardDef = CardDef {
    id: "CLASSIC_010",
    name: "Defender of Argus",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const GNOMISH_INVENTOR: CardDef = CardDef {
    id: "CLASSIC_011",
    name: "Gnomish Inventor",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const SPELLBREAKER: CardDef = CardDef {
    id: "CLASSIC_012",
    name: "Spellbreaker",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const AZURE_DRAKE: CardDef = CardDef {
    id: "CLASSIC_013",
    name: "Azure Drake",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};

pub const SUNWALKER: CardDef = CardDef {
    id: "CLASSIC_014",
    name: "Sunwalker",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ARGENT_COMMANDER: CardDef = CardDef {
    id: "CLASSIC_015",
    name: "Argent Commander",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const WINDFURY_HARPY: CardDef = CardDef {
    id: "CLASSIC_016",
    name: "Windfury Harpy",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const WOLFRIDER: CardDef = CardDef {
    id: "CLASSIC_017",
    name: "Wolfrider",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const AMANI_BERSERKER: CardDef = vanilla!("CLASSIC_018", "Amani Berserker", 2, 2, 3);

pub const FAERIE_DRAGON: CardDef = vanilla!("CLASSIC_019", "Faerie Dragon", 2, 3, 2);
// ============================================================
// 怀旧系列 — 更多中立随从 (2)
// ============================================================

pub const ABUSIVE_SERGEANT: CardDef = CardDef {
    id: "NEUTRAL_001",
    name: "Abusive Sergeant",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 2,
        health: 0,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const YOUTHFUL_BREWMASTER: CardDef = CardDef {
    id: "NEUTRAL_002",
    name: "Youthful Brewmaster",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const MAD_BOMBER: CardDef = CardDef {
    id: "NEUTRAL_003",
    name: "Mad Bomber",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ACOLYTE_OF_PAIN: CardDef = CardDef {
    id: "NEUTRAL_004",
    name: "Acolyte of Pain",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const EARTHEN_RING_FARSEER: CardDef = CardDef {
    id: "NEUTRAL_005",
    name: "Earthen Ring Farseer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 3,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const INJURED_BLADEMASTER: CardDef = CardDef {
    id: "NEUTRAL_006",
    name: "Injured Blademaster",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 7,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const IMP_MASTER: CardDef = CardDef {
    id: "NEUTRAL_007",
    name: "Imp Master",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_006t",
    }),
};

pub const RAGING_WORGEN: CardDef = CardDef {
    id: "NEUTRAL_008",
    name: "Raging Worgen",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const SCARLET_CRUSADER: CardDef = CardDef {
    id: "NEUTRAL_009",
    name: "Scarlet Crusader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const THRALLMAR_FARSEER: CardDef = CardDef {
    id: "NEUTRAL_010",
    name: "Thrallmar Farseer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ANCIENT_BREWMASTER: CardDef = CardDef {
    id: "NEUTRAL_011",
    name: "Ancient Brewmaster",
    card_type: CardType::Minion,
    cost: 4,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const CULT_MASTER: CardDef = CardDef {
    id: "NEUTRAL_012",
    name: "Cult Master",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const OGRE_MAGI: CardDef = CardDef {
    id: "NEUTRAL_013",
    name: "Ogre Magi",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};

pub const SILVERMOON_GUARDIAN: CardDef = CardDef {
    id: "NEUTRAL_014",
    name: "Silvermoon Guardian",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const VIOLET_TEACHER: CardDef = CardDef {
    id: "NEUTRAL_015",
    name: "Violet Teacher",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const MOGUSHAN_WARDEN: CardDef = CardDef {
    id: "NEUTRAL_016",
    name: "Mogu'shan Warden",
    card_type: CardType::Minion,
    cost: 4,
    attack: 1,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ABOMINATION: CardDef = CardDef {
    id: "NEUTRAL_017",
    name: "Abomination",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AllCharacters,
    }),
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const FROSTWOLF_WARLORD: CardDef = CardDef {
    id: "NEUTRAL_018",
    name: "Frostwolf Warlord",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const GADGETZAN_AUCTIONEER: CardDef = CardDef {
    id: "NEUTRAL_019",
    name: "Gadgetzan Auctioneer",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const SILVER_HAND_KNIGHT: CardDef = CardDef {
    id: "NEUTRAL_020",
    name: "Silver Hand Knight",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_020t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const SQUIRE: CardDef = vanilla!("NEUTRAL_020t", "Squire", 1, 2, 2);

pub const FROST_ELEMENTAL: CardDef = CardDef {
    id: "NEUTRAL_021",
    name: "Frost Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::FreezeCharacter {
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const LORD_OF_THE_ARENA: CardDef = CardDef {
    id: "NEUTRAL_022",
    name: "Lord of the Arena",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const RECKLESS_ROCKETEER: CardDef = CardDef {
    id: "NEUTRAL_023",
    name: "Reckless Rocketeer",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ARCHMAGE: CardDef = CardDef {
    id: "NEUTRAL_024",
    name: "Archmage",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};

pub const CORE_HOUND: CardDef = vanilla!("NEUTRAL_025", "Core Hound", 7, 9, 5);

pub const SEA_GIANT: CardDef = vanilla!("NEUTRAL_026", "Sea Giant", 10, 8, 8);
pub const MOLTEN_GIANT: CardDef = vanilla!("NEUTRAL_027", "Molten Giant", 20, 8, 8);
pub const MOUNTAIN_GIANT: CardDef = vanilla!("NEUTRAL_028", "Mountain Giant", 12, 8, 8);

// ============================================================
// 补全卡牌 — 中立
// ============================================================
// 中立 Basic 补全
pub const GRIMSCALE_ORACLE: CardDef = CardDef {
    id: "NEUTRAL_B01",
    name: "Grimscale Oracle",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::OtherFriendlyMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const MURLOC_RAIDER: CardDef = vanilla!("NEUTRAL_B02", "Murloc Raider", 1, 2, 1);
pub const STONETUSK_BOAR: CardDef = CardDef {
    id: "NEUTRAL_B03",
    name: "Stonetusk Boar",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const VOODOO_DOCTOR: CardDef = CardDef {
    id: "NEUTRAL_B04",
    name: "Voodoo Doctor",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 2,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const FROSTWOLF_GRUNT: CardDef = CardDef {
    id: "NEUTRAL_B05",
    name: "Frostwolf Grunt",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const DALARAN_MAGE: CardDef = CardDef {
    id: "NEUTRAL_B06",
    name: "Dalaran Mage",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};
pub const IRONFORGE_RIFLEMAN: CardDef = CardDef {
    id: "NEUTRAL_B07",
    name: "Ironforge Rifleman",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const IRONFUR_GRIZZLY: CardDef = CardDef {
    id: "NEUTRAL_B08",
    name: "Ironfur Grizzly",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const MAGMA_RAGER: CardDef = vanilla!("NEUTRAL_B09", "Magma Rager", 3, 5, 1);
pub const RAZORFEN_HUNTER: CardDef = CardDef {
    id: "NEUTRAL_B10",
    name: "Razorfen Hunter",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_B10t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const BOAR: CardDef = vanilla!("NEUTRAL_B10t", "Boar", 1, 1, 1);
pub const SILVERBACK_PATRIARCH: CardDef = CardDef {
    id: "NEUTRAL_B11",
    name: "Silverback Patriarch",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const DRAGONLING_MECHANIC: CardDef = CardDef {
    id: "NEUTRAL_B12",
    name: "Dragonling Mechanic",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_B12t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const MECHANICAL_DRAGONLING: CardDef =
    vanilla!("NEUTRAL_B12t", "Mechanical Dragonling", 1, 2, 1);
pub const OASIS_SNAPJAW: CardDef = vanilla!("NEUTRAL_B13", "Oasis Snapjaw", 4, 2, 7);
pub const STORMWIND_KNIGHT: CardDef = CardDef {
    id: "NEUTRAL_B14",
    name: "Stormwind Knight",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const BOOTY_BAY_BODYGUARD: CardDef = CardDef {
    id: "NEUTRAL_B15",
    name: "Booty Bay Bodyguard",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const DARKSCALE_HEALER: CardDef = CardDef {
    id: "NEUTRAL_B16",
    name: "Darkscale Healer",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 2,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const NIGHTBLADE: CardDef = CardDef {
    id: "NEUTRAL_B17",
    name: "Nightblade",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::EnemyHero,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const STORMPIKE_COMMANDO: CardDef = CardDef {
    id: "NEUTRAL_B18",
    name: "Stormpike Commando",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const ARGENT_SQUIRE: CardDef = CardDef {
    id: "NEUTRAL_C01",
    name: "Argent Squire",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const LEPER_GNOME: CardDef = CardDef {
    id: "NEUTRAL_C02",
    name: "Leper Gnome",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::EnemyHero,
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const SHIELDBEARER: CardDef = CardDef {
    id: "NEUTRAL_C03",
    name: "Shieldbearer",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const YOUNG_DRAGONHAWK: CardDef = CardDef {
    id: "NEUTRAL_C04",
    name: "Young Dragonhawk",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const FEN_CREEPER: CardDef = CardDef {
    id: "NEUTRAL_C05",
    name: "Fen Creeper",
    card_type: CardType::Minion,
    cost: 5,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const PRIESTESS_OF_ELUNE: CardDef = CardDef {
    id: "NEUTRAL_C06",
    name: "Priestess of Elune",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 4,
        target: EffectTarget::FriendlyHero,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const BLOODMAGE_THALNOS: CardDef = CardDef {
    id: "LEGENDARY_012",
    name: "Bloodmage Thalnos",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
};
pub const SOUTHSHORE_CAPTAIN: CardDef = CardDef {
    id: "NEUTRAL_E01",
    name: "Southsea Captain",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 1,
            health: 1,
        },
        AuraTarget::OtherFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

// 补全 ⬜ Neutral — Coldlight Seer、Murloc Warleader
/// 寒光先知 — 战吼：使所有其他鱼人获得+2生命值（简化：使所有友方随从获得+2生命值）
pub const COLDLIGHT_SEER: CardDef = CardDef {
    id: "NEUTRAL_R01",
    name: "Coldlight Seer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 0,
        health: 2,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
/// 鱼人领军 — 你的其他鱼人获得+2/+1（简化：你的其他友方随从获得+2/+1）
pub const MURLOC_WARLEADER: CardDef = CardDef {
    id: "NEUTRAL_E02",
    name: "Murloc Warleader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 2,
            health: 1,
        },
        AuraTarget::OtherFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};


// ============================================================
// 怀旧系列 — 🔧 卡牌简化版（效果需要新引擎支持，简化为白板或部分效果）
// ============================================================

// 中立 Basic — 无法完全实现的随从
/// 古拉巴什狂暴者 — 每当受到伤害获得+3攻击力（Enrage简化：白板）
pub const GURUBASHI_BERSERKER: CardDef = vanilla!("NEUTRAL_B19", "Gurubashi Berserker", 5, 2, 8);

// 中立 Common — 简化版
/// 南海船工 — 装备武器时获得冲锋（简化：始终有冲锋）
pub const SOUTHSHORE_DECKHAND: CardDef = CardDef {
    id: "NEUTRAL_C07",
    name: "Southsea Deckhand",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
/// 狼人渗透者 — 潜行（简化：白板）
pub const WORGEN_INFILTRATOR: CardDef = vanilla!("NEUTRAL_C08", "Worgen Infiltrator", 1, 2, 1);
/// 血帆袭击者 — 战吼：获得等同于武器攻击力的攻击力（简化：白板）
pub const BLOODSAIL_RAIDER: CardDef = vanilla!("NEUTRAL_C09", "Bloodsail Raider", 2, 2, 3);
/// 丛林猎豹 — 潜行（简化：白板）
pub const JUNGLE_PANTHER: CardDef = vanilla!("NEUTRAL_C10", "Jungle Panther", 3, 4, 2);
/// 牛头人战士 — 嘲讽，激怒：+3攻击力（简化：仅嘲讽）
pub const TAUREN_WARRIOR: CardDef = CardDef {
    id: "NEUTRAL_C11",
    name: "Tauren Warrior",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
/// 食尸鬼 — 每当一个随从死亡，获得+1攻击力（简化：白板）
pub const FLESHEATING_GHOUL: CardDef = vanilla!("NEUTRAL_C12", "Flesheating Ghoul", 3, 3, 3);
/// 恐怖海盗 — 嘲讽，费用随武器减（简化：仅嘲讽）
pub const DREAD_CORSAIR: CardDef = CardDef {
    id: "NEUTRAL_C13",
    name: "Dread Corsair",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
/// 风险投资公司雇佣兵 — 你的随从费用增加（3）（简化：白板）
pub const VENTURE_CO_MERCENARY: CardDef =
    vanilla!("NEUTRAL_C14", "Venture Co. Mercenary", 5, 7, 6);
/// 恶毒铁匠 — 激怒：你的武器获得+2攻击力（简化：白板）
pub const SPITEFUL_SMITH: CardDef = vanilla!("NEUTRAL_C15", "Spiteful Smith", 5, 4, 6);

// 中立 Rare — 简化版
/// 愤怒的小鸡 — 激怒：+5攻击力（简化：白板）
pub const ANGRY_CHICKEN: CardDef = vanilla!("NEUTRAL_R02", "Angry Chicken", 1, 1, 1);
/// 血帆海盗 — 战吼：移除对手武器1点耐久（简化：白板）
pub const BLOODSAIL_CORSAIR: CardDef = vanilla!("NEUTRAL_R03", "Bloodsail Corsair", 1, 1, 2);
/// 光耀之子 — 每当角色被治疗，获得+2攻击力（简化：白板）
pub const LIGHTWARDEN: CardDef = vanilla!("NEUTRAL_R04", "Lightwarden", 1, 1, 2);
/// 鱼人招潮者 — 每当你召唤鱼人，获得+1攻击力（简化：白板）
pub const MURLOC_TIDECALLER: CardDef = vanilla!("NEUTRAL_R05", "Murloc Tidecaller", 1, 1, 2);
/// 奥秘守护者 — 每当奥秘被打出，获得+1/+1（简化：白板）
pub const SECRETKEEPER: CardDef = vanilla!("NEUTRAL_R06", "Secretkeeper", 1, 1, 2);
/// 上古看守者 — 无法攻击（cant_attack 引擎已支持）
pub const ANCIENT_WATCHER: CardDef = CardDef {
    id: "NEUTRAL_R07",
    name: "Ancient Watcher",
    card_type: CardType::Minion,
    cost: 2,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    end_turn_effect: None,
};
/// 疯狂炼金师 — 战吼：交换随从的攻击力和生命值（简化：白板）
pub const CRAZED_ALCHEMIST: CardDef = vanilla!("NEUTRAL_R08", "Crazed Alchemist", 2, 2, 2);
/// 飞刀杂耍者 — 召唤随从后造成1点随机伤害（简化：白板）
pub const KNIFE_JUGGLER: CardDef = vanilla!("NEUTRAL_R09", "Knife Juggler", 2, 3, 2);
/// 魔瘾者 — 施放法术后本回合+2攻击力（简化：白板）
pub const MANA_ADDICT: CardDef = vanilla!("NEUTRAL_R10", "Mana Addict", 2, 1, 3);
/// 日怒保卫者 — 战吼：使相邻随从获得嘲讽（简化：白板）
pub const SUNFURY_PROTECTOR: CardDef = vanilla!("NEUTRAL_R11", "Sunfury Protector", 2, 2, 3);
/// 狂野炎术师 — 施放法术后造成1点AOE（简化：白板）
pub const WILD_PYROMANCER: CardDef = vanilla!("NEUTRAL_R12", "Wild Pyromancer", 2, 3, 2);
/// 报警机器人 — 回合开始时交换手牌随从（简化：白板）
pub const ALARM_O_BOT: CardDef = vanilla!("NEUTRAL_R13", "Alarm-o-Bot", 3, 0, 3);
/// 奥术傀儡 — 冲锋，战吼给对手法力水晶（简化：仅冲锋）
pub const ARCANE_GOLEM: CardDef = CardDef {
    id: "NEUTRAL_R14",
    name: "Arcane Golem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
/// 攻城车 — 回合开始时造成2点随机伤害（简化：白板）
pub const DEMOLISHER: CardDef = vanilla!("NEUTRAL_R15", "Demolisher", 3, 1, 4);
/// 帝王眼镜蛇 — 毒蛇（消灭任何受此伤害的随从）（简化：白板）
pub const EMPEROR_COBRA: CardDef = vanilla!("NEUTRAL_R16", "Emperor Cobra", 3, 2, 3);
/// 任务达人 — 每当你打出一张牌，获得+1/+1（简化：白板）
pub const QUESTING_ADVENTURER: CardDef = vanilla!("NEUTRAL_R17", "Questing Adventurer", 3, 2, 2);
/// 年迈的法师 — 战吼：使相邻随从获得法术伤害+1（简化：白板）
pub const ANCIENT_MAGE: CardDef = vanilla!("NEUTRAL_R18", "Ancient Mage", 4, 2, 5);
/// 暮光幼龙 — 战吼：每有一张手牌获得+1生命值（简化：白板）
pub const TWILIGHT_DRAKE: CardDef = vanilla!("NEUTRAL_R19", "Twilight Drake", 4, 4, 1);
/// 狂奔科多兽 — 战吼：消灭攻击力≤2的随机敌方随从（简化：白板）
pub const STAMPEDING_KODO: CardDef = vanilla!("NEUTRAL_R20", "Stampeding Kodo", 5, 3, 5);

// 中立 Epic — 简化版
/// 鱼人杀手蟹 — 战吼：消灭鱼人并获得+2/+2（简化：白板）
pub const HUNGRY_CRAB: CardDef = vanilla!("NEUTRAL_E03", "Hungry Crab", 1, 1, 2);
/// 末日预言者 — 回合开始时消灭所有随从（简化：白板）
pub const DOOMSAYER: CardDef = vanilla!("NEUTRAL_E04", "Doomsayer", 2, 0, 7);
/// 血骑士 — 战吼：吸收所有圣盾并获得+3/+3（简化：白板）
pub const BLOOD_KNIGHT: CardDef = vanilla!("NEUTRAL_E05", "Blood Knight", 3, 3, 3);
/// 王牌猎人 — 战吼：消灭攻击力≥7的随从（简化：白板）
pub const BIG_GAME_HUNTER: CardDef = vanilla!("NEUTRAL_E06", "Big Game Hunter", 5, 4, 2);
/// 年轻的女祭司 — 回合结束时给随机友方随从+1生命值（简化：白板）
pub const YOUNG_PRIESTESS: CardDef = vanilla!("NEUTRAL_R21", "Young Priestess", 1, 2, 1);
/// 法力怨魂 — 所有随从费用增加（1）（简化：白板）
pub const MANA_WRAITH: CardDef = vanilla!("NEUTRAL_R22", "Mana Wraith", 2, 2, 2);
/// 铸剑大师 — 回合结束时给随机友方随从+1攻击力（简化：白板）
pub const MASTER_SWORDSMITH: CardDef = vanilla!("NEUTRAL_R23", "Master Swordsmith", 2, 1, 3);
/// 小个子召唤师 — 每回合第一张随从费用减（1）（简化：白板）
pub const PINT_SIZED_SUMMONER: CardDef = vanilla!("NEUTRAL_R24", "Pint-Sized Summoner", 2, 2, 2);
/// 军情七处渗透者 — 战吼：摧毁随机敌方奥秘（简化：白板）
pub const SI7_INFILTRATOR: CardDef = vanilla!("NEUTRAL_R25", "SI:7 Infiltrator", 4, 5, 4);
/// 奥秘吞噬者 — 战吼：摧毁所有敌方奥秘并获得+1/+1（简化：白板）
pub const EATER_OF_SECRETS: CardDef = vanilla!("NEUTRAL_R26", "Eater of Secrets", 4, 2, 4);

// ============================================================
