//! 怀旧系列 — 德鲁伊 (Druid)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};

// ============================================================
// 怀旧系列 — 德鲁伊 (Druid)
// ============================================================

pub const INNERVATE: CardDef = CardDef {
    id: "DRUID_001",
    name: "Innervate",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    // 效果: 获得2法力水晶 (在 trigger 中处理)
};

pub const CLAW: CardDef = CardDef {
    id: "DRUID_002",
    name: "Claw",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainHeroAttack {
        attack: 2,
        armor: 2,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const MARK_OF_THE_WILD: CardDef = CardDef {
    id: "DRUID_003",
    name: "Mark of the Wild",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const WRATH: CardDef = CardDef {
    id: "DRUID_004",
    name: "Wrath",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const SWIPE: CardDef = CardDef {
    id: "DRUID_005",
    name: "Swipe",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const STARFIRE: CardDef = CardDef {
    id: "DRUID_006",
    name: "Starfire",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const DRUID_OF_THE_CLAW: CardDef = CardDef {
    id: "DRUID_007",
    name: "Druid of the Claw",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const ANCIENT_OF_LORE: CardDef = CardDef {
    id: "DRUID_008",
    name: "Ancient of Lore",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 2 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

pub const ANCIENT_OF_WAR: CardDef = CardDef {
    id: "DRUID_009",
    name: "Ancient of War",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 10,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

// 怀旧系列 — 更多职业卡牌
// ============================================================

pub const SAVAGE_ROAR: CardDef = CardDef {
    id: "DRUID_010",
    name: "Savage Roar",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};


// 德鲁伊补全
pub const MOONFIRE: CardDef = CardDef {
    id: "DRUID_011",
    name: "Moonfire",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};
pub const WILD_GROWTH: CardDef = CardDef {
    id: "DRUID_012",
    name: "Wild Growth",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};
pub const HEALING_TOUCH: CardDef = CardDef {
    id: "DRUID_013",
    name: "Healing Touch",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};
pub const IRONBARK_PROTECTOR: CardDef = CardDef {
    id: "DRUID_014",
    name: "Ironbark Protector",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};


// 补全德鲁伊 Force of Nature
pub const FORCE_OF_NATURE: CardDef = CardDef {
    id: "DRUID_015",
    name: "Force of Nature",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};
pub const TREANT: CardDef = CardDef {
    id: "DRUID_015t",
    name: "Treant",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

/// 野性赐福 — 使你的随从获得+2/+2和嘲讽（简化：仅+2/+2）
pub const GIFT_OF_THE_WILD: CardDef = CardDef {
    id: "DRUID_016",
    name: "Gift of the Wild",
    card_type: CardType::Spell,
    cost: 8,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

/// 撕咬 — 使你的英雄获得+4攻击力本回合，获得4点护甲
pub const BITE: CardDef = CardDef {
    id: "DRUID_017",
    name: "Bite",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainHeroAttack {
        attack: 4,
        armor: 4,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

/// 野蛮之击 — 对一个随从造成等同于你英雄攻击力的伤害
pub const SAVAGERY: CardDef = CardDef {
    id: "DRUID_018",
    name: "Savagery",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealHeroAttackDamage {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
};

