//! 怀旧系列 — 法师 (Mage)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{CardType, SecretTrigger};
use crate::core::effect::{CardEffect, EffectTarget};

// 怀旧系列 — 法师 (Mage)
// ============================================================

pub const ARCANE_MISSILES: CardDef = CardDef {
    id: "MAGE_001",
    name: "Arcane Missiles",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const FROSTBOLT: CardDef = CardDef {
    id: "MAGE_002",
    name: "Frostbolt",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const ARCANE_INTELLECT: CardDef = CardDef {
    id: "MAGE_003",
    name: "Arcane Intellect",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 2 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const FROST_NOVA: CardDef = CardDef {
    id: "MAGE_004",
    name: "Frost Nova",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::FreezeCharacter { target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const FIREBALL: CardDef = CardDef {
    id: "MAGE_005",
    name: "Fireball",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 6, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const POLYMORPH: CardDef = CardDef {
    id: "MAGE_006",
    name: "Polymorph",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion { target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const WATER_ELEMENTAL: CardDef = CardDef {
    id: "MAGE_007",
    name: "Water Elemental",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const FLAMESTRIKE: CardDef = CardDef {
    id: "MAGE_008",
    name: "Flamestrike",
    card_type: CardType::Spell,
    cost: 7,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 4, target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const PYROBLAST: CardDef = CardDef {
    id: "MAGE_009",
    name: "Pyroblast",
    card_type: CardType::Spell,
    cost: 10,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 10, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};


pub const ICE_BARRIER: CardDef = CardDef {
    id: "MAGE_010",
    name: "Ice Barrier",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: Some(SecretTrigger::AfterFriendlyAttacked),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const ICE_BLOCK: CardDef = CardDef {
    id: "MAGE_011",
    name: "Ice Block",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: Some(SecretTrigger::AfterFriendlyAttacked),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const MIRROR_ENTITY: CardDef = CardDef {
    id: "MAGE_012",
    name: "Mirror Entity",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: Some(SecretTrigger::AfterEnemyMinionPlayed),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const COUNTERSPELL: CardDef = CardDef {
    id: "MAGE_013",
    name: "Counterspell",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: Some(SecretTrigger::WhenEnemySpellCast),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const BLIZZARD: CardDef = CardDef {
    id: "MAGE_014",
    name: "Blizzard",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 2, target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

/// 冰锥术 — 冻结一个随从和相邻的随从（简化：冻结一个随机敌方随从）
pub const CONE_OF_COLD: CardDef = CardDef {
    id: "MAGE_016",
    name: "Cone of Cold",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::FreezeCharacter { target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

// 法师补全
pub const ARCANE_EXPLOSION: CardDef = CardDef {
    id: "MAGE_015",
    name: "Arcane Explosion",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 1, target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};


/// 玛瑙巫师 — 每当你施放一个法术，获得+1攻击力
pub const MANA_WYRM: CardDef = CardDef {
    id: "MAGE_016",
    name: "Mana Wyrm",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: Some(CardEffect::GainStats {
        attack: 1,
        health: 0,
        target: EffectTarget::Self_,
    }),
};
