//! 怀旧系列 — 圣骑士 (Paladin)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};

// ============================================================
// 怀旧系列 — 圣骑士 (Paladin)
// ============================================================

pub const BLESSING_OF_MIGHT: CardDef = CardDef {
    id: "PALADIN_001",
    name: "Blessing of Might",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 3, health: 0, target: EffectTarget::FriendlyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const HUMILITY: CardDef = CardDef {
    id: "PALADIN_002",
    name: "Humility",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack { attack: 1, target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const HOLY_LIGHT: CardDef = CardDef {
    id: "PALADIN_003",
    name: "Holy Light",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth { amount: 8, target: EffectTarget::FriendlyHero }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const BLESSING_OF_KINGS: CardDef = CardDef {
    id: "PALADIN_004",
    name: "Blessing of Kings",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 4, health: 4, target: EffectTarget::FriendlyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const CONSECRATION: CardDef = CardDef {
    id: "PALADIN_005",
    name: "Consecration",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 2, target: EffectTarget::AllEnemyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const TRUESILVER_CHAMPION: CardDef = CardDef {
    id: "PALADIN_006",
    name: "Truesilver Champion",
    card_type: CardType::Weapon,
    cost: 4,
    attack: 4,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const GUARDIAN_OF_KINGS: CardDef = CardDef {
    id: "PALADIN_007",
    name: "Guardian of Kings",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 6,
        target: EffectTarget::FriendlyHero,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const TIRION_FORDRING: CardDef = CardDef {
    id: "PALADIN_008",
    name: "Tirion Fordring",
    card_type: CardType::Minion,
    cost: 8,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::EquipWeapon {
        card_id: "PALADIN_008t",
    }),
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
pub const ASHBRINGER: CardDef = CardDef {
    id: "PALADIN_008t",
    name: "Ashbringer",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 5,
    health: 0,
    durability: 3,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const ALDOR_PEACEKEEPER: CardDef = CardDef {
    id: "PALADIN_009",
    name: "Aldor Peacekeeper",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack {
        attack: 1,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};


pub const EQUALITY: CardDef = CardDef {
    id: "PALADIN_010",
    name: "Equality",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack { attack: 0, target: EffectTarget::AllMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const HAMMER_OF_WRATH: CardDef = CardDef {
    id: "PALADIN_011",
    name: "Hammer of Wrath",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const AVENGING_WRATH: CardDef = CardDef {
    id: "PALADIN_012",
    name: "Avenging Wrath",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 8, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const LAY_ON_HANDS: CardDef = CardDef {
    id: "PALADIN_013",
    name: "Lay on Hands",
    card_type: CardType::Spell,
    cost: 8,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth { amount: 8, target: EffectTarget::FriendlyHero }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

/// 神圣愤怒 — 抽一张牌，造成等同于其法力消耗的伤害（简化：仅抽牌）
pub const HOLY_WRATH: CardDef = CardDef {
    id: "PALADIN_017",
    name: "Holy Wrath",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 5, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
/// 正义 — 使你的随从获得圣盾（简化版，无法实现群体圣盾）
pub const RIGHTEOUSNESS: CardDef = CardDef {
    id: "PALADIN_018",
    name: "Righteousness",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 0, health: 0, target: EffectTarget::AllFriendlyMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

// 圣骑士补全
pub const HAND_OF_PROTECTION: CardDef = CardDef {
    id: "PALADIN_014",
    name: "Hand of Protection",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats { attack: 0, health: 0, target: EffectTarget::FriendlyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
pub const LIGHTS_JUSTICE: CardDef = CardDef {
    id: "PALADIN_015",
    name: "Light's Justice",
    card_type: CardType::Weapon,
    cost: 1,
    attack: 1,
    health: 0,
    durability: 4,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
pub const ARGENT_PROTECTOR: CardDef = CardDef {
    id: "PALADIN_016",
    name: "Argent Protector",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};


/// 受祝福的勇士 — 使一个随从的攻击力翻倍
pub const BLESSED_CHAMPION: CardDef = CardDef {
    id: "PALADIN_016",
    name: "Blessed Champion",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DoubleAttack {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
