//! Classic set — Rogue.
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};

// Classic set — Rogue
// ============================================================

pub const BACKSTAB: CardDef = CardDef {
    id: "ROGUE_001",
    name: "Backstab",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const DEADLY_POISON: CardDef = CardDef {
    id: "ROGUE_002",
    name: "Deadly Poison",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::BuffWeapon {
        attack: 2,
        durability: 0,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const EVISCERATE: CardDef = CardDef {
    id: "ROGUE_003",
    name: "Eviscerate",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::AnyEnemy,
    }),
    attack_equals_health: false,
};

pub const SAP: CardDef = CardDef {
    id: "ROGUE_004",
    name: "Sap",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SI7_AGENT: CardDef = CardDef {
    id: "ROGUE_005",
    name: "SI:7 Agent",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    attack_equals_health: false,
};

pub const ASSASSINATE: CardDef = CardDef {
    id: "ROGUE_006",
    name: "Assassinate",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SPRINT: CardDef = CardDef {
    id: "ROGUE_007",
    name: "Sprint",
    card_type: CardType::Spell,
    cost: 7,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 4 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FAN_OF_KNIVES: CardDef = CardDef {
    id: "ROGUE_008",
    name: "Fan of Knives",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AllEnemyMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const PREPARATION: CardDef = CardDef {
    id: "ROGUE_009",
    name: "Preparation",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const COLD_BLOOD: CardDef = CardDef {
    id: "ROGUE_010",
    name: "Cold Blood",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::GainStats {
        attack: 4,
        health: 0,
        target: EffectTarget::FriendlyMinion,
    }),
    attack_equals_health: false,
};

pub const DEFIAS_RINGLEADER: CardDef = CardDef {
    id: "ROGUE_011",
    name: "Defias Ringleader",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::SummonMinion { card_id: "ROGUE_t" }),
    attack_equals_health: false,
};

pub const EDWIN_VANCLEEF: CardDef = CardDef {
    id: "ROGUE_012",
    name: "Edwin VanCleef",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::GainStats {
        attack: 4,
        health: 4,
        target: EffectTarget::Self_,
    }),
    attack_equals_health: false,
};

// Rogue additions
pub const SINISTER_STRIKE: CardDef = CardDef {
    id: "ROGUE_013",
    name: "Sinister Strike",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::EnemyHero,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const SHIV: CardDef = CardDef {
    id: "ROGUE_014",
    name: "Shiv",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const ASSASSINS_BLADE: CardDef = CardDef {
    id: "ROGUE_015",
    name: "Assassin's Blade",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 3,
    health: 0,
    durability: 4,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Vanish — return all minions to their owner's hand
pub const VANISH: CardDef = CardDef {
    id: "ROGUE_016",
    name: "Vanish",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ReturnAllToHand),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Combo / Shadowstep / Betrayal / Blade Flurry / Poison / Stealth
// ============================================================

/// Headcrack — deal 2 damage to the enemy hero. Combo: return this card to your hand.
pub const HEADCRACK: CardDef = CardDef {
    id: "ROGUE_017",
    name: "Headcrack",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::EnemyHero,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::DealDamageAndReturnToHand {
        amount: 2,
        target: EffectTarget::EnemyHero,
    }),
    attack_equals_health: false,
};

/// Kidnapper — Combo: return an enemy minion to its owner's hand.
pub const KIDNAPPER: CardDef = CardDef {
    id: "ROGUE_018",
    name: "Kidnapper",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: Some(CardEffect::ReturnToHand {
        target: EffectTarget::AnyEnemyMinion,
    }),
    attack_equals_health: false,
};

/// Shadowstep — return a friendly minion to your hand; it costs (2) less.
pub const SHADOWSTEP: CardDef = CardDef {
    id: "ROGUE_019",
    name: "Shadowstep",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ReturnFriendlyToHandAndReduceCost { amount: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Betrayal — deal damage equal to the target's Attack to its adjacent minions.
pub const BETRAYAL: CardDef = CardDef {
    id: "ROGUE_020",
    name: "Betrayal",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AdjacentDamage),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Blade Flurry — destroy your weapon and deal damage equal to its Attack to all enemies.
pub const BLADE_FLURRY: CardDef = CardDef {
    id: "ROGUE_021",
    name: "Blade Flurry",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyWeaponAndDealAttackToEnemies),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Patient Assassin — Stealth, Poison (keywords applied by apply_card_keywords).
pub const PATIENT_ASSASSIN: CardDef = CardDef {
    id: "ROGUE_022",
    name: "Patient Assassin",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Perdition's Blade — Weapon 2/2; Battlecry: deal 1 damage.
pub const PERDITIONS_BLADE: CardDef = CardDef {
    id: "ROGUE_023",
    name: "Perdition's Blade",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Master of Disguise — Battlecry: give a friendly minion Stealth.
pub const MASTER_OF_DISGUISE: CardDef = CardDef {
    id: "ROGUE_024",
    name: "Master of Disguise",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GrantStealth),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 3 additions — stealing
// ============================================================

/// Pilfer — add a random card from another class to your hand.
/// (This engine does not model classes; simplified to a random non-Rogue card)
pub const PILFER: CardDef = CardDef {
    id: "ROGUE_025",
    name: "Pilfer",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: crate::core::effect::RandomPool::OtherClass,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
