//! 怀旧系列 — 传奇卡牌 (Legendary)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};
use crate::vanilla;

// 怀旧系列 — 传奇卡牌 (Legendary)
// ============================================================

pub const CAIRNE_BLOODHOOF: CardDef = CardDef {
    id: "LEGENDARY_001",
    name: "Cairne Bloodhoof",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_001t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const BAINE_BLOODHOOF: CardDef = vanilla!("LEGENDARY_001t", "Baine Bloodhoof", 6, 4, 5);

pub const HOGGER: CardDef = CardDef {
    id: "LEGENDARY_002",
    name: "Hogger",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_002t",
    }),
};
pub const GNOLL: CardDef = CardDef {
    id: "LEGENDARY_002t",
    name: "Gnoll",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ILLIDAN_STORMRAGE: CardDef = CardDef {
    id: "LEGENDARY_003",
    name: "Illidan Stormrage",
    card_type: CardType::Minion,
    cost: 6,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_003t",
    }),
};
pub const FLAME_OF_AZZINOTH: CardDef = vanilla!("LEGENDARY_003t", "Flame of Azzinoth", 1, 2, 1);

pub const THE_BEAST: CardDef = CardDef {
    id: "LEGENDARY_004",
    name: "The Beast",
    card_type: CardType::Minion,
    cost: 6,
    attack: 9,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_004t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};
pub const FINKLE_EINHORN: CardDef = vanilla!("LEGENDARY_004t", "Finkle Einhorn", 3, 3, 3);

pub const BARON_GEDDON: CardDef = CardDef {
    id: "LEGENDARY_005",
    name: "Baron Geddon",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AllCharacters,
    }),
};

pub const GRUUL: CardDef = CardDef {
    id: "LEGENDARY_006",
    name: "Gruul",
    card_type: CardType::Minion,
    cost: 8,
    attack: 7,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
};

pub const RAGNAROS_THE_FIRELORD: CardDef = CardDef {
    id: "LEGENDARY_007",
    name: "Ragnaros the Firelord",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    end_turn_effect: Some(CardEffect::DealDamage {
        amount: 8,
        target: EffectTarget::AnyEnemy,
    }),
};

pub const ALEXSTRASZA: CardDef = CardDef {
    id: "LEGENDARY_008",
    name: "Alexstrasza",
    card_type: CardType::Minion,
    cost: 9,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack {
        attack: 15,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const MALYGOS: CardDef = CardDef {
    id: "LEGENDARY_009",
    name: "Malygos",
    card_type: CardType::Minion,
    cost: 9,
    attack: 4,
    health: 12,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 5,
    cant_attack: false,
    end_turn_effect: None,
};

pub const ONYXIA: CardDef = CardDef {
    id: "LEGENDARY_010",
    name: "Onyxia",
    card_type: CardType::Minion,
    cost: 9,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

pub const DEATHWING: CardDef = CardDef {
    id: "LEGENDARY_011",
    name: "Deathwing",
    card_type: CardType::Minion,
    cost: 10,
    attack: 12,
    health: 12,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::AllMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
};

