//! Classic set — Warlock.
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget};

// Classic set — Warlock
// ============================================================

pub const SOULFIRE: CardDef = CardDef {
    id: "WARLOCK_001",
    name: "Soulfire",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FLAME_IMP: CardDef = CardDef {
    id: "WARLOCK_002",
    name: "Flame Imp",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const MORTAL_COIL: CardDef = CardDef {
    id: "WARLOCK_003",
    name: "Mortal Coil",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const VOIDWALKER: CardDef = CardDef {
    id: "WARLOCK_004",
    name: "Voidwalker",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const HELLFIRE: CardDef = CardDef {
    id: "WARLOCK_005",
    name: "Hellfire",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const DRAIN_LIFE: CardDef = CardDef {
    id: "WARLOCK_006",
    name: "Drain Life",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const DOOMGUARD: CardDef = CardDef {
    id: "WARLOCK_007",
    name: "Doomguard",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SHADOW_BOLT: CardDef = CardDef {
    id: "WARLOCK_008",
    name: "Shadow Bolt",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const TWISTING_NETHER: CardDef = CardDef {
    id: "WARLOCK_009",
    name: "Twisting Nether",
    card_type: CardType::Spell,
    cost: 8,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::AllMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const LORD_JARAXXUS: CardDef = CardDef {
    id: "WARLOCK_010",
    name: "Lord Jaraxxus",
    card_type: CardType::Minion,
    cost: 9,
    attack: 3,
    health: 15,
    durability: 0,
    battlecry: Some(CardEffect::EquipWeapon {
        card_id: "WARLOCK_010t",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const BLOOD_FURY: CardDef = CardDef {
    id: "WARLOCK_010t",
    name: "Blood Fury",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 3,
    health: 0,
    durability: 8,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Warlock additions
pub const DREAD_INFERNAL: CardDef = CardDef {
    id: "WARLOCK_011",
    name: "Dread Infernal",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const PIT_LORD: CardDef = CardDef {
    id: "WARLOCK_012",
    name: "Pit Lord",
    card_type: CardType::Minion,
    cost: 4,
    attack: 5,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 5,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Felstalker — Battlecry: discard a random card from your hand
pub const FELSTALKER: CardDef = CardDef {
    id: "WARLOCK_016",
    name: "Felstalker",
    card_type: CardType::Minion,
    cost: 2,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DiscardRandomCard),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Siphon Soul — destroy a minion, restore 3 Health to your hero
pub const SIPHON_SOUL: CardDef = CardDef {
    id: "WARLOCK_017",
    name: "Siphon Soul",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAndHeal {
        target: EffectTarget::AnyEnemyMinion,
        heal: 3,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Shadowflame — destroy a friendly minion, deal damage equal to its Attack to all enemy minions
pub const SHADOWFLAME: CardDef = CardDef {
    id: "WARLOCK_018",
    name: "Shadowflame",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAndAOE {
        target: EffectTarget::AllEnemyMinions,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Felguard — Battlecry: destroy one of your mana crystals
pub const FELGUARD: CardDef = CardDef {
    id: "WARLOCK_019",
    name: "Felguard",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DestroyManaCrystal),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Sense Demons — draw two Demons from your deck
pub const SENSE_DEMONS: CardDef = CardDef {
    id: "WARLOCK_020",
    name: "Sense Demons",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCardByRace {
        count: 2,
        race: crate::core::component::Race::Demon,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Demonfire — deal 2 damage to a minion; if it is a friendly Demon, give it +2/+2 instead
pub const DEMONFIRE: CardDef = CardDef {
    id: "WARLOCK_021",
    name: "Demonfire",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::Demonfire {
        damage: 2,
        attack_bonus: 2,
        health_bonus: 2,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Void Terror — Battlecry: destroy adjacent minions and gain their Attack and Health
pub const VOID_TERROR: CardDef = CardDef {
    id: "WARLOCK_022",
    name: "Void Terror",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAdjacent { gain_stats: true }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// ============================================================
// Tier 1 additions — Warlock (docs/classic-cards-roadmap.md)
// ============================================================

/// Siegebreaker — Taunt; your other Demons have +1 Attack
pub const SIEGEBREAKER: CardDef = CardDef {
    id: "WARLOCK_T01",
    name: "Siegebreaker",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(crate::core::component::Race::Demon),
    hero_power: None,
    aura: Some((
        AuraEffect::GainAttack(1),
        AuraTarget::OtherFriendlyRace(crate::core::component::Race::Demon),
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Summoning Portal
// ============================================================

/// Summoning Portal — your minions cost (2) less, but not less than (1).
pub const SUMMONING_PORTAL: CardDef = CardDef {
    id: "WARLOCK_023",
    name: "Summoning Portal",
    card_type: CardType::Minion,
    cost: 4,
    attack: 0,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: Some((
        crate::core::component::AuraEffect::ReduceMinionCost { amount: 2, min: 1 },
        crate::core::component::AuraTarget::AllFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Corruption
// ============================================================

/// Corruption — choose an enemy minion. Destroy it at the start of your turn.
pub const CORRUPTION: CardDef = CardDef {
    id: "WARLOCK_024",
    name: "Corruption",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::Corrupt),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 3 additions — random Demons
// ============================================================

/// Call of the Void — add a random Demon to your hand.
pub const CALL_OF_THE_VOID: CardDef = CardDef {
    id: "WARLOCK_025",
    name: "Call of the Void",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: crate::core::effect::RandomPool::Demon,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Bane of Doom — deal 2 damage to a character. If it dies, summon a random Demon.
pub const BANE_OF_DOOM: CardDef = CardDef {
    id: "WARLOCK_026",
    name: "Bane of Doom",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamageAndSummonIfKilled {
        amount: 2,
        pool: crate::core::effect::RandomPool::Demon,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
