//! 怀旧系列 — 潜行者 (Rogue)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};

// 怀旧系列 — 潜行者 (Rogue)
// ============================================================

pub const BACKSTAB: CardDef = CardDef {
    id: "ROGUE_001",
    name: "Backstab",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const DEADLY_POISON: CardDef = CardDef {
    id: "ROGUE_002",
    name: "Deadly Poison",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const EVISCERATE: CardDef = CardDef {
    id: "ROGUE_003",
    name: "Eviscerate",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const SAP: CardDef = CardDef {
    id: "ROGUE_004",
    name: "Sap",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const SI7_AGENT: CardDef = CardDef {
    id: "ROGUE_005",
    name: "SI:7 Agent",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const ASSASSINATE: CardDef = CardDef {
    id: "ROGUE_006",
    name: "Assassinate",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const SPRINT: CardDef = CardDef {
    id: "ROGUE_007",
    name: "Sprint",
    card_type: CardType::Spell,
    cost: 7,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const FAN_OF_KNIVES: CardDef = CardDef {
    id: "ROGUE_008",
    name: "Fan of Knives",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};


pub const PREPARATION: CardDef = CardDef {
    id: "ROGUE_009",
    name: "Preparation",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const COLD_BLOOD: CardDef = CardDef {
    id: "ROGUE_010",
    name: "Cold Blood",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const DEFIAS_RINGLEADER: CardDef = CardDef {
    id: "ROGUE_011",
    name: "Defias Ringleader",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

pub const EDWIN_VANCLEEF: CardDef = CardDef {
    id: "ROGUE_012",
    name: "Edwin VanCleef",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

// 潜行者补全
pub const SINISTER_STRIKE: CardDef = CardDef {
    id: "ROGUE_013",
    name: "Sinister Strike",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
pub const SHIV: CardDef = CardDef {
    id: "ROGUE_014",
    name: "Shiv",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};
pub const ASSASSINS_BLADE: CardDef = CardDef {
    id: "ROGUE_015",
    name: "Assassin's Blade",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 3,
    health: 0,
    durability: 4,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
};

