//! 怀旧系列 — 传奇卡牌 (Legendary)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};
use crate::vanilla;

// 怀旧系列 — 传奇卡牌 (Legendary)
// ============================================================

pub const CAIRNE_BLOODHOOF: CardDef = CardDef {
    id: "LEGENDARY_001",
    name: "Cairne Bloodhoof",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_001t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const BAINE_BLOODHOOF: CardDef = vanilla!("LEGENDARY_001t", "Baine Bloodhoof", 6, 4, 5);

pub const HOGGER: CardDef = CardDef {
    id: "LEGENDARY_002",
    name: "Hogger",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_002t",
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const GNOLL: CardDef = CardDef {
    id: "LEGENDARY_002t",
    name: "Gnoll",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ILLIDAN_STORMRAGE: CardDef = CardDef {
    id: "LEGENDARY_003",
    name: "Illidan Stormrage",
    card_type: CardType::Minion,
    cost: 6,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_003t",
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const FLAME_OF_AZZINOTH: CardDef = vanilla!("LEGENDARY_003t", "Flame of Azzinoth", 1, 2, 1);

pub const THE_BEAST: CardDef = CardDef {
    id: "LEGENDARY_004",
    name: "The Beast",
    card_type: CardType::Minion,
    cost: 6,
    attack: 9,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_004t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
pub const FINKLE_EINHORN: CardDef = vanilla!("LEGENDARY_004t", "Finkle Einhorn", 3, 3, 3);

pub const BARON_GEDDON: CardDef = CardDef {
    id: "LEGENDARY_005",
    name: "Baron Geddon",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AllCharacters,
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const GRUUL: CardDef = CardDef {
    id: "LEGENDARY_006",
    name: "Gruul",
    card_type: CardType::Minion,
    cost: 8,
    attack: 7,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const RAGNAROS_THE_FIRELORD: CardDef = CardDef {
    id: "LEGENDARY_007",
    name: "Ragnaros the Firelord",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::DealDamage {
        amount: 8,
        target: EffectTarget::AnyEnemy,
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ALEXSTRASZA: CardDef = CardDef {
    id: "LEGENDARY_008",
    name: "Alexstrasza",
    card_type: CardType::Minion,
    cost: 9,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::SetAttack {
        attack: 15,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const MALYGOS: CardDef = CardDef {
    id: "LEGENDARY_009",
    name: "Malygos",
    card_type: CardType::Minion,
    cost: 9,
    attack: 4,
    health: 12,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 5,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const ONYXIA: CardDef = CardDef {
    id: "LEGENDARY_010",
    name: "Onyxia",
    card_type: CardType::Minion,
    cost: 9,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

pub const DEATHWING: CardDef = CardDef {
    id: "LEGENDARY_011",
    name: "Deathwing",
    card_type: CardType::Minion,
    cost: 10,
    attack: 12,
    health: 12,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::AllMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};


/// 绿皮船长 — 战吼：使你的武器获得+1/+1
pub const CAPTAIN_GREENSKIN: CardDef = CardDef {
    id: "LEGENDARY_018",
    name: "Captain Greenskin",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::BuffWeapon {
        attack: 1,
        durability: 1,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 哈里森·琼斯 — 战吼：摧毁对手的武器，并抽等同于其耐久度的牌
pub const HARRISON_JONES: CardDef = CardDef {
    id: "LEGENDARY_019",
    name: "Harrison Jones",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DestroyWeaponAndDraw),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 黑骑士 — 战吼：消灭一个具有嘲讽的敌方随从
pub const THE_BLACK_KNIGHT: CardDef = CardDef {
    id: "LEGENDARY_020",
    name: "The Black Knight",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion { target: EffectTarget::TauntEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 米尔豪斯·法力风暴 — 2费4/4，战吼：敌方下回合法术费用为0（简化：无负面效果）
pub const MILLHOUSE_MANASTORM: CardDef = CardDef {
    id: "LEGENDARY_021",
    name: "Millhouse Manastorm",
    card_type: CardType::Minion,
    cost: 2,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};

/// 纳特·帕格 — 在你的回合结束时，有50%几率抽一张牌（简化：回合结束抽一张牌）
pub const NAT_PAGLE: CardDef = CardDef {
    id: "LEGENDARY_022",
    name: "Nat Pagle",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::DrawCard { count: 1 }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
};
