//! Classic set — neutral minions.
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType};
use crate::core::effect::{CardEffect, EffectTarget, RandomPool};
use crate::vanilla;

// ============================================================
// Classic set — neutral minions
// ============================================================

pub const BLOODFEN_RAPTOR: CardDef = vanilla!("CLASSIC_001", "Bloodfen Raptor", 2, 3, 2);
pub const BLUEGILL_WARRIOR: CardDef = CardDef {
    id: "CLASSIC_002",
    name: "Bluegill Warrior",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ACIDIC_SWAMP_OOZE: CardDef = CardDef {
    id: "CLASSIC_003",
    name: "Acidic Swamp Ooze",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DestroyWeapon),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const IRONBEAK_OWL: CardDef = CardDef {
    id: "CLASSIC_004",
    name: "Ironbeak Owl",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const KOBOLD_GEOMANCER: CardDef = CardDef {
    id: "CLASSIC_005",
    name: "Kobold Geomancer",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const MURLOC_TIDEHUNTER: CardDef = CardDef {
    id: "CLASSIC_006",
    name: "Murloc Tidehunter",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_006t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const MURLOC_SCOUT: CardDef = vanilla!("CLASSIC_006t", "Murloc Scout", 1, 1, 1);

pub const HARVEST_GOLEM: CardDef = CardDef {
    id: "CLASSIC_007",
    name: "Harvest Golem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_007t",
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const DAMAGED_GOLEM: CardDef = vanilla!("CLASSIC_007t", "Damaged Golem", 1, 2, 1);

pub const SENJIN_SHIELDMASTA: CardDef = CardDef {
    id: "CLASSIC_008",
    name: "Sen'jin Shieldmasta",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const DARK_IRON_DWARF: CardDef = CardDef {
    id: "CLASSIC_009",
    name: "Dark Iron Dwarf",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 2,
        health: 0,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const DEFENDER_OF_ARGUS: CardDef = CardDef {
    id: "CLASSIC_010",
    name: "Defender of Argus",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const GNOMISH_INVENTOR: CardDef = CardDef {
    id: "CLASSIC_011",
    name: "Gnomish Inventor",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SPELLBREAKER: CardDef = CardDef {
    id: "CLASSIC_012",
    name: "Spellbreaker",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const AZURE_DRAKE: CardDef = CardDef {
    id: "CLASSIC_013",
    name: "Azure Drake",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SUNWALKER: CardDef = CardDef {
    id: "CLASSIC_014",
    name: "Sunwalker",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ARGENT_COMMANDER: CardDef = CardDef {
    id: "CLASSIC_015",
    name: "Argent Commander",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const WINDFURY_HARPY: CardDef = CardDef {
    id: "CLASSIC_016",
    name: "Windfury Harpy",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const WOLFRIDER: CardDef = CardDef {
    id: "CLASSIC_017",
    name: "Wolfrider",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const AMANI_BERSERKER: CardDef = vanilla!("CLASSIC_018", "Amani Berserker", 2, 2, 3);

pub const FAERIE_DRAGON: CardDef = vanilla!("CLASSIC_019", "Faerie Dragon", 2, 3, 2);
// ============================================================
// Classic set — more neutral minions (2)
// ============================================================

pub const ABUSIVE_SERGEANT: CardDef = CardDef {
    id: "NEUTRAL_001",
    name: "Abusive Sergeant",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 2,
        health: 0,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const YOUTHFUL_BREWMASTER: CardDef = CardDef {
    id: "NEUTRAL_002",
    name: "Youthful Brewmaster",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const MAD_BOMBER: CardDef = CardDef {
    id: "NEUTRAL_003",
    name: "Mad Bomber",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ACOLYTE_OF_PAIN: CardDef = CardDef {
    id: "NEUTRAL_004",
    name: "Acolyte of Pain",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    // Draw-on-damage is a trigger, not a deathrattle (roadmap G2) — registered
    // by ID in cards/mod.rs apply_card_keywords.
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const EARTHEN_RING_FARSEER: CardDef = CardDef {
    id: "NEUTRAL_005",
    name: "Earthen Ring Farseer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 3,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const INJURED_BLADEMASTER: CardDef = CardDef {
    id: "NEUTRAL_006",
    name: "Injured Blademaster",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 7,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const IMP_MASTER: CardDef = CardDef {
    id: "NEUTRAL_007",
    name: "Imp Master",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_006t",
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const RAGING_WORGEN: CardDef = CardDef {
    id: "NEUTRAL_008",
    name: "Raging Worgen",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SCARLET_CRUSADER: CardDef = CardDef {
    id: "NEUTRAL_009",
    name: "Scarlet Crusader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const THRALLMAR_FARSEER: CardDef = CardDef {
    id: "NEUTRAL_010",
    name: "Thrallmar Farseer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ANCIENT_BREWMASTER: CardDef = CardDef {
    id: "NEUTRAL_011",
    name: "Ancient Brewmaster",
    card_type: CardType::Minion,
    cost: 4,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const CULT_MASTER: CardDef = CardDef {
    id: "NEUTRAL_012",
    name: "Cult Master",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: Some(CardEffect::DrawCard { count: 1 }),
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const OGRE_MAGI: CardDef = CardDef {
    id: "NEUTRAL_013",
    name: "Ogre Magi",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SILVERMOON_GUARDIAN: CardDef = CardDef {
    id: "NEUTRAL_014",
    name: "Silvermoon Guardian",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const VIOLET_TEACHER: CardDef = CardDef {
    id: "NEUTRAL_015",
    name: "Violet Teacher",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: Some(CardEffect::SummonMinion {
        card_id: "CLASSIC_VT",
    }),
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const MOGUSHAN_WARDEN: CardDef = CardDef {
    id: "NEUTRAL_016",
    name: "Mogu'shan Warden",
    card_type: CardType::Minion,
    cost: 4,
    attack: 1,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ABOMINATION: CardDef = CardDef {
    id: "NEUTRAL_017",
    name: "Abomination",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AllCharacters,
    }),
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const FROSTWOLF_WARLORD: CardDef = CardDef {
    id: "NEUTRAL_018",
    name: "Frostwolf Warlord",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const GADGETZAN_AUCTIONEER: CardDef = CardDef {
    id: "NEUTRAL_019",
    name: "Gadgetzan Auctioneer",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: Some(CardEffect::DrawCard { count: 1 }),
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const SILVER_HAND_KNIGHT: CardDef = CardDef {
    id: "NEUTRAL_020",
    name: "Silver Hand Knight",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_020t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const SQUIRE: CardDef = vanilla!("NEUTRAL_020t", "Squire", 1, 2, 2);

pub const FROST_ELEMENTAL: CardDef = CardDef {
    id: "NEUTRAL_021",
    name: "Frost Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::FreezeCharacter {
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const LORD_OF_THE_ARENA: CardDef = CardDef {
    id: "NEUTRAL_022",
    name: "Lord of the Arena",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const RECKLESS_ROCKETEER: CardDef = CardDef {
    id: "NEUTRAL_023",
    name: "Reckless Rocketeer",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const ARCHMAGE: CardDef = CardDef {
    id: "NEUTRAL_024",
    name: "Archmage",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

pub const CORE_HOUND: CardDef = vanilla!("NEUTRAL_025", "Core Hound", 7, 9, 5);

pub const SEA_GIANT: CardDef = vanilla!("NEUTRAL_026", "Sea Giant", 10, 8, 8);
pub const MOLTEN_GIANT: CardDef = vanilla!("NEUTRAL_027", "Molten Giant", 20, 8, 8);
pub const MOUNTAIN_GIANT: CardDef = vanilla!("NEUTRAL_028", "Mountain Giant", 12, 8, 8);

// ============================================================
// Completed cards — Neutral
// ============================================================
// Neutral Basic additions
pub const GRIMSCALE_ORACLE: CardDef = CardDef {
    id: "NEUTRAL_B01",
    name: "Grimscale Oracle",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::OtherFriendlyMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const MURLOC_RAIDER: CardDef = vanilla!("NEUTRAL_B02", "Murloc Raider", 1, 2, 1);
pub const STONETUSK_BOAR: CardDef = CardDef {
    id: "NEUTRAL_B03",
    name: "Stonetusk Boar",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const VOODOO_DOCTOR: CardDef = CardDef {
    id: "NEUTRAL_B04",
    name: "Voodoo Doctor",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 2,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const FROSTWOLF_GRUNT: CardDef = CardDef {
    id: "NEUTRAL_B05",
    name: "Frostwolf Grunt",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const DALARAN_MAGE: CardDef = CardDef {
    id: "NEUTRAL_B06",
    name: "Dalaran Mage",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const IRONFORGE_RIFLEMAN: CardDef = CardDef {
    id: "NEUTRAL_B07",
    name: "Ironforge Rifleman",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const IRONFUR_GRIZZLY: CardDef = CardDef {
    id: "NEUTRAL_B08",
    name: "Ironfur Grizzly",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const MAGMA_RAGER: CardDef = vanilla!("NEUTRAL_B09", "Magma Rager", 3, 5, 1);
pub const RAZORFEN_HUNTER: CardDef = CardDef {
    id: "NEUTRAL_B10",
    name: "Razorfen Hunter",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_B10t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const BOAR: CardDef = vanilla!("NEUTRAL_B10t", "Boar", 1, 1, 1);
pub const SILVERBACK_PATRIARCH: CardDef = CardDef {
    id: "NEUTRAL_B11",
    name: "Silverback Patriarch",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const DRAGONLING_MECHANIC: CardDef = CardDef {
    id: "NEUTRAL_B12",
    name: "Dragonling Mechanic",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "NEUTRAL_B12t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const MECHANICAL_DRAGONLING: CardDef =
    vanilla!("NEUTRAL_B12t", "Mechanical Dragonling", 1, 2, 1);
pub const OASIS_SNAPJAW: CardDef = vanilla!("NEUTRAL_B13", "Oasis Snapjaw", 4, 2, 7);
pub const STORMWIND_KNIGHT: CardDef = CardDef {
    id: "NEUTRAL_B14",
    name: "Stormwind Knight",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const BOOTY_BAY_BODYGUARD: CardDef = CardDef {
    id: "NEUTRAL_B15",
    name: "Booty Bay Bodyguard",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const DARKSCALE_HEALER: CardDef = CardDef {
    id: "NEUTRAL_B16",
    name: "Darkscale Healer",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 2,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const NIGHTBLADE: CardDef = CardDef {
    id: "NEUTRAL_B17",
    name: "Nightblade",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::EnemyHero,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const STORMPIKE_COMMANDO: CardDef = CardDef {
    id: "NEUTRAL_B18",
    name: "Stormpike Commando",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const ARGENT_SQUIRE: CardDef = CardDef {
    id: "NEUTRAL_C01",
    name: "Argent Squire",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const LEPER_GNOME: CardDef = CardDef {
    id: "NEUTRAL_C02",
    name: "Leper Gnome",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::EnemyHero,
    }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const SHIELDBEARER: CardDef = CardDef {
    id: "NEUTRAL_C03",
    name: "Shieldbearer",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const YOUNG_DRAGONHAWK: CardDef = CardDef {
    id: "NEUTRAL_C04",
    name: "Young Dragonhawk",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const FEN_CREEPER: CardDef = CardDef {
    id: "NEUTRAL_C05",
    name: "Fen Creeper",
    card_type: CardType::Minion,
    cost: 5,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const PRIESTESS_OF_ELUNE: CardDef = CardDef {
    id: "NEUTRAL_C06",
    name: "Priestess of Elune",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 4,
        target: EffectTarget::FriendlyHero,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const BLOODMAGE_THALNOS: CardDef = CardDef {
    id: "LEGENDARY_012",
    name: "Bloodmage Thalnos",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
pub const SOUTHSHORE_CAPTAIN: CardDef = CardDef {
    id: "NEUTRAL_E01",
    name: "Southsea Captain",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 1,
            health: 1,
        },
        AuraTarget::OtherFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Complete Neutral — Coldlight Seer, Murloc Warleader
/// Coldlight Seer — Battlecry: give all other Murlocs +2 Health (simplified: all friendly minions)
pub const COLDLIGHT_SEER: CardDef = CardDef {
    id: "NEUTRAL_R01",
    name: "Coldlight Seer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 0,
        health: 2,
        target: EffectTarget::AllFriendlyMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Murloc Warleader — your other Murlocs have +2/+1 (simplified: your other friendly minions)
pub const MURLOC_WARLEADER: CardDef = CardDef {
    id: "NEUTRAL_E02",
    name: "Murloc Warleader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 2,
            health: 1,
        },
        AuraTarget::OtherFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// ============================================================
// Classic set — simplified cards (effects need new engine support; simplified to vanilla or partial effects)
// ============================================================

// Neutral Basic — minions not fully implementable
/// Gurubashi Berserker — gains +3 Attack whenever damaged (Enrage simplified: vanilla)
pub const GURUBASHI_BERSERKER: CardDef = vanilla!("NEUTRAL_B19", "Gurubashi Berserker", 5, 2, 8);

// Neutral Common — simplified
/// Southsea Deckhand — has Charge while you have a weapon (simplified: always has Charge)
pub const SOUTHSHORE_DECKHAND: CardDef = CardDef {
    id: "NEUTRAL_C07",
    name: "Southsea Deckhand",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Worgen Infiltrator — Stealth (simplified: vanilla)
pub const WORGEN_INFILTRATOR: CardDef = vanilla!("NEUTRAL_C08", "Worgen Infiltrator", 1, 2, 1);
/// Bloodsail Raider — Battlecry: gain Attack equal to your weapon's Attack (simplified: vanilla)
pub const BLOODSAIL_RAIDER: CardDef = vanilla!("NEUTRAL_C09", "Bloodsail Raider", 2, 2, 3);
/// Jungle Panther — Stealth (simplified: vanilla)
pub const JUNGLE_PANTHER: CardDef = vanilla!("NEUTRAL_C10", "Jungle Panther", 3, 4, 2);
/// Tauren Warrior — Taunt, Enrage: +3 Attack (simplified: Taunt only)
pub const TAUREN_WARRIOR: CardDef = CardDef {
    id: "NEUTRAL_C11",
    name: "Tauren Warrior",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Flesheating Ghoul — gains +1 Attack whenever a minion dies (simplified: vanilla)
pub const FLESHEATING_GHOUL: CardDef = vanilla!("NEUTRAL_C12", "Flesheating Ghoul", 3, 3, 3);
/// Dread Corsair — Taunt, cost reduced by your weapon (simplified: Taunt only)
pub const DREAD_CORSAIR: CardDef = CardDef {
    id: "NEUTRAL_C13",
    name: "Dread Corsair",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Venture Co. Mercenary — your minions cost (3) more (simplified: vanilla)
pub const VENTURE_CO_MERCENARY: CardDef = vanilla!("NEUTRAL_C14", "Venture Co. Mercenary", 5, 7, 6);
/// Spiteful Smith — Enrage: your weapon gains +2 Attack (simplified: vanilla)
pub const SPITEFUL_SMITH: CardDef = vanilla!("NEUTRAL_C15", "Spiteful Smith", 5, 4, 6);

// Neutral Rare — simplified
/// Angry Chicken — Enrage: +5 Attack (simplified: vanilla)
pub const ANGRY_CHICKEN: CardDef = vanilla!("NEUTRAL_R02", "Angry Chicken", 1, 1, 1);
/// Bloodsail Corsair — Battlecry: remove 1 durability from the opponent's weapon (simplified: vanilla)
pub const BLOODSAIL_CORSAIR: CardDef = vanilla!("NEUTRAL_R03", "Bloodsail Corsair", 1, 1, 2);
/// Lightwarden — gains +2 Attack whenever a character is healed (simplified: vanilla)
pub const LIGHTWARDEN: CardDef = vanilla!("NEUTRAL_R04", "Lightwarden", 1, 1, 2);
/// Murloc Tidecaller — gains +1 Attack whenever you summon a Murloc (simplified: vanilla)
pub const MURLOC_TIDECALLER: CardDef = vanilla!("NEUTRAL_R05", "Murloc Tidecaller", 1, 1, 2);
/// Secretkeeper — gains +1/+1 whenever a Secret is played (simplified: vanilla)
pub const SECRETKEEPER: CardDef = vanilla!("NEUTRAL_R06", "Secretkeeper", 1, 1, 2);
/// Ancient Watcher — cannot attack (cant_attack supported by the engine)
pub const ANCIENT_WATCHER: CardDef = CardDef {
    id: "NEUTRAL_R07",
    name: "Ancient Watcher",
    card_type: CardType::Minion,
    cost: 2,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Crazed Alchemist — Battlecry: swap a minion's Attack and Health (simplified: vanilla)
pub const CRAZED_ALCHEMIST: CardDef = vanilla!("NEUTRAL_R08", "Crazed Alchemist", 2, 2, 2);
/// Knife Juggler — deal 1 random damage after summoning a minion (simplified: vanilla)
pub const KNIFE_JUGGLER: CardDef = vanilla!("NEUTRAL_R09", "Knife Juggler", 2, 3, 2);
/// Mana Addict — +2 Attack this turn after casting a spell (simplified: vanilla)
pub const MANA_ADDICT: CardDef = vanilla!("NEUTRAL_R10", "Mana Addict", 2, 1, 3);
/// Sunfury Protector — Battlecry: give adjacent minions Taunt (simplified: vanilla)
pub const SUNFURY_PROTECTOR: CardDef = vanilla!("NEUTRAL_R11", "Sunfury Protector", 2, 2, 3);
/// Wild Pyromancer — deal 1 AOE damage after casting a spell (simplified: vanilla)
pub const WILD_PYROMANCER: CardDef = vanilla!("NEUTRAL_R12", "Wild Pyromancer", 2, 3, 2);
/// Alarm-o-Bot — swap a hand minion at start of turn (simplified: vanilla)
pub const ALARM_O_BOT: CardDef = vanilla!("NEUTRAL_R13", "Alarm-o-Bot", 3, 0, 3);
/// Arcane Golem — Charge, Battlecry gives the opponent a mana crystal (simplified: Charge only)
pub const ARCANE_GOLEM: CardDef = CardDef {
    id: "NEUTRAL_R14",
    name: "Arcane Golem",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Demolisher — deal 2 random damage at start of turn (simplified: vanilla)
pub const DEMOLISHER: CardDef = vanilla!("NEUTRAL_R15", "Demolisher", 3, 1, 4);
/// Emperor Cobra — Poison (destroy any minion damaged by it) (simplified: vanilla)
pub const EMPEROR_COBRA: CardDef = vanilla!("NEUTRAL_R16", "Emperor Cobra", 3, 2, 3);
/// Questing Adventurer — gains +1/+1 whenever you play a card (simplified: vanilla)
pub const QUESTING_ADVENTURER: CardDef = vanilla!("NEUTRAL_R17", "Questing Adventurer", 3, 2, 2);
/// Ancient Mage — Battlecry: give adjacent minions Spell Damage +1 (simplified: vanilla)
pub const ANCIENT_MAGE: CardDef = vanilla!("NEUTRAL_R18", "Ancient Mage", 4, 2, 5);
/// Twilight Drake — Battlecry: +1 Health per card in hand (simplified: vanilla)
pub const TWILIGHT_DRAKE: CardDef = vanilla!("NEUTRAL_R19", "Twilight Drake", 4, 4, 1);
/// Stampeding Kodo — Battlecry: destroy a random enemy minion with 2 or less Attack (simplified: vanilla)
pub const STAMPEDING_KODO: CardDef = vanilla!("NEUTRAL_R20", "Stampeding Kodo", 5, 3, 5);

// Neutral Epic — simplified
/// Hungry Crab — Battlecry: destroy a Murloc and gain +2/+2 (simplified: vanilla)
pub const HUNGRY_CRAB: CardDef = vanilla!("NEUTRAL_E03", "Hungry Crab", 1, 1, 2);
/// Doomsayer — destroy all minions at start of turn (simplified: vanilla)
pub const DOOMSAYER: CardDef = vanilla!("NEUTRAL_E04", "Doomsayer", 2, 0, 7);
/// Blood Knight — Battlecry: absorb all Divine Shields and gain +3/+3 (simplified: vanilla)
pub const BLOOD_KNIGHT: CardDef = vanilla!("NEUTRAL_E05", "Blood Knight", 3, 3, 3);
/// Big Game Hunter — Battlecry: destroy a minion with 7 or more Attack (simplified: vanilla)
pub const BIG_GAME_HUNTER: CardDef = vanilla!("NEUTRAL_E06", "Big Game Hunter", 5, 4, 2);
/// Young Priestess — give a random friendly minion +1 Health at end of turn (simplified: vanilla)
pub const YOUNG_PRIESTESS: CardDef = vanilla!("NEUTRAL_R21", "Young Priestess", 1, 2, 1);
/// Mana Wraith — all minions cost (1) more (simplified: vanilla)
pub const MANA_WRAITH: CardDef = vanilla!("NEUTRAL_R22", "Mana Wraith", 2, 2, 2);
/// Master Swordsmith — give a random friendly minion +1 Attack at end of turn (simplified: vanilla)
pub const MASTER_SWORDSMITH: CardDef = vanilla!("NEUTRAL_R23", "Master Swordsmith", 2, 1, 3);
/// Pint-Sized Summoner — the first minion each turn costs (1) less (simplified: vanilla)
pub const PINT_SIZED_SUMMONER: CardDef = vanilla!("NEUTRAL_R24", "Pint-Sized Summoner", 2, 2, 2);
/// SI:7 Infiltrator — Battlecry: destroy a random enemy Secret (simplified: vanilla)
pub const SI7_INFILTRATOR: CardDef = vanilla!("NEUTRAL_R25", "SI:7 Infiltrator", 4, 5, 4);
/// Eater of Secrets — Battlecry: destroy all enemy Secrets and gain +1/+1 (simplified: vanilla)
pub const EATER_OF_SECRETS: CardDef = vanilla!("NEUTRAL_R26", "Eater of Secrets", 4, 2, 4);

// ============================================================

/// Violet Teacher — whenever you cast a spell, summon a 1/1 Violet Apprentice
pub const VIOLET_APPRENTICE: CardDef = vanilla!("CLASSIC_VT", "Violet Apprentice", 1, 1, 1);

/// Arcane Devourer — whenever you cast a spell, gain +2/+2
pub const ARCANE_DEVOURER: CardDef = CardDef {
    id: "CLASSIC_AD",
    name: "Arcane Devourer",
    card_type: CardType::Minion,
    cost: 8,
    attack: 4,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: Some(CardEffect::GainStats {
        attack: 2,
        health: 2,
        target: EffectTarget::Self_,
    }),
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Faceless Manipulator — Battlecry: choose a minion and become a copy of it
pub const FACELESS_MANIPULATOR: CardDef = CardDef {
    id: "CLASSIC_FM",
    name: "Faceless Manipulator",
    card_type: CardType::Minion,
    cost: 5,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::CopyMinionStats),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// ============================================================
// Tier 1 additions — Neutral (docs/classic-cards-roadmap.md)
// ============================================================

/// Wisp — vanilla
pub const WISP: CardDef = vanilla!("NEUTRAL_T01", "Wisp", 0, 1, 1);
/// Elven Archer — Battlecry: deal 1 damage
pub const ELVEN_ARCHER: CardDef = CardDef {
    id: "NEUTRAL_T02",
    name: "Elven Archer",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Goldshire Footman — Taunt
pub const GOLDSHIRE_FOOTMAN: CardDef = CardDef {
    id: "NEUTRAL_T03",
    name: "Goldshire Footman",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Novice Engineer — Battlecry: draw a card
pub const NOVICE_ENGINEER: CardDef = CardDef {
    id: "NEUTRAL_T04",
    name: "Novice Engineer",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// River Crocolisk — vanilla
pub const RIVER_CROCOLISK: CardDef = vanilla!("NEUTRAL_T05", "River Crocolisk", 2, 2, 3);
/// Raid Leader — your other minions have +1 Attack
pub const RAID_LEADER: CardDef = CardDef {
    id: "NEUTRAL_T06",
    name: "Raid Leader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::OtherFriendlyMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Shattered Sun Cleric — Battlecry: give a friendly minion +1/+1
pub const SHATTERED_SUN_CLERIC: CardDef = CardDef {
    id: "NEUTRAL_T07",
    name: "Shattered Sun Cleric",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Chillwind Yeti — vanilla
pub const CHILLWIND_YETI: CardDef = vanilla!("NEUTRAL_T08", "Chillwind Yeti", 4, 4, 5);
/// Boulderfist Ogre — vanilla
pub const BOULDERFIST_OGRE: CardDef = vanilla!("NEUTRAL_T09", "Boulderfist Ogre", 6, 6, 7);
/// Stormwind Champion — your other minions have +1/+1
pub const STORMWIND_CHAMPION: CardDef = CardDef {
    id: "NEUTRAL_T10",
    name: "Stormwind Champion",
    card_type: CardType::Minion,
    cost: 7,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 1,
            health: 1,
        },
        AuraTarget::OtherFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// War Golem — vanilla
pub const WAR_GOLEM: CardDef = vanilla!("NEUTRAL_T11", "War Golem", 7, 7, 7);
/// Dire Wolf Alpha — adjacent minions have +1 Attack
pub const DIRE_WOLF_ALPHA: CardDef = CardDef {
    id: "NEUTRAL_T12",
    name: "Dire Wolf Alpha",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Loot Hoarder — Deathrattle: draw a card
pub const LOOT_HOARDER: CardDef = CardDef {
    id: "NEUTRAL_T13",
    name: "Loot Hoarder",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
/// Stranglethorn Tiger — Stealth (simplified: vanilla; engine does not implement Stealth yet)
pub const STRANGLETHORN_TIGER: CardDef = vanilla!("NEUTRAL_T14", "Stranglethorn Tiger", 5, 5, 5);
/// Ravenholdt Assassin — Stealth (simplified: vanilla; engine does not implement Stealth yet)
pub const RAVENHOLDT_ASSASSIN: CardDef = vanilla!("NEUTRAL_T15", "Ravenholdt Assassin", 7, 7, 5);

// Tier 2 additions — King Mukla
// ============================================================

/// King Mukla — Battlecry: give your opponent 2 Bananas.
pub const KING_MUKLA: CardDef = CardDef {
    id: "NEUTRAL_T16",
    name: "King Mukla",
    card_type: CardType::Minion,
    cost: 3,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::GiveCardToOpponent {
        card_id: "NEUTRAL_T16t",
        count: 2,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Banana (King Mukla token) — give a minion +1/+1.
pub const BANANA: CardDef = CardDef {
    id: "NEUTRAL_T16t",
    name: "Banana",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 1,
        health: 1,
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// Tier 2 additions — Tinkmaster Overspark
// ============================================================

/// Tinkmaster Overspark — Battlecry: transform a minion into a random 5/5 Devilsaur or 1/1 Squirrel.
pub const TINKMASTER_OVERSPARK: CardDef = CardDef {
    id: "NEUTRAL_T17",
    name: "Tinkmaster Overspark",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::TransformToRandom {
        card_a: "NEUTRAL_T17a",
        card_b: "NEUTRAL_T17b",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Devilsaur (Tinkmaster token) — 5/5
pub const DEVILSAUR: CardDef = vanilla!("NEUTRAL_T17a", "Devilsaur", 5, 5, 5);

/// Squirrel (Tinkmaster token) — 1/1
pub const SQUIRREL: CardDef = vanilla!("NEUTRAL_T17b", "Squirrel", 1, 1, 1);

// Tier 3 additions — random pools
// ============================================================

/// Brightwing — Battlecry: add a random Legendary minion to your hand.
pub const BRIGHTWING: CardDef = CardDef {
    id: "NEUTRAL_T18",
    name: "Brightwing",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Legendary,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Nozdormu — 8/8 (turn timer is meaningless in a simulator; implemented as a plain minion).
pub const NOZDORMU: CardDef = vanilla!("NEUTRAL_T19", "Nozdormu", 9, 8, 8);

/// Xavius — at the end of your turn, add a random Shadow spell to your hand.
pub const XAVIUS: CardDef = CardDef {
    id: "NEUTRAL_T20",
    name: "Xavius",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::ShadowSpell,
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Ysera — at the end of your turn, add a Dream card to your hand.
pub const YSERA: CardDef = CardDef {
    id: "NEUTRAL_T21",
    name: "Ysera",
    card_type: CardType::Minion,
    cost: 9,
    attack: 4,
    health: 12,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Dream,
    }),
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Emerald Drake (Dream card) — 4/7
pub const EMERALD_DRAKE: CardDef = vanilla!("NEUTRAL_T21a", "Emerald Drake", 4, 4, 7);

/// Laughing Sister (Dream card) — 3/5
pub const LAUGHING_SISTER: CardDef = vanilla!("NEUTRAL_T21b", "Laughing Sister", 3, 3, 5);

/// Dream (Dream card) — return a minion to its owner's hand.
pub const DREAM: CardDef = CardDef {
    id: "NEUTRAL_T21c",
    name: "Dream",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ReturnToHand {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Nightmare (Dream card) — give a minion +5/+5.
pub const NIGHTMARE: CardDef = CardDef {
    id: "NEUTRAL_T21d",
    name: "Nightmare",
    card_type: CardType::Spell,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 5,
        health: 5,
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Ysera Awakens (Dream card) — deal 5 damage to all characters (simplified: includes Ysera herself).
pub const YSERA_AWAKENS: CardDef = CardDef {
    id: "NEUTRAL_T21e",
    name: "Ysera Awakens",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 5,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// Barrens Stablehand — Battlecry: summon a random Beast.
pub const BARRENS_STABLEHAND: CardDef = CardDef {
    id: "NEUTRAL_T22",
    name: "Barrens Stablehand",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonRandomMinion {
        pool: RandomPool::Beast,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
