//! 怀旧系列 — 术士 (Warlock)。
#![allow(missing_docs)]

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::effect::{CardEffect, EffectTarget};

// 怀旧系列 — 术士 (Warlock)
// ============================================================

pub const SOULFIRE: CardDef = CardDef {
    id: "WARLOCK_001",
    name: "Soulfire",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 4, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const FLAME_IMP: CardDef = CardDef {
    id: "WARLOCK_002",
    name: "Flame Imp",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const MORTAL_COIL: CardDef = CardDef {
    id: "WARLOCK_003",
    name: "Mortal Coil",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 1, target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const VOIDWALKER: CardDef = CardDef {
    id: "WARLOCK_004",
    name: "Voidwalker",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const HELLFIRE: CardDef = CardDef {
    id: "WARLOCK_005",
    name: "Hellfire",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 3, target: EffectTarget::AllCharacters }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const DRAIN_LIFE: CardDef = CardDef {
    id: "WARLOCK_006",
    name: "Drain Life",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 2, target: EffectTarget::AnyEnemy }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const DOOMGUARD: CardDef = CardDef {
    id: "WARLOCK_007",
    name: "Doomguard",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};


pub const SHADOW_BOLT: CardDef = CardDef {
    id: "WARLOCK_008",
    name: "Shadow Bolt",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage { amount: 4, target: EffectTarget::AnyEnemyMinion }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const TWISTING_NETHER: CardDef = CardDef {
    id: "WARLOCK_009",
    name: "Twisting Nether",
    card_type: CardType::Spell,
    cost: 8,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion { target: EffectTarget::AllMinions }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

pub const LORD_JARAXXUS: CardDef = CardDef {
    id: "WARLOCK_010",
    name: "Lord Jaraxxus",
    card_type: CardType::Minion,
    cost: 9,
    attack: 3,
    health: 15,
    durability: 0,
    battlecry: Some(CardEffect::EquipWeapon {
        card_id: "WARLOCK_010t",
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};
pub const BLOOD_FURY: CardDef = CardDef {
    id: "WARLOCK_010t",
    name: "Blood Fury",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 3,
    health: 0,
    durability: 8,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

// 术士补全
pub const DREAD_INFERNAL: CardDef = CardDef {
    id: "WARLOCK_011",
    name: "Dread Infernal",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};
pub const PIT_LORD: CardDef = CardDef {
    id: "WARLOCK_012",
    name: "Pit Lord",
    card_type: CardType::Minion,
    cost: 4,
    attack: 5,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 5,
        target: EffectTarget::Self_,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};


/// 恶魔猎犬 — 战吼：随机丢弃一张手牌
pub const FELSTALKER: CardDef = CardDef {
    id: "WARLOCK_016",
    name: "Felstalker",
    card_type: CardType::Minion,
    cost: 2,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DiscardRandomCard),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 灵魂虹吸 — 消灭一个随从，为你的英雄恢复3点生命值
pub const SIPHON_SOUL: CardDef = CardDef {
    id: "WARLOCK_017",
    name: "Siphon Soul",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAndHeal {
        target: EffectTarget::AnyEnemyMinion,
        heal: 3,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 暗影烈焰 — 消灭一个友方随从，对所有敌方随从造成等同于其攻击力的伤害
pub const SHADOWFLAME: CardDef = CardDef {
    id: "WARLOCK_018",
    name: "Shadowflame",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAndAOE {
        target: EffectTarget::AllEnemyMinions,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 恶魔卫士 — 战吼：摧毁一颗你的法力水晶
pub const FELGUARD: CardDef = CardDef {
    id: "WARLOCK_019",
    name: "Felguard",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DestroyManaCrystal),
    deathrattle: None,
    taunt: true,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 感知恶魔 — 从你的牌库中抽两张恶魔牌（简化：抽1张牌）
pub const SENSE_DEMONS: CardDef = CardDef {
    id: "WARLOCK_020",
    name: "Sense Demons",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 2 }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 恶魔之火 — 对一个随从造成2点伤害；如果是友方恶魔，改为获得+2/+2（简化：造成2点伤害）
pub const DEMONFIRE: CardDef = CardDef {
    id: "WARLOCK_021",
    name: "Demonfire",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 2,
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};

/// 虚空恐魔 — 战吼：消灭相邻的随从并获得其攻击力和生命值
pub const VOID_TERROR: CardDef = CardDef {
    id: "WARLOCK_022",
    name: "Void Terror",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAdjacent { gain_stats: true }),
    deathrattle: None,
    taunt: false,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    spell_effect: None,
    end_turn_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
};
