//! Core Set W1 cards (core-set-roadmap W1) — attack-pipeline primitives.
//!
//! RUSH / LIFESTEAL / REBORN are components applied by `apply_card_keywords`
//! (the `CardDef` struct stays untouched); this file holds the card
//! definitions, their scripted effects and the Lynx token. Chinese names
//! follow the `classic-cards-zh.md` convention once the cards land.
//!
//! Card data: `cards/cards.json` (CORE_* IDs); card texts verified against
//! the official Core Set versions (2026-08-08).

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;

/// CORE_BT_156 Imprisoned Vilefiend — 2/3/5 Demon, Rush (the Core version
/// dropped the original's Dormant-for-2-turns).
pub const IMPRISONED_VILEFIEND: CardDef = CardDef {
    id: "CORE_BT_156",
    name: "Imprisoned Vilefiend",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DRG_079 Evasive Wyrm — 6/5/4 Dragon, Divine Shield, Elusive, Rush.
pub const EVASIVE_WYRM: CardDef = CardDef {
    id: "CORE_DRG_079",
    name: "Evasive Wyrm",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: true,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_657 Underking — 7/6/6 Undead, Rush. Battlecry and Deathrattle:
/// gain 6 Armor.
pub const UNDERKING: CardDef = CardDef {
    id: "CORE_RLK_657",
    name: "Underking",
    card_type: CardType::Minion,
    cost: 7,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::GainArmor {
        amount: 6,
        target: EffectTarget::FriendlyHero,
    }),
    deathrattle: Some(CardEffect::GainArmor {
        amount: 6,
        target: EffectTarget::FriendlyHero,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TRL_900 Halazzi, the Lynx — 4/4/2 Beast, Rush. Battlecry: fill your
/// hand with 1/1 Lynxes that have Rush.
pub const HALAZZI_THE_LYNX: CardDef = CardDef {
    id: "CORE_TRL_900",
    name: "Halazzi, the Lynx",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::FillHandWithMinion {
        card_id: "CORE_TRL_900t",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TRL_900t Lynx — 1/1 Beast with Rush (Halazzi's battlecry token;
/// id ends in 't', so the RL pool filters it out).
pub const LYNX: CardDef = CardDef {
    id: "CORE_TRL_900t",
    name: "Lynx",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_WC_701 Felrattler — 3/3/2 Beast, Rush. Deathrattle: deal 1 damage
/// to all enemy minions.
pub const FELRATTLER: CardDef = CardDef {
    id: "CORE_WC_701",
    name: "Felrattler",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AllEnemyMinions,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_921 Aldrachi Warblades — 3-cost 2/2 weapon, Lifesteal (weapon
/// attacks heal the hero).
pub const ALDRACHI_WARBLADES: CardDef = CardDef {
    id: "CORE_BT_921",
    name: "Aldrachi Warblades",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_558 Swamp Leech — 1/2/1 Beast, Lifesteal.
pub const SWAMP_LEECH: CardDef = CardDef {
    id: "CORE_GIL_558",
    name: "Swamp Leech",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ICC_055 Drain Soul — 2-cost Priest spell, Lifesteal: deal 3 damage
/// to a minion.
pub const DRAIN_SOUL: CardDef = CardDef {
    id: "CORE_ICC_055",
    name: "Drain Soul",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyMinion,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ICC_214 Obsidian Statue — 9/4/8, Taunt, Lifesteal. Deathrattle:
/// summon a 4/8 Obsidian Statue (a fresh copy with its own Deathrattle).
pub const OBSIDIAN_STATUE: CardDef = CardDef {
    id: "CORE_ICC_214",
    name: "Obsidian Statue",
    card_type: CardType::Minion,
    cost: 9,
    attack: 4,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "CORE_ICC_214",
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_442 Void Shard — 4-cost Priest spell, Lifesteal: deal 4 damage
/// to a minion.
pub const VOID_SHARD: CardDef = CardDef {
    id: "CORE_SW_442",
    name: "Void Shard",
    card_type: CardType::Spell,
    cost: 4,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::DealDamage {
        amount: 4,
        target: EffectTarget::AnyEnemyMinion,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TTN_866 Mythical Terror — 7/4/10 Demon + Beast, Lifesteal. At the
/// end of your turn, force all enemy minions to attack this.
pub const MYTHICAL_TERROR: CardDef = CardDef {
    id: "CORE_TTN_866",
    name: "Mythical Terror",
    card_type: CardType::Minion,
    cost: 7,
    attack: 4,
    health: 10,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::ForceEnemyMinionsAttackThis),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_745 Malignant Horror — 4/2/4 Undead, Reborn. At the end of your
/// turn, spend 4 Corpses to summon a copy of this minion.
pub const MALIGNANT_HORROR: CardDef = CardDef {
    id: "CORE_RLK_745",
    name: "Malignant Horror",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::SpendCorpsesSummonCopy { cost: 4 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_723 Murmy — 1/1/1 Murloc, Reborn.
pub const MURMY: CardDef = CardDef {
    id: "CORE_ULD_723",
    name: "Murmy",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
