//! Core Set W4b cards (core-set-roadmap W4b) — the second battlecry batch.
//! Effects verified against the official Core Set data (2026-08-08).
//! Known simplifications (for the fidelity ledger): Siamat gains Rush (the Taunt half of the choice is dropped)
//! (no choice system — the 2-of-4 selection is approximated), Steamcleaner
//! has no card-origin tracking (no-op), Avatar of Hearthstone adds five
//! random cards to hand instead of opening a pack.

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;
use crate::core::effect::RandomPool;

/// CORE_CS2_042 Fire Elemental — 6费 Minion
pub const CORE_FIRE_ELEMENTAL: CardDef = CardDef {
    id: "CORE_CS2_042",
    name: "Fire Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyCharacter,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CS2_188 Abusive Sergeant — 1费 Minion
pub const CORE_ABUSIVE_SERGEANT: CardDef = CardDef {
    id: "CORE_CS2_188",
    name: "Abusive Sergeant",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::GainStatsThisTurn {
        attack: 2,
        health: 0,
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CS2_189 Elven Archer — 1费 Minion
pub const CORE_ELVEN_ARCHER: CardDef = CardDef {
    id: "CORE_CS2_189",
    name: "Elven Archer",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyCharacter,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_011 Voodoo Doctor — 1费 Minion
pub const CORE_VOODOO_DOCTOR: CardDef = CardDef {
    id: "CORE_EX1_011",
    name: "Voodoo Doctor",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealth {
        amount: 2,
        target: EffectTarget::AnyCharacter,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_014 King Mukla — 3费 Minion
pub const CORE_KING_MUKLA: CardDef = CardDef {
    id: "CORE_EX1_014",
    name: "King Mukla",
    card_type: CardType::Minion,
    cost: 3,
    attack: 5,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::GiveCardToOpponent {
        card_id: "NEUTRAL_T16t",
        count: 2,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_043 Twilight Drake — 4费 Minion
pub const CORE_TWILIGHT_DRAKE: CardDef = CardDef {
    id: "CORE_EX1_043",
    name: "Twilight Drake",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::GainStatsPerHandCard {
        attack: 0,
        health_per_card: 1,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_058 Sunfury Protector — 2费 Minion
pub const CORE_SUNFURY_PROTECTOR: CardDef = CardDef {
    id: "CORE_EX1_058",
    name: "Sunfury Protector",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GrantAdjacentTaunt),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_059 Crazed Alchemist — 2费 Minion
pub const CORE_CRAZED_ALCHEMIST: CardDef = CardDef {
    id: "CORE_EX1_059",
    name: "Crazed Alchemist",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::SwapAttackAndHealth {
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_082 Mad Bomber — 2费 Minion
pub const CORE_MAD_BOMBER: CardDef = CardDef {
    id: "CORE_EX1_082",
    name: "Mad Bomber",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DealDamageRandomly {
        amount: 1,
        count: 3,
        target: EffectTarget::AllCharacters,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_103 Coldlight Seer — 3费 Minion
pub const CORE_COLDLIGHT_SEER: CardDef = CardDef {
    id: "CORE_EX1_103",
    name: "Coldlight Seer",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 0,
        health: 2,
        target: EffectTarget::AllOtherFriendlyRace(crate::core::component::Race::Murloc),
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_189 Brightwing — 2费 Minion
pub const CORE_BRIGHTWING: CardDef = CardDef {
    id: "CORE_EX1_189",
    name: "Brightwing",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Legendary,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_193 Psychic Conjurer — 1费 Minion
pub const CORE_PSYCHIC_CONJURER: CardDef = CardDef {
    id: "CORE_EX1_193",
    name: "Psychic Conjurer",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::CopyRandomEnemyDeckCards { count: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_198 Natalie Seline — 7费 Minion
pub const CORE_NATALIE_SELINE: CardDef = CardDef {
    id: "CORE_EX1_198",
    name: "Natalie Seline",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::DestroyAndGainHealth),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_310 Doomguard — 5费 Minion
pub const CORE_DOOMGUARD: CardDef = CardDef {
    id: "CORE_EX1_310",
    name: "Doomguard",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 7,
    durability: 0,
    battlecry: Some(CardEffect::DiscardTwoRandomCards),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_319 Flame Imp — 1费 Minion
pub const CORE_FLAME_IMP: CardDef = CardDef {
    id: "CORE_EX1_319",
    name: "Flame Imp",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DamageSelfHero { damage: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_362 Argent Protector — 2费 Minion
pub const CORE_ARGENT_PROTECTOR: CardDef = CardDef {
    id: "CORE_EX1_362",
    name: "Argent Protector",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::GrantDivineShield {
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_506 Murloc Tidehunter — 2费 Minion
pub const CORE_MURLOC_TIDEHUNTER: CardDef = CardDef {
    id: "CORE_EX1_506",
    name: "Murloc Tidehunter",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "CORE_EX1_506a",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BOT_256 Astromancer — 7费 Minion
pub const CORE_ASTROMANCER: CardDef = CardDef {
    id: "CORE_BOT_256",
    name: "Astromancer",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::SummonRandomMinionCostEqHandSize),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CATA_001 Tichondrius — 9费 Minion
pub const CORE_TICHONDRIUS: CardDef = CardDef {
    id: "CORE_CATA_001",
    name: "Tichondrius",
    card_type: CardType::Minion,
    cost: 9,
    attack: 9,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::NextDemonDiscount { amount: 999 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CATA_002 Calia Menethil — 6费 Minion
pub const CORE_CALIA_MENETHIL: CardDef = CardDef {
    id: "CORE_CATA_002",
    name: "Calia Menethil",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::ResurrectHighestCostFallen),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CATA_006 Ulfar — 6费 Minion
pub const CORE_ULFAR: CardDef = CardDef {
    id: "CORE_CATA_006",
    name: "Ulfar",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GrantDeathrattleSummonOwnCost),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DRG_024 Sky Raider — 1费 Minion
pub const CORE_SKY_RAIDER: CardDef = CardDef {
    id: "CORE_DRG_024",
    name: "Sky Raider",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomPirateToHand),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Pirate),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DRG_403 Blowtorch Saboteur — 3费 Minion
pub const CORE_BLOWTORCH_SABOTEUR: CardDef = CardDef {
    id: "CORE_DRG_403",
    name: "Blowtorch Saboteur",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::NextEnemyHeroPowerCostMore { amount: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_OG_149 Ravaging Ghoul — 3费 Minion
pub const CORE_RAVAGING_GHOUL: CardDef = CardDef {
    id: "CORE_OG_149",
    name: "Ravaging Ghoul",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DamageAllOtherMinions { damage: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_REV_308 Maze Guide — 2费 Minion
pub const CORE_MAZE_GUIDE: CardDef = CardDef {
    id: "CORE_REV_308",
    name: "Maze Guide",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::SummonRandomMinionOfCost { cost: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_REV_946 Steamcleaner — 5费 Minion
pub const CORE_STEAMCLEANER: CardDef = CardDef {
    id: "CORE_REV_946",
    name: "Steamcleaner",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Mechanical),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SCH_181 Archwitch Willow — 8费 Minion
pub const CORE_ARCHWITCH_WILLOW: CardDef = CardDef {
    id: "CORE_SCH_181",
    name: "Archwitch Willow",
    card_type: CardType::Minion,
    cost: 8,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::SummonRandomDemonFromHandOrDeck),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SCH_713 Cult Neophyte — 2费 Minion
pub const CORE_CULT_NEOPHYTE: CardDef = CardDef {
    id: "CORE_SCH_713",
    name: "Cult Neophyte",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::NextEnemySpellsCostMore { amount: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TRL_111 Headhunter's Hatchet — 2费 Weapon
pub const CORE_HEADHUNTERS_HATCHET: CardDef = CardDef {
    id: "CORE_TRL_111",
    name: "Headhunter's Hatchet",
    card_type: CardType::Weapon,
    cost: 2,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: Some(CardEffect::BuffWeaponDurabilityIfBeast { amount: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TRL_240 Savage Striker — 2费 Minion
pub const CORE_SAVAGE_STRIKER: CardDef = CardDef {
    id: "CORE_TRL_240",
    name: "Savage Striker",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DealHeroAttackDamage {
        target: EffectTarget::AnyEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_TRL_345 Krag'wa, the Frog — 6费 Minion
pub const CORE_KRAGWA_THE_FROG: CardDef = CardDef {
    id: "CORE_TRL_345",
    name: "Krag'wa, the Frog",
    card_type: CardType::Minion,
    cost: 6,
    attack: 4,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::ReturnLastTurnSpells),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_165 Riftcleaver — 6费 Minion
pub const CORE_RIFTCLEAVER: CardDef = CardDef {
    id: "CORE_ULD_165",
    name: "Riftcleaver",
    card_type: CardType::Minion,
    cost: 6,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinionAndSelfDamage),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_178 Siamat — 7费 Minion
pub const CORE_SIAMAT: CardDef = CardDef {
    id: "CORE_ULD_178",
    name: "Siamat",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_191 Beaming Sidekick — 1费 Minion
pub const CORE_BEAMING_SIDEKICK: CardDef = CardDef {
    id: "CORE_ULD_191",
    name: "Beaming Sidekick",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::GainStats {
        attack: 0,
        health: 2,
        target: EffectTarget::FriendlyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_271 Injured Tol'vir — 2费 Minion
pub const CORE_INJURED_TOLVIR: CardDef = CardDef {
    id: "CORE_ULD_271",
    name: "Injured Tol'vir",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DamageSelfMinion { damage: 3 }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_WON_096 Dark Peddler — 2费 Minion
pub const CORE_DARK_PEDDLER: CardDef = CardDef {
    id: "CORE_WON_096",
    name: "Dark Peddler",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomOneCostCard),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_WON_141 Menagerie Mug — 3费 Minion
pub const CORE_MENAGERIE_MUG: CardDef = CardDef {
    id: "CORE_WON_141",
    name: "Menagerie Mug",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::BuffThreeDifferentRaces {
        attack: 1,
        health: 1,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_WON_145 Avatar of Hearthstone — 9费 Minion
pub const CORE_AVATAR_OF_HEARTHSTONE: CardDef = CardDef {
    id: "CORE_WON_145",
    name: "Avatar of Hearthstone",
    card_type: CardType::Minion,
    cost: 9,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::AddFiveRandomCards),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
