//! Core Set W8 cards (core-set-roadmap W8) — special types: the deferred
//! HERO (Lord Jaraxxus — hero replacement), the LOCATION (Sanguine Depths
//! — CardType::Location), the three ENCHANTMENT tokens, and the Imp token.
//! Effects verified against the official Core Set data (2026-08-08).
//! Registered simplification: Lord Jaraxxus replaces the hero with a
//! 15-health Jaraxxus hero and equips Blood Fury 3/8, but the "can't heal
//! above 15" cap is implicit in the new hero's base health (the old hero's
//! accumulated damage is dropped, not carried over). The location effect
//! lives in the battlecry slot (secret convention) and resolves on
//! activation.

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;

/// CORE_EX1_323 Lord Jaraxxus — 8费 Hero (replaces the hero, equips
/// Blood Fury, sets the INFERNO! hero power)
pub const CORE_LORD_JARAXXUS: CardDef = CardDef {
    id: "CORE_EX1_323",
    name: "Lord Jaraxxus",
    card_type: CardType::Hero,
    cost: 8,
    attack: 0,
    health: 15,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_REV_990 Sanguine Depths — 1费 Location (3 durability; activate:
/// Deal 1 damage to a minion and give it +2 Attack)
pub const CORE_SANGUINE_DEPTHS: CardDef = CardDef {
    id: "CORE_REV_990",
    name: "Sanguine Depths",
    card_type: CardType::Location,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 3,
    battlecry: Some(CardEffect::DamageAndGainAttack {
        damage: 1,
        attack_bonus: 2,
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CATA_006e Thornspeakers' Spirit — 0费 Enchantment (Ulfar's spirit
/// buff; the engine models buffs as Enchantment components — data only)
pub const CORE_THORNSPEAKERS_SPIRIT: CardDef = CardDef {
    id: "CORE_CATA_006e",
    name: "Thornspeakers' Spirit",
    card_type: CardType::Enchantment,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CS2_039e Windfury — 0费 Enchantment (the Windfury buff token;
/// the engine models buffs as components — data only)
pub const CORE_WINDFURY_ENCHANTMENT: CardDef = CardDef {
    id: "CORE_CS2_039e",
    name: "Windfury",
    card_type: CardType::Enchantment,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EDR_002e Deathly Poison — 0费 Enchantment (Poison Breath's
/// Poisonous buff token — data only)
pub const CORE_DEATHLY_POISON: CardDef = CardDef {
    id: "CORE_EDR_002e",
    name: "Deathly Poison",
    card_type: CardType::Enchantment,
    cost: 0,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_191t Imp — 1费 Minion 1/1 Demon (token)
pub const CORE_IMP: CardDef = CardDef {
    id: "CORE_GIL_191t",
    name: "Imp",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_323t Infernal — 6费 Minion 6/6 Demon (INFERNO! hero power token)
pub const CORE_INFERNAL: CardDef = CardDef {
    id: "CORE_EX1_323t",
    name: "Infernal",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
