//! Core Set W4a cards (core-set-roadmap W4a) — the battlecry batch.
//! Effects verified against the official Core Set data (2026-08-08).
//! Known simplifications (for the fidelity ledger): Discover cards use
//! random generation (no Discover system), Raptor Herald drops the 2026
//! Rewind/Kindred keywords, Falric's corpse-doubling aura is not modelled
//! (battlecry only), conditional discovers (Netherspite Historian,
//! Gorillabot A-3, Necrotic Mortician, Hematurge) are unconditional random
//! generation, Crystalsmith Cultist's Shadow-spell condition is modelled
//! as the healed-this-turn check (same shape).

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;
use crate::core::effect::RandomPool;

/// CORE_BAR_313 Priest of An'she — 5费 Minion
pub const CORE_PRIEST_OF_ANSHE: CardDef = CardDef {
    id: "CORE_BAR_313",
    name: "Priest of An'she",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::GainStatsIfHealedThisTurn {
        attack: 3,
        health: 3,
    }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_120 Warmaul Challenger — 3费 Minion
pub const CORE_WARMAUL_CHALLENGER: CardDef = CardDef {
    id: "CORE_BT_120",
    name: "Warmaul Challenger",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 10,
    durability: 0,
    battlecry: Some(CardEffect::BattleToTheDeath),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_321 Netherwalker — 2费 Minion
pub const CORE_NETHERWALKER: CardDef = CardDef {
    id: "CORE_BT_321",
    name: "Netherwalker",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Demon,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_416 Raging Felscreamer — 4费 Minion
pub const CORE_RAGING_FELSCREAMER: CardDef = CardDef {
    id: "CORE_BT_416",
    name: "Raging Felscreamer",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::NextDemonDiscount { amount: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CFM_753 Grimestreet Outfitter — 2费 Minion
pub const CORE_GRIMESTREET_OUTFITTER: CardDef = CardDef {
    id: "CORE_CFM_753",
    name: "Grimestreet Outfitter",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::BuffHandMinions {
        attack: 1,
        health: 1,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CFM_790 Dirty Rat — 2费 Minion
pub const CORE_DIRTY_RAT: CardDef = CardDef {
    id: "CORE_CFM_790",
    name: "Dirty Rat",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::SummonRandomEnemyHandMinion),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DMF_067 Prize Vendor — 2费 Minion
pub const CORE_PRIZE_VENDOR: CardDef = CardDef {
    id: "CORE_DMF_067",
    name: "Prize Vendor",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DrawForBoth),
    deathrattle: Some(CardEffect::DrawForBoth),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DMF_511 Foxy Fraud — 2费 Minion
pub const CORE_FOXY_FRAUD: CardDef = CardDef {
    id: "CORE_DMF_511",
    name: "Foxy Fraud",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::NextComboDiscount { amount: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EDR_001 Babbling Bookcase — 3费 Minion
pub const CORE_BABBLING_BOOKCASE: CardDef = CardDef {
    id: "CORE_EDR_001",
    name: "Babbling Bookcase",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomMageSpells { count: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EDR_003 Falric — 3费 Minion
pub const CORE_FALRIC: CardDef = CardDef {
    id: "CORE_EDR_003",
    name: "Falric",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EDR_004 Raptor Herald — 3费 Minion
pub const CORE_RAPTOR_HERALD: CardDef = CardDef {
    id: "CORE_EDR_004",
    name: "Raptor Herald",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Beast,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_531 Witch's Apprentice — 0费 Minion
pub const CORE_WITCHS_APPRENTICE: CardDef = CardDef {
    id: "CORE_GIL_531",
    name: "Witch's Apprentice",
    card_type: CardType::Minion,
    cost: 0,
    attack: 0,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomShamanSpell),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_622 Lifedrinker — 4费 Minion
pub const CORE_LIFEDRINKER: CardDef = CardDef {
    id: "CORE_GIL_622",
    name: "Lifedrinker",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DamageEnemyHeroAndHealSelf { amount: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_623 Witchwood Grizzly — 5费 Minion
pub const CORE_WITCHWOOD_GRIZZLY: CardDef = CardDef {
    id: "CORE_GIL_623",
    name: "Witchwood Grizzly",
    card_type: CardType::Minion,
    cost: 5,
    attack: 3,
    health: 12,
    durability: 0,
    battlecry: Some(CardEffect::LoseHealthPerOpponentHandCard),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GVG_059 Coghammer — 3费 Weapon
pub const CORE_COGHAMMER: CardDef = CardDef {
    id: "CORE_GVG_059",
    name: "Coghammer",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 2,
    health: 0,
    durability: 3,
    battlecry: Some(CardEffect::GrantRandomFriendlyDivineShieldTaunt),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ICC_407 Gnomeferatu — 2费 Minion
pub const CORE_GNOMEFERATU: CardDef = CardDef {
    id: "CORE_ICC_407",
    name: "Gnomeferatu",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::RemoveTopEnemyDeckCard),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_KAR_057 Ivory Knight — 4费 Minion
pub const CORE_IVORY_KNIGHT: CardDef = CardDef {
    id: "CORE_KAR_057",
    name: "Ivory Knight",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DiscoverSpellAndHealCost),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_KAR_061 The Curator — 5费 Minion
pub const CORE_THE_CURATOR: CardDef = CardDef {
    id: "CORE_KAR_061",
    name: "The Curator",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DrawBeastDragonMurloc),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Mechanical),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_KAR_062 Netherspite Historian — 2费 Minion
pub const CORE_NETHERSPITE_HISTORIAN: CardDef = CardDef {
    id: "CORE_KAR_062",
    name: "Netherspite Historian",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Dragon,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_KAR_069 Swashburglar — 1费 Minion
pub const CORE_SWASHBURGLAR: CardDef = CardDef {
    id: "CORE_KAR_069",
    name: "Swashburglar",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomOtherClassCard),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Pirate),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOE_039 Gorillabot A-3 — 3费 Minion
pub const CORE_GORILLABOT_A_3: CardDef = CardDef {
    id: "CORE_LOE_039",
    name: "Gorillabot A-3",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Mechanical,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Mechanical),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOOT_013 Vulgar Homunculus — 2费 Minion
pub const CORE_VULGAR_HOMUNCULUS: CardDef = CardDef {
    id: "CORE_LOOT_013",
    name: "Vulgar Homunculus",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DamageSelfHero { damage: 2 }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_NEW1_018 Bloodsail Raider — 2费 Minion
pub const CORE_BLOODSAIL_RAIDER: CardDef = CardDef {
    id: "CORE_NEW1_018",
    name: "Bloodsail Raider",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::GainAttackEqualToWeapon),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Pirate),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ONY_022 Battle Vicar — 2费 Minion
pub const CORE_BATTLE_VICAR: CardDef = CardDef {
    id: "CORE_ONY_022",
    name: "Battle Vicar",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Spell,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Draenei),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_062 Nerubian Swarmguard — 4费 Minion
pub const CORE_NERUBIAN_SWARMGUARD: CardDef = CardDef {
    id: "CORE_RLK_062",
    name: "Nerubian Swarmguard",
    card_type: CardType::Minion,
    cost: 4,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SummonTwoCopiesOfSelf),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_066 Hematurge — 2费 Minion
pub const CORE_HEMATURGE: CardDef = CardDef {
    id: "CORE_RLK_066",
    name: "Hematurge",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Spell,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_116 Necrotic Mortician — 2费 Minion
pub const CORE_NECROTIC_MORTICIAN: CardDef = CardDef {
    id: "CORE_RLK_116",
    name: "Necrotic Mortician",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Spell,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_505 Marrow Manipulator — 6费 Minion
pub const CORE_MARROW_MANIPULATOR: CardDef = CardDef {
    id: "CORE_RLK_505",
    name: "Marrow Manipulator",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::SpendCorpsesDamageRandom { max: 5, damage: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_506 Boneguard Commander — 8费 Minion
pub const CORE_BONEGUARD_COMMANDER: CardDef = CardDef {
    id: "CORE_RLK_506",
    name: "Boneguard Commander",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::SpendCorpsesSummonFootmen { max: 6 }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_706 Alexandros Mograine — 7费 Minion
pub const CORE_ALEXANDROS_MOGRAINE: CardDef = CardDef {
    id: "CORE_RLK_706",
    name: "Alexandros Mograine",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 7,
    durability: 0,
    battlecry: Some(CardEffect::OngoingEndTurnDamage { damage: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_814 Crystalsmith Cultist — 1费 Minion
pub const CORE_CRYSTALSMITH_CULTIST: CardDef = CardDef {
    id: "CORE_RLK_814",
    name: "Crystalsmith Cultist",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::GainStatsIfHealedThisTurn {
        attack: 1,
        health: 1,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_084 Fire Plume Phoenix — 4费 Minion
pub const CORE_FIRE_PLUME_PHOENIX: CardDef = CardDef {
    id: "CORE_UNG_084",
    name: "Fire Plume Phoenix",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AnyCharacter,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_205 Glacial Shard — 1费 Minion
pub const CORE_GLACIAL_SHARD: CardDef = CardDef {
    id: "CORE_UNG_205",
    name: "Glacial Shard",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::FreezeCharacter {
        target: EffectTarget::AnyEnemy,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_809 Fire Fly — 1费 Minion
pub const CORE_FIRE_FLY: CardDef = CardDef {
    id: "CORE_UNG_809",
    name: "Fire Fly",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddCardToHand {
        card_id: "CORE_UNG_809t",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_848 Primordial Drake — 8费 Minion
pub const CORE_PRIMORDIAL_DRAKE: CardDef = CardDef {
    id: "CORE_UNG_848",
    name: "Primordial Drake",
    card_type: CardType::Minion,
    cost: 8,
    attack: 4,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::DamageAllOtherMinions { damage: 2 }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_912 Jeweled Macaw — 1费 Minion
pub const CORE_JEWELED_MACAW: CardDef = CardDef {
    id: "CORE_UNG_912",
    name: "Jeweled Macaw",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Beast,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_WW_329 Detonation Juggernaut — 4费 Minion
pub const CORE_DETONATION_JUGGERNAUT: CardDef = CardDef {
    id: "CORE_WW_329",
    name: "Detonation Juggernaut",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::BuffTauntHandMinions {
        attack: 2,
        health: 2,
    }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Mechanical),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_UNG_809t Flame Elemental — 1费 Minion
pub const CORE_FLAME_ELEMENTAL: CardDef = CardDef {
    id: "CORE_UNG_809t",
    name: "Flame Elemental",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_061t Risen Footman — 1费 Minion
pub const CORE_RISEN_FOOTMAN: CardDef = CardDef {
    id: "CORE_RLK_061t",
    name: "Risen Footman",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
