//! Core Set W5 cards (core-set-roadmap W5) — deathrattle/secret/aura batch.
//! Effects verified against the official Core Set data (2026-08-08).
//! Known simplifications (for the fidelity ledger): Fandral Staghelm's
//! Choose-One combining is not modelled (whiteboard 3/6), Frostmourne's
//! weapon-kill tracking is approximated by the highest-Cost resurrect,
//! Vibrant Squirrel's acorn draw-summon is approximated (no-op deathrattle).

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType, Race};
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;

/// CORE_AT_123 Chillmaw — 7费 Minion
pub const CORE_CHILLMAW: CardDef = CardDef {
    id: "CORE_AT_123",
    name: "Chillmaw",
    card_type: CardType::Minion,
    cost: 7,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DamageAllMinionsIfHoldingDragon { damage: 3 }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_AV_337 Mountain Bear — 7费 Minion
pub const CORE_MOUNTAIN_BEAR: CardDef = CardDef {
    id: "CORE_AV_337",
    name: "Mountain Bear",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMultipleMinions {
        card_id: "CORE_AV_337t",
        count: 2,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BAR_310 Lightshower Elemental — 6费 Minion
pub const CORE_LIGHTSHOWER_ELEMENTAL: CardDef = CardDef {
    id: "CORE_BAR_310",
    name: "Lightshower Elemental",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::RestoreHealth {
        amount: 8,
        target: EffectTarget::AllFriendlyCharacters,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_201 Augmented Porcupine — 3费 Minion
pub const CORE_AUGMENTED_PORCUPINE: CardDef = CardDef {
    id: "CORE_BT_201",
    name: "Augmented Porcupine",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DamageAllEnemiesByAttack),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DAL_720 Waggle Pick — 4费 Weapon
pub const CORE_WAGGLE_PICK: CardDef = CardDef {
    id: "CORE_DAL_720",
    name: "Waggle Pick",
    card_type: CardType::Weapon,
    cost: 4,
    attack: 4,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: Some(CardEffect::ReturnRandomFriendlyAndReduceCost { amount: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_DRG_107 Violet Spellwing — 1费 Minion
pub const CORE_VIOLET_SPELLWING: CardDef = CardDef {
    id: "CORE_DRG_107",
    name: "Violet Spellwing",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::AddCardToHand {
        card_id: "MAGE_001",
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_012 Bloodmage Thalnos — 2费 Minion
pub const CORE_BLOODMAGE_THALNOS: CardDef = CardDef {
    id: "CORE_EX1_012",
    name: "Bloodmage Thalnos",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 1,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_096 Loot Hoarder — 2费 Minion
pub const CORE_LOOT_HOARDER: CardDef = CardDef {
    id: "CORE_EX1_096",
    name: "Loot Hoarder",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawCard { count: 1 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_110 Cairne Bloodhoof — 6费 Minion
pub const CORE_CAIRNE_BLOODHOOF: CardDef = CardDef {
    id: "CORE_EX1_110",
    name: "Cairne Bloodhoof",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "LEGENDARY_001t",
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_383 Tirion Fordring — 8费 Minion
pub const CORE_TIRION_FORDRING: CardDef = CardDef {
    id: "CORE_EX1_383",
    name: "Tirion Fordring",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::EquipWeapon {
        card_id: "PALADIN_008t",
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GVG_114 Sneed's Old Shredder — 7费 Minion
pub const CORE_SNEEDS_OLD_SHREDDER: CardDef = CardDef {
    id: "CORE_GVG_114",
    name: "Sneed's Old Shredder",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonRandomLegendaryMinion),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Mechanical),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOOT_368 Voidlord — 9费 Minion
pub const CORE_VOIDLORD: CardDef = CardDef {
    id: "CORE_LOOT_368",
    name: "Voidlord",
    card_type: CardType::Minion,
    cost: 9,
    attack: 3,
    health: 9,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMultipleMinions {
        card_id: "WARLOCK_004",
        count: 3,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOOT_413 Plated Beetle — 2费 Minion
pub const CORE_PLATED_BEETLE: CardDef = CardDef {
    id: "CORE_LOOT_413",
    name: "Plated Beetle",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GainArmor {
        amount: 3,
        target: EffectTarget::FriendlyHero,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_OG_031 Hammer of Twilight — 5费 Weapon
pub const CORE_HAMMER_OF_TWILIGHT: CardDef = CardDef {
    id: "CORE_OG_031",
    name: "Hammer of Twilight",
    card_type: CardType::Weapon,
    cost: 5,
    attack: 4,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "CORE_OG_031a",
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_RLK_086 Frostmourne — 6费 Weapon
pub const CORE_FROSTMOURNE: CardDef = CardDef {
    id: "CORE_RLK_086",
    name: "Frostmourne",
    card_type: CardType::Weapon,
    cost: 6,
    attack: 4,
    health: 0,
    durability: 3,
    battlecry: None,
    deathrattle: Some(CardEffect::ResurrectWeaponKilled),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_068 Mo'arg Forgefiend — 8费 Minion
pub const CORE_MOARG_FORGEFIEND: CardDef = CardDef {
    id: "CORE_SW_068",
    name: "Mo'arg Forgefiend",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GainArmor {
        amount: 8,
        target: EffectTarget::FriendlyHero,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_439 Vibrant Squirrel — 1费 Minion
pub const CORE_VIBRANT_SQUIRREL: CardDef = CardDef {
    id: "CORE_SW_439",
    name: "Vibrant Squirrel",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_280 Sahket Sapper — 4费 Minion
pub const CORE_SAHKET_SAPPER: CardDef = CardDef {
    id: "CORE_ULD_280",
    name: "Sahket Sapper",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::ReturnToHand {
        target: EffectTarget::AnyEnemyMinion,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Pirate),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_YOD_026 Fiendish Servant — 1费 Minion
pub const CORE_FIENDISH_SERVANT: CardDef = CardDef {
    id: "CORE_YOD_026",
    name: "Fiendish Servant",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GrantAttackToRandomFriendly),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BAR_812 Oasis Ally — 3费 Spell
pub const CORE_OASIS_ALLY: CardDef = CardDef {
    id: "CORE_BAR_812",
    name: "Oasis Ally",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::AfterFriendlyAttacked),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_287 Counterspell — 3费 Spell
pub const CORE_COUNTERSPELL: CardDef = CardDef {
    id: "CORE_EX1_287",
    name: "Counterspell",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::WhenEnemySpellCast),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_289 Ice Barrier — 3费 Spell
pub const CORE_ICE_BARRIER: CardDef = CardDef {
    id: "CORE_EX1_289",
    name: "Ice Barrier",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::WhenEnemyAttacksHero),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_610 Explosive Trap — 2费 Spell
pub const CORE_EXPLOSIVE_TRAP: CardDef = CardDef {
    id: "CORE_EX1_610",
    name: "Explosive Trap",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::WhenEnemyAttacksHero),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_611 Freezing Trap — 2费 Spell
pub const CORE_FREEZING_TRAP: CardDef = CardDef {
    id: "CORE_EX1_611",
    name: "Freezing Trap",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::WhenEnemyAttacksHero),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_577 Rat Trap — 2费 Spell
pub const CORE_RAT_TRAP: CardDef = CardDef {
    id: "CORE_GIL_577",
    name: "Rat Trap",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "CORE_GIL_577t",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::AfterEnemyPlaysThreeCards),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_ULD_152 Pressure Plate — 2费 Spell
pub const CORE_PRESSURE_PLATE: CardDef = CardDef {
    id: "CORE_ULD_152",
    name: "Pressure Plate",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::WhenEnemySpellCast),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_187 Kayn Sunfury — 4费 Minion
pub const CORE_KAYN_SUNFURY: CardDef = CardDef {
    id: "CORE_BT_187",
    name: "Kayn Sunfury",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: true,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CS2_122 Raid Leader — 3费 Minion
pub const CORE_RAID_LEADER: CardDef = CardDef {
    id: "CORE_CS2_122",
    name: "Raid Leader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::AllFriendlyMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_CS2_222 Stormwind Champion — 7费 Minion
pub const CORE_STORMWIND_CHAMPION: CardDef = CardDef {
    id: "CORE_CS2_222",
    name: "Stormwind Champion",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 1,
            health: 1,
        },
        AuraTarget::AllFriendlyMinions,
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_162 Dire Wolf Alpha — 2费 Minion
pub const CORE_DIRE_WOLF_ALPHA: CardDef = CardDef {
    id: "CORE_EX1_162",
    name: "Dire Wolf Alpha",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(2), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_507 Murloc Warleader — 3费 Minion
pub const CORE_MURLOC_WARLEADER: CardDef = CardDef {
    id: "CORE_EX1_507",
    name: "Murloc Warleader",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 2,
            health: 1,
        },
        AuraTarget::FriendlyRace(Race::Murloc),
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_NEW1_027 Southsea Captain — 3费 Minion
pub const CORE_SOUTHSEA_CAPTAIN: CardDef = CardDef {
    id: "CORE_NEW1_027",
    name: "Southsea Captain",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Pirate),
    hero_power: None,
    aura: Some((
        AuraEffect::GainStats {
            attack: 1,
            health: 1,
        },
        AuraTarget::FriendlyRace(Race::Pirate),
    )),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_OG_044 Fandral Staghelm — 4费 Minion
pub const CORE_FANDRAL_STAGHELM: CardDef = CardDef {
    id: "CORE_OG_044",
    name: "Fandral Staghelm",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_AV_337t Mountain Cub — 2费 Minion
pub const CORE_MOUNTAIN_CUB: CardDef = CardDef {
    id: "CORE_AV_337t",
    name: "Mountain Cub",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BAR_812t Water Elemental — 4费 Minion
pub const CORE_WATER_ELEMENTAL: CardDef = CardDef {
    id: "CORE_BAR_812t",
    name: "Water Elemental",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_OG_031a Twilight Elemental — 4费 Minion
pub const CORE_TWILIGHT_ELEMENTAL: CardDef = CardDef {
    id: "CORE_OG_031a",
    name: "Twilight Elemental",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_GIL_577t Doom Rat — 6/6 (Rat Trap's secret token).
pub const CORE_DOOM_RAT: CardDef = CardDef {
    id: "CORE_GIL_577t",
    name: "Doom Rat",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
