//! Core Set W2 cards (core-set-roadmap W2) — hand/spell-pipeline primitives.
//!
//! TRADEABLE is a component applied by `apply_card_keywords`
//! (`Action::TradeCard`); OUTCAST effects are the `DrawCardOutcast` /
//! `OutcastDamage` variants resolved against the OutcastPlayed marker;
//! ImmuneToSpellpower cards are exempt in `apply_spell_power`. Chinese names
//! follow the `classic-cards-zh.md` convention once the cards land.
//!
//! Card data: `cards/cards.json` (CORE_* IDs); card texts verified against
//! the official Core Set versions (2026-08-08).

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;

/// CORE_EX1_002 The Black Knight — 4/4, Tradeable. Battlecry: destroy an
/// enemy minion with Taunt.
pub const CORE_THE_BLACK_KNIGHT: CardDef = CardDef {
    id: "CORE_EX1_002",
    name: "The Black Knight",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::TauntEnemyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_EX1_005 Big Game Hunter — 4/2, Tradeable. Battlecry: destroy an
/// enemy minion with 5 or more Attack.
pub const CORE_BIG_GAME_HUNTER: CardDef = CardDef {
    id: "CORE_EX1_005",
    name: "Big Game Hunter",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::DestroyMinion {
        target: EffectTarget::EnemyMinionAttackGE(5),
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_REV_023 Demolition Renovator — 3/3, Tradeable. Battlecry: destroy
/// an enemy location (no Location card type until W8 — the effect resolves
/// against no targets and fizzles for now).
pub const DEMOLITION_RENOVATOR: CardDef = CardDef {
    id: "CORE_REV_023",
    name: "Demolition Renovator",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DestroyEnemyLocation),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_066 Royal Librarian — 4/4, Tradeable. Battlecry: silence a
/// minion.
pub const ROYAL_LIBRARIAN: CardDef = CardDef {
    id: "CORE_SW_066",
    name: "Royal Librarian",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SilenceMinion {
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_072 Rustrot Viper — 3/4, Tradeable. Battlecry: destroy your
/// opponent's weapon.
pub const RUSTROT_VIPER: CardDef = CardDef {
    id: "CORE_SW_072",
    name: "Rustrot Viper",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DestroyWeapon),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_429 Best in Shell — 6-cost spell, Tradeable. Summon two 2/7
/// Turtles with Taunt.
pub const BEST_IN_SHELL: CardDef = CardDef {
    id: "CORE_SW_429",
    name: "Best in Shell",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::SummonMultipleMinions {
        card_id: "CORE_SW_429t",
        count: 2,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_SW_429t Turtle — 2/7 Beast with Taunt (Best in Shell's token;
/// id ends in 't', so the RL pool filters it out).
pub const TURTLE: CardDef = CardDef {
    id: "CORE_SW_429t",
    name: "Turtle",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_480 Crimson Sigil Runner — 1/1 Demon, Outcast: draw a card.
pub const CRIMSON_SIGIL_RUNNER: CardDef = CardDef {
    id: "CORE_BT_480",
    name: "Crimson Sigil Runner",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::DrawCardOutcast {
        normal: 0,
        outcast: 1,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_491 Spectral Sight — 2-cost spell, Outcast: draw a card, or two
/// when played from the hand edge.
pub const SPECTRAL_SIGHT: CardDef = CardDef {
    id: "CORE_BT_491",
    name: "Spectral Sight",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::DrawCardOutcast {
        normal: 1,
        outcast: 2,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BT_801 Eye Beam — 3-cost spell, Lifesteal (W1 component). Deal 3
/// damage to a minion; Outcast: 6 instead. (The W1 half shipped in W1; the
/// Outcast half completes the card in W2.)
pub const EYE_BEAM: CardDef = CardDef {
    id: "CORE_BT_801",
    name: "Eye Beam",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::OutcastDamage {
        amount: 3,
        outcast_amount: 6,
        target: EffectTarget::AnyMinion,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BAR_311 Devouring Plague — 3-cost Priest spell, Lifesteal (W1).
/// Deal 4 damage randomly split among all enemy minions; Immune to spell
/// damage (the W2 exemption completes the card).
pub const DEVOURING_PLAGUE: CardDef = CardDef {
    id: "CORE_BAR_311",
    name: "Devouring Plague",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::DealDamageRandomly {
        amount: 1,
        count: 4,
        target: EffectTarget::AnyEnemyMinion,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOOT_101 Explosive Runes — 3-cost secret, Immune to spell damage.
/// Secret: after your opponent plays a minion, deal 6 damage to it and any
/// excess to their hero.
pub const EXPLOSIVE_RUNES: CardDef = CardDef {
    id: "CORE_LOOT_101",
    name: "Explosive Runes",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamagePlayedMinionAndExcess { amount: 6 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: Some(crate::core::component::SecretTrigger::AfterEnemyMinionPlayed),
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_LOOT_373 Healing Rain — 3-cost Priest spell, Immune to spell
/// damage. Restore 12 health randomly split among all friendly characters.
pub const HEALING_RAIN: CardDef = CardDef {
    id: "CORE_LOOT_373",
    name: "Healing Rain",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::RestoreRandomFriendly { amount: 12 }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CORE_BRM_013 Quick Shot — 2-cost Hunter spell, affected by spell damage
/// (the official AFFECTED_BY_SPELL_POWER marker — the engine applies spell
/// damage to all spells by default). Deal 3 damage to a minion; if your
/// hand is empty, draw a card.
pub const QUICK_SHOT: CardDef = CardDef {
    id: "CORE_BRM_013",
    name: "Quick Shot",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: Some(CardEffect::DamageAndDrawIfHandEmpty {
        damage: 3,
        target: EffectTarget::AnyMinion,
    }),
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
