//! M4-W1 cards (exp_cata_w1) — the Cataclysm sub-roadmap W1: the 11
//! **Colossal** cards and their 31 appendage tokens (2025–2026 expansions
//! master roadmap M4-W1, the C1 body-part primitive).
//!
//! The Colossal mechanic itself (the `ColossalPart`/`ColossalMain`
//! components, the summon path and the death cascade) lives in
//! `cards/colossal.rs`; the CardDef here only carries the plain minion
//! data and the card's own non-Colossal effects.
//!
//! Implementation decisions (per the M4-W1 spec, verified against
//! `/tmp/hs_full.json` 2026-08-09; the fidelity rows are fidelity-debt.md
//! §23, en + zh):
//! - **Colossal +N** is data, not a CardDef field: `colossal_parts` in
//!   cards/colossal.rs maps each main's id to its appendage token ids
//!   (Magmaw CATA_550 is the `fill` entry — +99 clamps to the free board
//!   space at summon).
//! - **Wickerfang CATA_139**: the main is a plain 6/0/5. Each Leg's
//!   end-of-turn +1/+1 is `GainStatsAndCopyToColossalMain` — the leg
//!   gains, then the main copies via the part→main link (the official
//!   "after a Leg gains stats" trigger only copies the legs' own
//!   end-of-turn gains, §23).
//! - **Ragnaros CATA_150**: "At the end of your turn, trigger your
//!   minions' Deathrattles" — `TriggerFriendlyDeathrattles`, a play-order
//!   scan of the living board (distinct from the graveyard-scan
//!   `TriggerFriendlyDeadDeathrattles`). The Hands of Ragnaros carry the
//!   Herald `{0}` placeholder in the official text ("Deal {0} damage to a
//!   random enemy") — fixed to 2 (§23).
//! - **Azshara CATA_151**: "Your hero has Windfury" — the
//!   `AuraEffect::GrantWindfury` / `AuraTarget::FriendlyHero` aura pair
//!   (new aura primitives, wired through both aura_applies_to functions
//!   and the attack-bucket query). The Tentacles' on-summon hero-+Attack
//!   `{0}` is fixed to 2 (`GainHeroAttack` is already until-end-of-turn,
//!   §23).
//! - **Al'Akir CATA_153**: "Battlecry: Get 2 minions with Cost equal to
//!   this minion's Attack. They cost (1)" — `AddRandomMinionsCostEqualAttack`
//!   with the roadmap G5 set-to-(1) cost modifier. Rush rides the
//!   apply_card_keywords hook; Windfury is a CardDef field. The Charged
//!   Hands' adjacent +`{0}` is fixed to +1 (§23).
//! - **Sinestra CATA_154**: "Your spells from other classes cast twice" —
//!   the rules.rs CardPlayed hook re-resolves the spell's effect once
//!   while a friendly Sinestra is on board (the Tyrande convention: no
//!   explicit target, no second SpellCast event). The class filter is
//!   DROPPED — the engine has no per-player or per-card class concept, so
//!   ALL spells double (§23). The Wings' on-summon "get a random spell
//!   from another class, it costs ({0}) less" reuses
//!   `AddRandomOtherClassSpells` with the reduction fixed to 0 (§23).
//! - **Arisen Onyxia CATA_155**: "When your hero would lose Health on
//!   your turn, gain that much max Health instead" — the rules.rs
//!   DamageDealt redirect converts hero health-loss into a permanent
//!   max-Health enchantment (before armor/weapon absorption, §23). The
//!   Wings' on-summon "get a random {0}-Cost minion. It costs Health this
//!   turn" fixes {0} to 0; the CostHealth marker is not cleared when the
//!   turn ends (§23).
//! - **The Black Blood CATA_300**: "After you restore Health to a
//!   character, attack a random enemy minion" — an id-keyed
//!   `CharacterHealed` trigger (registered in apply_card_keywords) with
//!   the reused `AttackRandomEnemyMinionExcess` (the Briarspawn Drake
//!   excess-damage model). The trigger class fires on ANY heal on either
//!   side — the official "you restore" scope is approximated (§23). The
//!   Bodies' "#3" is a fixed 3 (not a Herald placeholder):
//!   `RestoreDamagedFriendly`.
//! - **Chromatus CATA_432**: Taunt/Lifesteal/Elusive/Divine Shield — the
//!   CardDef fields carry all but Lifesteal (id-keyed hook). The four
//!   Heads each carry one keyword plus a
//!   `RemoveKeywordFromColossalMain` deathrattle that strips it from the
//!   main via the part→main link (the main keeps the other three).
//! - **Vulcanos CATA_488**: "At the end of your turn, deal 2 damage to
//!   all other minions" — the reused `DamageAllOtherMinions` (Primordial
//!   Drake). The Plumes' "Whenever this takes damage, get a random Fire
//!   spell. It costs (3) less" — `ThisMinionDamaged` trigger + the
//!   `AddRandomFireSpellCostsLess` effect (Fire filter reads the quest
//!   registry's official spell-school table).
//! - **Magmaw CATA_550**: "Colossal +99 — summon any leftover appendages
//!   when there is room" — the `fill` registry entry (both fill and
//!   non-fill clamp to `min(parts, free slots)` at summon; the maximum
//!   free space is 6, exactly the Body count). The Bodies' deathrattle is
//!   a fixed `GiveRandomFriendlyMinionAttack` +2.
//! - **Cho'gall CATA_726**: "Your Arms and Soldiers destroy minions in
//!   the enemy's deck instead" — while a friendly Cho'gall is on the
//!   board, the Arms' end-of-turn destruction redirects to a random enemy
//!   DECK minion; otherwise it destroys the friendly minion to the right
//!   and the Arm gains +2/+2 (the `{0}` fixed to 2, §23). The "Soldiers"
//!   cards are W2+ and share the same hook when they land (§23).
//! - **Stats** follow the official JSON data (`/tmp/hs_full.json`
//!   2026-08-09); they match the generated baselines (the differential
//!   gate compares the handwritten mains against the W0 generated data —
//!   the tokens are handwritten-only, no baselines).

use crate::cards::def::CardDef;
use crate::core::component::{AuraEffect, AuraTarget, CardType, Race};
use crate::core::effect::{CardEffect, EffectTarget};

/// CATA_139 Wickerfang — 6-cost 0/5 (MINION, Druid). Colossal +4.
pub const WICKERFANG: CardDef = CardDef {
    id: "CATA_139",
    name: "Wickerfang",
    card_type: CardType::Minion,
    cost: 6,
    attack: 0,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_150 Ragnaros, the Great Fire — 8-cost 8/8 (MINION, Elemental,
/// Warrior). Colossal +2; at the end of your turn, trigger your minions'
/// Deathrattles.
pub const RAGNAROS_THE_GREAT_FIRE: CardDef = CardDef {
    id: "CATA_150",
    name: "Ragnaros, the Great Fire",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::TriggerFriendlyDeathrattles),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_151 Azshara, Ocean Lord — 8-cost 8/8 (MINION, Naga,
/// Demon Hunter). Colossal +2; your hero has Windfury.
pub const AZSHARA_OCEAN_LORD: CardDef = CardDef {
    id: "CATA_151",
    name: "Azshara, Ocean Lord",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Naga),
    hero_power: None,
    aura: Some((AuraEffect::GrantWindfury, AuraTarget::FriendlyHero)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_153 Al'Akir, Lord of Storms — 8-cost 2/8 (MINION, Elemental,
/// Shaman). Colossal +2, Rush, Windfury. Battlecry: get 2 minions with
/// Cost equal to this minion's Attack; they cost (1).
pub const ALAKIR_LORD_OF_STORMS: CardDef = CardDef {
    id: "CATA_153",
    name: "Al'Akir, Lord of Storms",
    card_type: CardType::Minion,
    cost: 8,
    attack: 2,
    health: 8,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomMinionsCostEqualAttack { count: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: true,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_154 Sinestra — 6-cost 5/5 (MINION, Dragon, Rogue). Colossal +2;
/// your spells from other classes cast twice (the class filter is
/// dropped — see the module docs and fidelity-debt §23).
pub const SINESTRA: CardDef = CardDef {
    id: "CATA_154",
    name: "Sinestra",
    card_type: CardType::Minion,
    cost: 6,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_155 Arisen Onyxia — 9-cost 3/6 (MINION, Dragon + Undead,
/// Death Knight). Colossal +2; when your hero would lose Health on your
/// turn, gain that much max Health instead (the rules.rs redirect).
pub const ARISEN_ONYXIA: CardDef = CardDef {
    id: "CATA_155",
    name: "Arisen Onyxia",
    card_type: CardType::Minion,
    cost: 9,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_300 The Black Blood — 7-cost 5/9 (MINION, Priest). Colossal +3;
/// after you restore Health to a character, attack a random enemy minion
/// (the CharacterHealed trigger rides apply_card_keywords).
pub const THE_BLACK_BLOOD: CardDef = CardDef {
    id: "CATA_300",
    name: "The Black Blood",
    card_type: CardType::Minion,
    cost: 7,
    attack: 5,
    health: 9,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_432 Chromatus — 8-cost 8/8 (MINION, Dragon, Paladin). Colossal
/// +4; Taunt, Lifesteal, Elusive, Divine Shield.
pub const CHROMATUS: CardDef = CardDef {
    id: "CATA_432",
    name: "Chromatus",
    card_type: CardType::Minion,
    cost: 8,
    attack: 8,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: true,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_488 Vulcanos — 7-cost 4/8 (MINION, Elemental, Mage). Colossal
/// +2; at the end of your turn, deal 2 damage to all other minions.
pub const VULCANOS: CardDef = CardDef {
    id: "CATA_488",
    name: "Vulcanos",
    card_type: CardType::Minion,
    cost: 7,
    attack: 4,
    health: 8,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::DamageAllOtherMinions { damage: 2 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550 Magmaw — 7-cost 2/12 (MINION, Beast + Mechanical, Hunter).
/// Colossal +99 — summon any leftover appendages when there is room (the
/// `fill` registry entry; the count clamps to the free board space).
pub const MAGMAW: CardDef = CardDef {
    id: "CATA_550",
    name: "Magmaw",
    card_type: CardType::Minion,
    cost: 7,
    attack: 2,
    health: 12,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_726 Cho'gall, Mastermind — 9-cost 6/6 (MINION, Warlock).
/// Colossal +2; your Arms and Soldiers destroy minions in the enemy's
/// deck instead (the Arms' destroy hook reads the friendly-Cho'gall
/// switch; "Soldiers" are W2+ cards sharing the hook).
pub const CHOGALL_MASTERMIND: CardDef = CardDef {
    id: "CATA_726",
    name: "Cho'gall, Mastermind",
    card_type: CardType::Minion,
    cost: 9,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// ---------------------------------------------------------------
// Appendage tokens (31, all handwritten-only — no generated baselines)
// ---------------------------------------------------------------

/// CATA_139t Wickerfang's Leg — 1-cost 0/2 (MINION, Druid). Colossal
/// appendage; at the end of your turn, gain +1/+1 (the main copies the
/// gain via `GainStatsAndCopyToColossalMain`).
pub const WICKERFANGS_LEG: CardDef = CardDef {
    id: "CATA_139t",
    name: "Wickerfang's Leg",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStatsAndCopyToColossalMain {
        attack: 1,
        health: 1,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_139t2 Wickerfang's Leg (2) — identical to CATA_139t.
pub const WICKERFANGS_LEG_2: CardDef = CardDef {
    id: "CATA_139t2",
    name: "Wickerfang's Leg",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStatsAndCopyToColossalMain {
        attack: 1,
        health: 1,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_139t3 Wickerfang's Leg (3) — identical to CATA_139t.
pub const WICKERFANGS_LEG_3: CardDef = CardDef {
    id: "CATA_139t3",
    name: "Wickerfang's Leg",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStatsAndCopyToColossalMain {
        attack: 1,
        health: 1,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_139t4 Wickerfang's Leg (4) — identical to CATA_139t.
pub const WICKERFANGS_LEG_4: CardDef = CardDef {
    id: "CATA_139t4",
    name: "Wickerfang's Leg",
    card_type: CardType::Minion,
    cost: 1,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStatsAndCopyToColossalMain {
        attack: 1,
        health: 1,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_150t Hand of Ragnaros — 1-cost 2/1 (MINION, Elemental, Warrior).
/// Deathrattle: deal 2 damage to a random enemy (the official {0} is
/// fixed to 2, §23).
pub const HAND_OF_RAGNAROS: CardDef = CardDef {
    id: "CATA_150t",
    name: "Hand of Ragnaros",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamageRandomly {
        amount: 2,
        count: 1,
        target: EffectTarget::AnyEnemy,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_150t1 Hand of Ragnaros (2) — identical to CATA_150t.
pub const HAND_OF_RAGNAROS_2: CardDef = CardDef {
    id: "CATA_150t1",
    name: "Hand of Ragnaros",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamageRandomly {
        amount: 2,
        count: 1,
        target: EffectTarget::AnyEnemy,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_151t Azshara's Tentacle — 1-cost 2/1 (MINION, Naga, Demon
/// Hunter). When summoned, give your hero +2 Attack this turn (the
/// official {0} is fixed to 2; the effect rides the
/// `appendage_on_summon` registry, §23).
pub const AZSHARAS_TENTACLE: CardDef = CardDef {
    id: "CATA_151t",
    name: "Azshara's Tentacle",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Naga),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_151t1 Azshara's Tentacle (2) — identical to CATA_151t.
pub const AZSHARAS_TENTACLE_2: CardDef = CardDef {
    id: "CATA_151t1",
    name: "Azshara's Tentacle",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Naga),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_153t Charged Hand of Al'Akir — 1-cost 1/2 (MINION, Elemental,
/// Shaman). Adjacent minions have +1 Attack (the official {0} is fixed
/// to 1, §23).
pub const CHARGED_HAND_OF_ALAKIR: CardDef = CardDef {
    id: "CATA_153t",
    name: "Charged Hand of Al'Akir",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_153t1 Charged Hand of Al'Akir (2) — identical to CATA_153t.
pub const CHARGED_HAND_OF_ALAKIR_2: CardDef = CardDef {
    id: "CATA_153t1",
    name: "Charged Hand of Al'Akir",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: Some((AuraEffect::GainAttack(1), AuraTarget::AdjacentMinions)),
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_154t Sinestra's Wing — 1-cost 1/1 (MINION, Dragon, Rogue).
/// When summoned, get a random spell from another class (the official
/// "It costs ({0}) less" reduction is fixed to 0 — the effect rides the
/// `appendage_on_summon` registry, §23).
pub const SINESTRAS_WING: CardDef = CardDef {
    id: "CATA_154t",
    name: "Sinestra's Wing",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_154t1 Sinestra's Wing (2) — identical to CATA_154t.
pub const SINESTRAS_WING_2: CardDef = CardDef {
    id: "CATA_154t1",
    name: "Sinestra's Wing",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_155t Onyxia's Wing — 1-cost 1/1 (MINION, Dragon + Undead, Death
/// Knight). When summoned, get a random 0-Cost minion; it costs Health
/// this turn (the official {0} is fixed to 0; the effect rides the
/// `appendage_on_summon` registry, §23).
pub const ONYXIAS_WING: CardDef = CardDef {
    id: "CATA_155t",
    name: "Onyxia's Wing",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_155t1 Onyxia's Wing (2) — identical to CATA_155t.
pub const ONYXIAS_WING_2: CardDef = CardDef {
    id: "CATA_155t1",
    name: "Onyxia's Wing",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_300t1 Black Blood's Body — 2-cost 2/2 (MINION, Priest). At the
/// end of your turn, restore 3 Health to a random damaged friendly
/// character (the official "#3" is a fixed 3).
pub const BLACK_BLOODS_BODY: CardDef = CardDef {
    id: "CATA_300t1",
    name: "Black Blood's Body",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::RestoreDamagedFriendly { amount: 3 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_300t2 Black Blood's Body (2) — identical to CATA_300t1.
pub const BLACK_BLOODS_BODY_2: CardDef = CardDef {
    id: "CATA_300t2",
    name: "Black Blood's Body",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::RestoreDamagedFriendly { amount: 3 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_300t3 Black Blood's Body (3) — identical to CATA_300t1.
pub const BLACK_BLOODS_BODY_3: CardDef = CardDef {
    id: "CATA_300t3",
    name: "Black Blood's Body",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::RestoreDamagedFriendly { amount: 3 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_432t1 Green Head of Chromatus — 2-cost 2/3 (MINION, Dragon,
/// Paladin). Taunt; deathrattle: remove Taunt from Chromatus.
pub const GREEN_HEAD_OF_CHROMATUS: CardDef = CardDef {
    id: "CATA_432t1",
    name: "Green Head of Chromatus",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::RemoveKeywordFromColossalMain {
        keyword: crate::core::effect::KeywordKind::Taunt,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_432t2 Red Head of Chromatus — 2-cost 2/3 (MINION, Dragon,
/// Paladin). Lifesteal; deathrattle: remove Lifesteal from Chromatus.
pub const RED_HEAD_OF_CHROMATUS: CardDef = CardDef {
    id: "CATA_432t2",
    name: "Red Head of Chromatus",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::RemoveKeywordFromColossalMain {
        keyword: crate::core::effect::KeywordKind::Lifesteal,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_432t3 Blue Head of Chromatus — 2-cost 2/3 (MINION, Dragon,
/// Paladin). Elusive; deathrattle: remove Elusive from Chromatus.
pub const BLUE_HEAD_OF_CHROMATUS: CardDef = CardDef {
    id: "CATA_432t3",
    name: "Blue Head of Chromatus",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::RemoveKeywordFromColossalMain {
        keyword: crate::core::effect::KeywordKind::Elusive,
    }),
    taunt: false,
    stealth: false,
    elusive: true,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_432t4 Bronze Head of Chromatus — 2-cost 2/3 (MINION, Dragon,
/// Paladin). Divine Shield; deathrattle: remove Divine Shield from
/// Chromatus.
pub const BRONZE_HEAD_OF_CHROMATUS: CardDef = CardDef {
    id: "CATA_432t4",
    name: "Bronze Head of Chromatus",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::RemoveKeywordFromColossalMain {
        keyword: crate::core::effect::KeywordKind::DivineShield,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: true,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_488t Plume of Vulcanos — 2-cost 1/4 (MINION, Elemental, Mage).
/// Whenever this takes damage, get a random Fire spell; it costs (3)
/// less (the ThisMinionDamaged trigger rides apply_card_keywords).
pub const PLUME_OF_VULCANOS: CardDef = CardDef {
    id: "CATA_488t",
    name: "Plume of Vulcanos",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_488t2 Plume of Vulcanos (2) — identical to CATA_488t.
pub const PLUME_OF_VULCANOS_2: CardDef = CardDef {
    id: "CATA_488t2",
    name: "Plume of Vulcanos",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t Magmaw's Body — 1-cost 2/1 (MINION, Beast + Mechanical,
/// Hunter). Deathrattle: give a random friendly minion +2 Attack.
pub const MAGMAWS_BODY: CardDef = CardDef {
    id: "CATA_550t",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t2 Magmaw's Body (2) — identical to CATA_550t.
pub const MAGMAWS_BODY_2: CardDef = CardDef {
    id: "CATA_550t2",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t3 Magmaw's Body (3) — identical to CATA_550t.
pub const MAGMAWS_BODY_3: CardDef = CardDef {
    id: "CATA_550t3",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t4 Magmaw's Body (4) — identical to CATA_550t.
pub const MAGMAWS_BODY_4: CardDef = CardDef {
    id: "CATA_550t4",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t5 Magmaw's Body (5) — identical to CATA_550t.
pub const MAGMAWS_BODY_5: CardDef = CardDef {
    id: "CATA_550t5",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_550t6 Magmaw's Body (6) — identical to CATA_550t.
pub const MAGMAWS_BODY_6: CardDef = CardDef {
    id: "CATA_550t6",
    name: "Magmaw's Body",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GiveRandomFriendlyMinionAttack { attack: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_726t Cho's Arm — 1-cost 1/1 (MINION, Warlock). At the end of
/// your turn, destroy the minion to the right to gain +2/+2 (the
/// official {0} is fixed to 2; while a friendly Cho'gall is on the
/// board, the destruction targets the enemy's deck instead, §23).
pub const CHOS_ARM: CardDef = CardDef {
    id: "CATA_726t",
    name: "Cho's Arm",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::ColossalArmDestroyRight {
        attack: 2,
        health: 2,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// CATA_726t1 Gall's Arm — 1-cost 1/1 (MINION, Warlock). Same as Cho's
/// Arm (the second of Cho'gall's two arms).
pub const GALLS_ARM: CardDef = CardDef {
    id: "CATA_726t1",
    name: "Gall's Arm",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::ColossalArmDestroyRight {
        attack: 2,
        health: 2,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
