//! 2025–2026 expansions M1-W4a cards (exp_edr_w4a) — the Emerald Dream (EDR)
//! misc-effects wave, first half: the 86 non-legendary cards of the W4
//! "remaining cards" list (the 23 elite Wild Gods are M1-W4b and are NOT
//! implemented here; the FIR_* miniset is M1-W5).
//!
//! Mechanics introduced by this wave:
//! - deck-top buffs (Beanstalk Brute — the deck is ordered, so the top 3
//!   minions are the first 3 in deck order; enchantments persist across the
//!   deck → hand → play moves, see `World::move_to_zone`);
//! - death records via the graveyard zone (Succumb to Madness, the
//!   Felhunter/Felbat resurrection pair, Starsurge's fallen-count);
//! - a per-player spell-cast counter (`Player::spells_cast_total`, the New
//!   Moon upgrade condition — registered simplification, the real per-card
//!   tracking is approximated per-player);
//! - a per-player hero-power-use counter (`Player::hero_power_uses`,
//!   Glowroot Lure's cost reduction) and a one-time free-hero-power flag
//!   (Dreambound Disciple);
//! - per-player pending end-of-turn timers (Rotten Apple's self damage and
//!   Fractured Power's delayed crystals);
//! - the played-minion log (`Player::played_minion_ids`, Twisted Webweaver).
//!
//! D2 simplifications registered in `docs/finished/fidelity-debt.md` §14.3:
//! Nature spell school → any spell; Dormant → a plain can't-attack token;
//! "didn't start there" → dropped; "cast a random spell" (Forbidden Shrine)
//! → direct effect resolution; per-instance card identity (egg hatch, eaten
//! minion, treant's spell copy) → fixed/random substitutes; opponent-summons
//! and bounce-to-hand triggers → unmodeled (inert cards); rune tracking and
//! the leech-steal aura → dropped; the "can't play for 2 turns" restriction
//! → dropped.
//!
//! These consts are handwritten effect-wave implementations of the generated
//! expansion baselines: they never enter `ALL_CARDS` (the sampling pools
//! stay closed, decision D3) but are reachable through the `card_by_id`
//! chain (ALL_CARDS → HANDWRITTEN_EXPANSION_CARDS → EXPANSION_CARDS) and are
//! compared field-by-field against the generated baseline by the
//! `expansion_differential_gate` test (M0.4). Simplifications registered in
//! `docs/finished/fidelity-debt.md` §14.3 (2025–2026 expansions).
//!
//! Card data: `cards/cards.json` (EDR_* ids); card texts verified against
//! the official Emerald Dream set (2026-08-08).

use crate::cards::def::CardDef;
use crate::core::component::CardType;
use crate::core::component::Race;
use crate::core::effect::CardEffect;
use crate::core::effect::EffectTarget;
use crate::core::effect::RandomPool;

// ---------------------------------------------------------------------------
// M1-W4a cards
// ---------------------------------------------------------------------------

/// EDR_001 Hopeful Dryad — 3/3/3 Neutral. Battlecry: Get a random Dream card.
pub const HOPEFUL_DRYAD: CardDef = CardDef {
    id: "EDR_001",
    name: "Hopeful Dryad",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Dream,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_014 Verdant Dreamsaber — 5/4/7 Hunter Beast. Battlecry: If this costs
/// (3) or less, attack two random enemy minions. (The attack is modeled as
/// direct damage, like the "excess damage" family.)
pub const VERDANT_DREAMSABER: CardDef = CardDef {
    id: "EDR_014",
    name: "Verdant Dreamsaber",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 7,
    durability: 0,
    battlecry: Some(CardEffect::AttackTwoRandomEnemyMinionsIfCostLE { cost: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_060 Ward of Earth — 5-mana Druid spell. Gain 5 Armor. Summon a random
/// 5-Cost minion and give it Taunt.
pub const WARD_OF_EARTH: CardDef = CardDef {
    id: "EDR_060",
    name: "Ward of Earth",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::GainArmorSummonCostTaunt { armor: 5, cost: 5 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_105 Creature of Madness — 2/1/1 Neutral. Battlecry: Discover a 3-Cost
/// minion with a Dark Gift. (Discover simplified to random, per the fixed
/// Discover simplification.)
pub const CREATURE_OF_MADNESS: CardDef = CardDef {
    id: "EDR_105",
    name: "Creature of Madness",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCostMinionWithDarkGift { cost: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_110 Sporegnasher — 5/1/5 Neutral. Poisonous. Deathrattle: Deal 1
/// damage to a random enemy minion. (Poisonous lands via
/// `apply_card_keywords`, like the Core Set keywords.)
pub const SPOREGNASHER: CardDef = CardDef {
    id: "EDR_110",
    name: "Sporegnasher",
    card_type: CardType::Minion,
    cost: 5,
    attack: 1,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DealDamage {
        amount: 1,
        target: EffectTarget::AnyEnemyMinion,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_230 Beanstalk Brute — 5/4/4 Shaman Elemental. Battlecry: Give +4/+4
/// to the top 3 minions in your deck. (The deck is ordered; the "top 3
/// minions" are the first three minions in deck order. Enchantments persist
/// deck → hand → play, so the buff applies when the cards are drawn.)
pub const BEANSTALK_BRUTE: CardDef = CardDef {
    id: "EDR_230",
    name: "Beanstalk Brute",
    card_type: CardType::Minion,
    cost: 5,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::BuffTopDeckMinions {
        attack: 4,
        health: 4,
        count: 3,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_232 Typhoon — 10-mana Shaman spell. Each minion gets shuffled into a
/// random player's deck. (The deck choice is random per minion.)
pub const TYPHOON: CardDef = CardDef {
    id: "EDR_232",
    name: "Typhoon",
    card_type: CardType::Spell,
    cost: 10,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ShuffleAllMinionsIntoDecks),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_234 Emerald Bounty — 2-mana Shaman spell. Draw 2 cards. You can't
/// play them for 2 turns. (simplified: the "can't play for 2 turns"
/// restriction is dropped — it would need per-card play locks, see §14.3.)
pub const EMERALD_BOUNTY: CardDef = CardDef {
    id: "EDR_234",
    name: "Emerald Bounty",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawCard { count: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_251 Dragonscale Armaments — 1-mana Paladin spell. Draw a spell that
/// started in your deck and one that didn't. (simplified: the engine does
/// not track card origins, so the "didn't start there" half becomes a random
/// spell — §14.3.)
pub const DRAGONSCALE_ARMAMENTS: CardDef = CardDef {
    id: "EDR_251",
    name: "Dragonscale Armaments",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawDeckSpellAndAddRandomSpell),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_252 Mark of Ursol — 2-mana Paladin spell. Choose a minion. If it's an
/// enemy, set its stats to 1/1. If it's friendly, set its stats to 3/3
/// instead.
pub const MARK_OF_URSOL: CardDef = CardDef {
    id: "EDR_252",
    name: "Mark of Ursol",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SetStatsByFriendlyTarget {
        enemy_attack: 1,
        enemy_health: 1,
        friendly_attack: 3,
        friendly_health: 3,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_253 Ursine Maul — 4/4/2 Paladin weapon. After your hero attacks, draw
/// a card. (The HeroAttacked weapon trigger lands in `apply_card_keywords`,
/// like Truesilver Champion.)
pub const URSINE_MAUL: CardDef = CardDef {
    id: "EDR_253",
    name: "Ursine Maul",
    card_type: CardType::Weapon,
    cost: 4,
    attack: 4,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_254 Animated Moonwell — 3/1/4 Neutral Elemental. After you cast a
/// spell, gain Attack equal to its Cost.
pub const ANIMATED_MOONWELL: CardDef = CardDef {
    id: "EDR_254",
    name: "Animated Moonwell",
    card_type: CardType::Minion,
    cost: 3,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: Some(CardEffect::GainAttackEqualSpellCost),
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_255 Renewing Flames — 7-mana Paladin spell. Lifesteal. Deal 5 damage
/// to the lowest Health enemy, twice. (Lifesteal lands via
/// `apply_card_keywords`, like Devouring Plague.)
pub const RENEWING_FLAMES: CardDef = CardDef {
    id: "EDR_255",
    name: "Renewing Flames",
    card_type: CardType::Spell,
    cost: 7,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageLowestHealthEnemyTwice { amount: 5 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_256 Dreamwarden — 4/3/4 Paladin Dragon. Taunt. Battlecry: If there is
/// a card in your deck that didn't start there, draw it and gain +2/+2.
/// (simplified: the engine does not track card origins, so the condition is
/// dropped — the battlecry always draws the top card and gains +2/+2, §14.3.)
pub const DREAMWARDEN: CardDef = CardDef {
    id: "EDR_256",
    name: "Dreamwarden",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::DrawAndGainStats {
        attack: 2,
        health: 2,
    }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_260 Illusory Greenwing — 4/4/5 Neutral Dragon. Taunt. Deathrattle:
/// Shuffle two 4/5 Dragons with Taunt into your deck. They're Summoned When
/// Drawn. (simplified: the "Summoned When Drawn" half is dropped — drawn
/// cards enter the hand normally, §14.3.)
pub const ILLUSORY_GREENWING: CardDef = CardDef {
    id: "EDR_260",
    name: "Illusory Greenwing",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::ShuffleCardIntoDeck {
        card_id: "EDR_260t",
        count: 2,
    }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_261 Amphibian's Spirit — 3-mana Hunter spell. Give a minion +2/+2 and
/// "Deathrattle: Give a friendly minion +2/+2 and this Deathrattle."
/// (simplified: the engine stores one Deathrattle per entity, so a target
/// that already has one is replaced, §14.3.)
pub const AMPHIBIANS_SPIRIT: CardDef = CardDef {
    id: "EDR_261",
    name: "Amphibian's Spirit",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AmphibianSpiritBuff {
        attack: 2,
        health: 2,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_262 Spirit Bond — 3-mana Hunter spell. Deal 3 damage to a minion. If
/// it dies, summon a 3/2 Wolf with Rush.
pub const SPIRIT_BOND: CardDef = CardDef {
    id: "EDR_262",
    name: "Spirit Bond",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageAndSummonWolfIfKilled { damage: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_270 Horn of Plenty — 2-mana Druid spell. Discover a Nature spell. It
/// costs (2) less. (simplified: the Nature spell school is not modeled, so
/// the pool is any spell, and Discover is random, §14.3.)
pub const HORN_OF_PLENTY: CardDef = CardDef {
    id: "EDR_270",
    name: "Horn of Plenty",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomSpellCostsLess { reduction: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_271 Grove Shaper — 5/3/6 Druid. After you cast a Nature spell, summon
/// a 2/2 Treant with "Deathrattle: Get a copy of that spell."
/// (simplified: the Nature spell school is not modeled — the trigger fires
/// on any friendly spell; the treant's deathrattle cannot remember which
/// spell was cast, so it adds a random spell to hand instead, §14.3.)
pub const GROVE_SHAPER: CardDef = CardDef {
    id: "EDR_271",
    name: "Grove Shaper",
    card_type: CardType::Minion,
    cost: 5,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: Some(CardEffect::SummonTreantCopyingSpell),
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_272 Evergreen Stag — 6/6/7 Druid Beast. Elusive, Lifesteal, Taunt.
/// (Lifesteal lands via `apply_card_keywords`.)
pub const EVERGREEN_STAG: CardDef = CardDef {
    id: "EDR_272",
    name: "Evergreen Stag",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: true,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_416 Shepherd's Crook — 3/3/2 Hunter weapon. After your hero attacks,
/// summon a 3/3 Sheep that's Dormant for 2 turns. (simplified: Dormant is
/// not modeled — the Sheep is a plain 3/3 that never wakes, per the Dreadseed
/// precedent, §14.3. The HeroAttacked weapon trigger lands in
/// `apply_card_keywords`.)
pub const SHEPHERDS_CROOK: CardDef = CardDef {
    id: "EDR_416",
    name: "Shepherd's Crook",
    card_type: CardType::Weapon,
    cost: 3,
    attack: 3,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_453 Briarspawn Drake — 10/12/7 Neutral Dragon. At the end of your
/// turn, attack a random enemy minion (excess damage hits the enemy hero).
/// (The attack is modeled as direct damage; excess damage carries over to
/// the enemy hero, matching the card text.)
pub const BRIARSPAWN_DRAKE: CardDef = CardDef {
    id: "EDR_453",
    name: "Briarspawn Drake",
    card_type: CardType::Minion,
    cost: 10,
    attack: 12,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::AttackRandomEnemyMinionExcess),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_454 Clutch of Corruption — 2-mana Warrior Location (2 durability).
/// Choose a friendly Dragon. Summon a 0/2 Egg that hatches into a copy of
/// it. (simplified: the egg cannot remember which Dragon was chosen — its
/// deathrattle hatches a copy of a random friendly Dragon, §14.3.)
pub const CLUTCH_OF_CORRUPTION: CardDef = CardDef {
    id: "EDR_454",
    name: "Clutch of Corruption",
    card_type: CardType::Location,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 2,
    battlecry: Some(CardEffect::SummonEggHatchingDragon),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_455 Succumb to Madness — 3-mana Warrior spell. Discover a friendly
/// Dragon that died this game. Resummon it. (Discover simplified to random;
/// the death record reads the graveyard zone, like Calia Menethil.)
pub const SUCCUMB_TO_MADNESS: CardDef = CardDef {
    id: "EDR_455",
    name: "Succumb to Madness",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ResurrectRandomFallenDragon),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_457 Brood Keeper — 2/2/3 Warrior. Battlecry: If you're holding a
/// Dragon, equip a 2/2 Sword.
pub const BROOD_KEEPER: CardDef = CardDef {
    id: "EDR_457",
    name: "Brood Keeper",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::EquipSwordIfHoldingDragon),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_459 Afflicted Devastator — 4/6/6 Warrior Dragon. Battlecry: Deal 3
/// damage to all other friendly minions. Deathrattle: Deal 3 damage to all
/// enemy minions.
pub const AFFLICTED_DEVASTATOR: CardDef = CardDef {
    id: "EDR_459",
    name: "Afflicted Devastator",
    card_type: CardType::Minion,
    cost: 4,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::DamageAllOtherFriendlyMinions { damage: 3 }),
    deathrattle: Some(CardEffect::DealDamage {
        amount: 3,
        target: EffectTarget::AllEnemyMinions,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_460 Wish of the New Moon — 3-mana Priest spell. Deal 6 damage to a
/// minion. (Cast 3 spells to gain Lifesteal.) (simplified: the per-card
/// New Moon counter is approximated by the player's total spells cast this
/// game, §14.3.)
pub const WISH_OF_THE_NEW_MOON: CardDef = CardDef {
    id: "EDR_460",
    name: "Wish of the New Moon",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageMinionWithMoonLifesteal { amount: 6 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_461 Ritual of the New Moon — 5-mana Priest spell. Summon two random
/// 3-Cost minions. (Cast 3 spells to summon 6-Cost minions instead.)
/// (simplified: the per-card New Moon counter is approximated by the
/// player's total spells cast this game, §14.3.)
pub const RITUAL_OF_THE_NEW_MOON: CardDef = CardDef {
    id: "EDR_461",
    name: "Ritual of the New Moon",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::SummonTwoRandomCostMinions {
        base_cost: 3,
        upgraded_cost: 6,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_462 Selenic Drake — 4/3/6 Priest Dragon. Elusive. At the end of your
/// turn, get a random Dragon.
pub const SELENIC_DRAKE: CardDef = CardDef {
    id: "EDR_462",
    name: "Selenic Drake",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: true,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Dragon,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_468 Eggbasher — 4/3/5 Warrior. Battlecry: Deal 1 damage to a minion
/// and give it +4 Attack.
pub const EGGBASHER: CardDef = CardDef {
    id: "EDR_468",
    name: "Eggbasher",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::DamageAndGainAttack {
        damage: 1,
        attack_bonus: 4,
        target: EffectTarget::AnyMinion,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_469 Slumbering Sprite — 1/3/3 Neutral. Starts Dormant. After you use
/// your Hero Power, this awakens. (simplified: Dormant is not modeled — the
/// Sprite is a plain 3/3 that never wakes, per the Dreadseed precedent;
/// there is no hero-power-use trigger event, §14.3.)
pub const SLUMBERING_SPRITE: CardDef = CardDef {
    id: "EDR_469",
    name: "Slumbering Sprite",
    card_type: CardType::Minion,
    cost: 1,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_470 Barkshield Sentinel — 2/2/2 Neutral. Taunt. After you use your
/// Hero Power, gain +2 Health. (simplified: there is no hero-power-use
/// trigger event — the buff fires at the end of the turn, but only when the
/// hero power was used that turn, §14.3.)
pub const BARKSHELD_SENTINEL: CardDef = CardDef {
    id: "EDR_470",
    name: "Barkshield Sentinel",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainHealthIfHeroPowerUsed { amount: 2 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_472 Weaver of the Cycle — 3/3/3 Priest. Battlecry: If you're holding
/// a spell that costs (5) or more, deal 3 damage.
pub const WEAVER_OF_THE_CYCLE: CardDef = CardDef {
    id: "EDR_472",
    name: "Weaver of the Cycle",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::DamageIfHoldingSpell5Plus { amount: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_476 Moonwell — 6-mana Priest spell. Deal 4 damage to all enemy
/// characters. Restore 4 Health to all friendly characters.
pub const MOONWELL: CardDef = CardDef {
    id: "EDR_476",
    name: "Moonwell",
    card_type: CardType::Spell,
    cost: 6,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AoeDamageAndHealFriendly { damage: 4, heal: 4 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_477 Glowroot Lure — 6/6/6 Shaman. Taunt. Costs (1) less for each time
/// you used your Hero Power this game. (The cost reduction composes in
/// `engine::cost::play_cost`, keyed on the card id — see the Dread Corsair
/// precedent. The `Player::hero_power_uses` counter is the M1-W4a hero-power
/// facility.)
pub const GLOWROOT_LURE: CardDef = CardDef {
    id: "EDR_477",
    name: "Glowroot Lure",
    card_type: CardType::Minion,
    cost: 6,
    attack: 6,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_481 Mythical Runebear — 4/3/4 Hunter Beast. Taunt. Battlecry: If this
/// has 4 or more Attack, summon a copy of this.
pub const MYTHICAL_RUNEBEAR: CardDef = CardDef {
    id: "EDR_481",
    name: "Mythical Runebear",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonCopyIfAttackGE { attack: 4 }),
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_482 Rotten Apple — 2-mana Warlock spell. Restore 12 Health to your
/// hero. For the next 2 turns, deal 3 damage to your hero. (simplified: the
/// damage ticks at the END of each of the next 2 of your turns, the
/// `Player::self_damage_pending` timer, §14.3.)
pub const ROTTEN_APPLE: CardDef = CardDef {
    id: "EDR_482",
    name: "Rotten Apple",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealthAndPendingSelfDamage {
        heal: 12,
        damage: 3,
        turns: 2,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_483 Fractured Power — 2-mana Warlock spell. Destroy one of your Mana
/// Crystals. In 2 turns, gain two. (simplified: the gain lands at the END of
/// the 2nd of your turns, the `Player::crystal_gain_pending` timer, §14.3.)
pub const FRACTURED_POWER: CardDef = CardDef {
    id: "EDR_483",
    name: "Fractured Power",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyCrystalGainCrystalsLater { gain: 2, turns: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_484 Scavenging Flytrap — 7/2/7 Neutral. After a minion dies, gain its
/// Attack. (simplified: the minion's enchantments are wiped when it moves to
/// the graveyard, so the Flytrap gains the dead minion's base Attack, §14.3.
/// The any-minion-died trigger lands in `apply_card_keywords`, like
/// Flesheathing Ghoul.)
pub const SCAVENGING_FLYTRAP: CardDef = CardDef {
    id: "EDR_484",
    name: "Scavenging Flytrap",
    card_type: CardType::Minion,
    cost: 7,
    attack: 2,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_485 Rotheart Dryad — 1/1/1 Warlock. Deathrattle: Draw a minion that
/// costs (7) or more.
pub const ROTHEART_DRYAD: CardDef = CardDef {
    id: "EDR_485",
    name: "Rotheart Dryad",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawMinionCostGE { cost: 7 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_486 Scorching Observer — 9/7/9 Neutral Demon. Rush, Lifesteal.
/// (Both keywords land via `apply_card_keywords`.)
pub const SCORCHING_OBSERVER: CardDef = CardDef {
    id: "EDR_486",
    name: "Scorching Observer",
    card_type: CardType::Minion,
    cost: 9,
    attack: 7,
    health: 9,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_491 Archdruid of Thorns — 2/3/2 Warlock. Battlecry: Gain the
/// Deathrattles of your minions that died this turn. (simplified: the engine
/// stores one Deathrattle per entity — the Archdruid gains the deathrattle
/// of the most recently died friendly minion this turn, §14.3.)
pub const ARCHDRUID_OF_THORNS: CardDef = CardDef {
    id: "EDR_491",
    name: "Archdruid of Thorns",
    card_type: CardType::Minion,
    cost: 2,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: Some(CardEffect::GainDeathrattleOfDiedThisTurn),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_492 Mother Duck — 4/2/3 Neutral Beast. Battlecry: Summon three 1/1
/// Ducklings with Rush. (The Duckling's Rush lands via
/// `apply_card_keywords`.)
pub const MOTHER_DUCK: CardDef = CardDef {
    id: "EDR_492",
    name: "Mother Duck",
    card_type: CardType::Minion,
    cost: 4,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::SummonMultipleMinions {
        card_id: "EDR_492t",
        count: 3,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_494 Hungering Ancient — 8/6/7 Warlock. At the end of your turn, eat a
/// minion in your deck and gain its stats. Deathrattle: Add them to your
/// hand. (simplified: the eaten minion's identity cannot be stored per
/// instance, so the deathrattle adds a random minion from the deck to hand
/// instead, §14.3.)
pub const HUNGERING_ANCIENT: CardDef = CardDef {
    id: "EDR_494",
    name: "Hungering Ancient",
    card_type: CardType::Minion,
    cost: 8,
    attack: 6,
    health: 7,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::AddRandomDeckMinionToHand),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::EatDeckMinionGainStats),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_495 Twisted Treant — 2/2/2 Neutral. Deathrattle: Give a random minion
/// in each player's hand -2 Attack. (The debuff enchantment persists from
/// hand into play, so the -2 Attack applies when the card is played.)
pub const TWISTED_TREANT: CardDef = CardDef {
    id: "EDR_495",
    name: "Twisted Treant",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DebuffRandomHandMinionBoth {
        attack_reduction: 2,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_520 Forbidden Shrine — 1-mana Mage Location (3 durability). Spend all
/// your Mana. Cast a random spell that costs that much. (simplified: "cast"
/// is a direct effect resolution — no spell entity or SpellCast event is
/// produced, §14.3.)
pub const FORBIDDEN_SHRINE: CardDef = CardDef {
    id: "EDR_520",
    name: "Forbidden Shrine",
    card_type: CardType::Location,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 3,
    battlecry: Some(CardEffect::SpendAllManaCastRandomSpell),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_521 Tricky Satyr — 3/4/3 Rogue Demon. Battlecry: Get a copy of the
/// lowest Cost card in your opponent's hand. (Reads the opponent's hand —
/// registered in `POOL_OPEN_CARDS` like Nightmare Fuel.)
pub const TRICKY_SATYR: CardDef = CardDef {
    id: "EDR_521",
    name: "Tricky Satyr",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::CopyLowestCostEnemyHandCard),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_522 Mimicry — 1-mana Rogue spell. Your opponent draws 2 cards. You
/// get copies of them. (Reads the opponent's hand — registered in
/// `POOL_OPEN_CARDS`.)
pub const MIMICRY: CardDef = CardDef {
    id: "EDR_522",
    name: "Mimicry",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::OpponentDrawsTwoAndCopies),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_523 Web of Deception — 2-mana Rogue spell. Return a friendly minion
/// to your hand to summon a 4/4 Spider with Stealth. (The returned minion's
/// enchantments are wiped by the bounce, per `World::move_to_zone`.)
pub const WEB_OF_DECEPTION: CardDef = CardDef {
    id: "EDR_523",
    name: "Web of Deception",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::ReturnFriendlyMinionSummonSpider),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_524 Shadowcloaked Assailant — 4/3/5 Rogue Demon. Battlecry: If you're
/// holding one of the same cards as your opponent, shuffle theirs into their
/// deck. (simplified: when several enemy cards match, one random matching
/// card is shuffled, §14.3. Reads the opponent's hand — registered in
/// `POOL_OPEN_CARDS`.)
pub const SHADOWCLOAKED_ASSAILANT: CardDef = CardDef {
    id: "EDR_524",
    name: "Shadowcloaked Assailant",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::ShuffleMatchingEnemyHandCardIntoDeck),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_529 Plucky Podling — 1/1/2 Shaman. If this would transform into a
/// minion, it transforms into one that costs (2) more. (simplified: there is
/// no transform interception in the engine, so the clause is unmodeled — the
/// Podling is a plain 1/2, §14.3.)
pub const PLUCKY_PODLING: CardDef = CardDef {
    id: "EDR_529",
    name: "Plucky Podling",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_530 Daydreaming Pixie — 2/0/4 Neutral. At the end of your turn, get a
/// random Nature spell. (simplified: the Nature spell school is not modeled —
/// the pool is any spell, §14.3.)
pub const DAYDREAMING_PIXIE: CardDef = CardDef {
    id: "EDR_530",
    name: "Daydreaming Pixie",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Spell,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_531 Siphoning Growth — 1-mana Warrior spell. Destroy a friendly
/// minion to gain 8 Armor.
pub const SIPHONING_GROWTH: CardDef = CardDef {
    id: "EDR_531",
    name: "Siphoning Growth",
    card_type: CardType::Spell,
    cost: 1,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyFriendlyMinionGainArmor { armor: 8 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_540 Twisted Webweaver — 2/2/3 Rogue Beast. Whenever you play another
/// minion you've already played, draw a card. (The `Player::played_minion_ids`
/// log is the M1-W4a played-minion facility; the CardPlayed trigger lands in
/// `apply_card_keywords`.)
pub const TWISTED_WEBWEAVER: CardDef = CardDef {
    id: "EDR_540",
    name: "Twisted Webweaver",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_571 Fae Trickster — 3/2/4 Neutral Dragon. Deathrattle: Draw a spell
/// that costs (5) or more.
pub const FAE_TRICKSTER: CardDef = CardDef {
    id: "EDR_571",
    name: "Fae Trickster",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawSpellCostGE { cost: 5 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_572 Tormented Dreadwing — 5/5/5 Neutral Dragon. Deathrattle: Draw 2
/// Dragons. Reduce their Costs by (1).
pub const TORMENTED_DREADWING: CardDef = CardDef {
    id: "EDR_572",
    name: "Tormented Dreadwing",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::DrawDragonsReduced {
        count: 2,
        reduction: 1,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_598 Dream Rager — 3/5/1 Neutral. Elusive.
pub const DREAM_RAGER: CardDef = CardDef {
    id: "EDR_598",
    name: "Dream Rager",
    card_type: CardType::Minion,
    cost: 3,
    attack: 5,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: true,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_780 Bloodthistle Illusionist — 3/2/4 Neutral Demon. Battlecry: Summon
/// a copy of this. One secretly dies when it takes damage. (simplified: the
/// shared-secret-death clause is unmodeled — the copy is a plain copy, §14.3.)
pub const BLOODTHISTLE_ILLUSIONIST: CardDef = CardDef {
    id: "EDR_780",
    name: "Bloodthistle Illusionist",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonCopyOfSelf),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_781 Harbinger of the Blighted — 3/2/3 Rogue. Whenever this enters
/// your hand from the battlefield, summon two random 2-Cost minions.
/// (simplified: there is no zone-change trigger event, so the clause is
/// unmodeled — the Harbinger is a plain 2/3, §14.3.)
pub const HARBINGER_OF_THE_BLIGHTED: CardDef = CardDef {
    id: "EDR_781",
    name: "Harbinger of the Blighted",
    card_type: CardType::Minion,
    cost: 3,
    attack: 2,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_804 Divination — 2-mana Mage spell. Destroy a friendly Wisp to draw 3
/// cards. (The engine's Wisp is the EDR_851t 1/1 token — the only Wisp in
/// the card set.)
pub const DIVINATION: CardDef = CardDef {
    id: "EDR_804",
    name: "Divination",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DestroyFriendlyWispDraw { count: 3 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_810 Hideous Husk — 6/3/5 DK Undead. Your Leeches steal 1 more Health
/// from their victims. Battlecry: Summon two 0/2 Leeches. (simplified: the
/// leech-steal aura is unmodeled — the Leeches are plain 0/2 tokens, §14.3.)
pub const HIDEOUS_HUSK: CardDef = CardDef {
    id: "EDR_810",
    name: "Hideous Husk",
    card_type: CardType::Minion,
    cost: 6,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: Some(CardEffect::SummonMultipleMinions {
        card_id: "EDR_810t",
        count: 2,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_812 Grotesque Runeblade — 2/2/2 DK weapon. Battlecry: If the last card
/// you played had an Unholy rune, gain +1 Attack. Repeat for Blood and +1
/// Durability. (simplified: rune tracking is unmodeled — the Runeblade is a
/// plain 2/2 weapon, §14.3.)
pub const GROTESQUE_RUNEBLADE: CardDef = CardDef {
    id: "EDR_812",
    name: "Grotesque Runeblade",
    card_type: CardType::Weapon,
    cost: 2,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_814 Infested Breath — 2-mana DK spell. Deal 2 damage. Summon a 0/2
/// Leech.
pub const INFESTED_BREATH: CardDef = CardDef {
    id: "EDR_814",
    name: "Infested Breath",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageAndSummon {
        damage: 2,
        target: EffectTarget::AnyCharacter,
        card_id: "EDR_810t",
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_815 Corpse Flower — 3/0/5 DK Undead. After your opponent summons a
/// minion, spend 2 Corpses to deal 3 damage to it. (simplified: there is no
/// enemy-summons trigger event, so the clause is unmodeled — the Corpse
/// Flower is a plain 0/5, §14.3.)
pub const CORPSE_FLOWER: CardDef = CardDef {
    id: "EDR_815",
    name: "Corpse Flower",
    card_type: CardType::Minion,
    cost: 3,
    attack: 0,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Undead),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_816 Monstrous Mosquito — 1/1/2 DK Beast. At the end of your turn,
/// give your other minions +1 Attack.
pub const MONSTROUS_MOSQUITO: CardDef = CardDef {
    id: "EDR_816",
    name: "Monstrous Mosquito",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainStats {
        attack: 1,
        health: 0,
        target: EffectTarget::OtherFriendlyMinion,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_817 Sanguine Infestation — 5-mana DK spell. Draw 2 cards. Summon two
/// 0/2 Leeches.
pub const SANGUINE_INFESTATION: CardDef = CardDef {
    id: "EDR_817",
    name: "Sanguine Infestation",
    card_type: CardType::Spell,
    cost: 5,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawAndSummonLeeches { draw: 2 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_840 Grim Harvest — 2-mana DH spell. Draw a card. Summon a random
/// Dormant Dreadseed. (simplified: Dormant is not modeled — the Dreadseed
/// EDR_820t is the W3 can't-attack token, §14.3.)
pub const GRIM_HARVEST: CardDef = CardDef {
    id: "EDR_840",
    name: "Grim Harvest",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DrawAndSummonDreadseed { draw: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_841 Dreadsoul Corrupter — 4/4/4 DH. Battlecry and Deathrattle: Summon
/// a random Dormant Dreadseed. (simplified: Dormant is not modeled — the
/// Dreadseed EDR_820t is the W3 can't-attack token, §14.3.)
pub const DREADSOUL_CORRUPTER: CardDef = CardDef {
    id: "EDR_841",
    name: "Dreadsoul Corrupter",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: Some(CardEffect::SummonMinion {
        card_id: "EDR_820t",
    }),
    deathrattle: Some(CardEffect::SummonMinion {
        card_id: "EDR_820t",
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_842 Defiled Spear — 4/2/3 DH weapon. After your hero attacks an enemy
/// minion, deal your hero's Attack damage to another random enemy (the
/// splashed target excludes the minion that was just attacked — the
/// AttackedMinion weapon trigger lands in `apply_card_keywords`; the splash
/// is direct damage rather than an attack, §14.3).
pub const DEFILED_SPEAR: CardDef = CardDef {
    id: "EDR_842",
    name: "Defiled Spear",
    card_type: CardType::Weapon,
    cost: 4,
    attack: 2,
    health: 0,
    durability: 3,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_847 Dreambound Disciple — 3/3/3 Druid. Battlecry and Deathrattle:
/// Your next Hero Power costs (0). (The `Player::next_hero_power_free`
/// flag is the M1-W4a hero-power facility; it composes in
/// `engine::cost::play_cost` and is consumed at the hero-power activation.)
pub const DREAMBOUND_DISCIPLE: CardDef = CardDef {
    id: "EDR_847",
    name: "Dreambound Disciple",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: Some(CardEffect::NextHeroPowerCostsZero),
    deathrattle: Some(CardEffect::NextHeroPowerCostsZero),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_848 Photosynthesis — 3-mana Druid spell. Restore 6 Health. Get 3
/// random Druid spells.
pub const PHOTOSYNTHESIS: CardDef = CardDef {
    id: "EDR_848",
    name: "Photosynthesis",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::RestoreHealthAndGetDruidSpells {
        amount: 6,
        count: 3,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_849 Dreambound Raptor — 1/2/1 Neutral Beast. After you play a minion,
/// give it a random Bonus Effect. (simplified: the official Bonus Effect
/// pool is approximated by a fixed keyword pool — Taunt / Divine Shield /
/// Poisonous / Windfury / Elusive / Stealth; the CardPlayed trigger lands in
/// `apply_card_keywords`, §14.3.)
pub const DREAMBOUND_RAPTOR: CardDef = CardDef {
    id: "EDR_849",
    name: "Dreambound Raptor",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_861 Tranquil Treant — 2/2/2 Neutral. Deathrattle: Both players gain an
/// empty Mana Crystal.
pub const TRANQUIL_TREANT: CardDef = CardDef {
    id: "EDR_861",
    name: "Tranquil Treant",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::GainManaCrystalBoth { count: 1 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_873 Envoy of the Glade — 4/3/6 Neutral. Battlecry: Transform all
/// Neutral cards in your deck into random Druid ones. (Neutral = not a class
/// card; the replacement pool is the Druid class list in the active window.)
pub const ENVOY_OF_THE_GLADE: CardDef = CardDef {
    id: "EDR_873",
    name: "Envoy of the Glade",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: Some(CardEffect::TransformNeutralDeckToDruid),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_874 Stellar Balance — 2-mana Mage spell. Get a Moonfire and a
/// Starfire. Give them Spell Damage +1. (The spell entity's own Spell
/// Damage applies to itself when cast — `total_spell_damage` counts the
/// spell entity while it is in play.)
pub const STELLAR_BALANCE: CardDef = CardDef {
    id: "EDR_874",
    name: "Stellar Balance",
    card_type: CardType::Spell,
    cost: 2,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::AddMoonfireAndStarfireWithSpellDamage),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_889 Petal Peddler — 2/1/4 Neutral Dragon. At the end of your turn,
/// give another random friendly Dragon +1/+1.
pub const PETAL_PEDDLER: CardDef = CardDef {
    id: "EDR_889",
    name: "Petal Peddler",
    card_type: CardType::Minion,
    cost: 2,
    attack: 1,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::BuffAnotherRandomFriendlyDragon {
        attack: 1,
        health: 1,
    }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_890 Nightmare Dragonkin — 3/4/2 DH Dragon. Deathrattle: Reduce the
/// Cost of the right-most card in your hand by (2).
pub const NIGHTMARE_DRAGONKIN: CardDef = CardDef {
    id: "EDR_890",
    name: "Nightmare Dragonkin",
    card_type: CardType::Minion,
    cost: 3,
    attack: 4,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::ReduceRightmostHandCardCost { reduction: 2 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_891 Ravenous Felhunter — 5/5/3 DH Demon. Deathrattle: Resurrect a
/// friendly Deathrattle minion that costs (4) or less. Summon a copy of it.
/// (The death record reads the graveyard zone, like Calia Menethil.)
pub const RAVENOUS_FELHUNTER: CardDef = CardDef {
    id: "EDR_891",
    name: "Ravenous Felhunter",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::ResurrectDeathrattleMinionCostLE { cost: 4 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_892 Ferocious Felbat — 7/7/5 DH Demon. Deathrattle: Resurrect a
/// different friendly Deathrattle minion that costs (5) or more. Summon a
/// copy of it. ("Different" — the Felbat itself is excluded from the
/// graveyard scan.)
pub const FEROCIOUS_FELBAT: CardDef = CardDef {
    id: "EDR_892",
    name: "Ferocious Felbat",
    card_type: CardType::Minion,
    cost: 7,
    attack: 7,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::ResurrectDeathrattleMinionCostGE { cost: 5 }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Demon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_940 Merry Moonkin — 4/3/6 Mage. At the end of your turn, gain 1
/// Armor. (Improved by Wisps you control!) (The armor gain is 1 plus the
/// number of friendly Wisps — the engine's Wisp is the EDR_851t token.)
pub const MERRY_MOONKIN: CardDef = CardDef {
    id: "EDR_940",
    name: "Merry Moonkin",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 6,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GainArmorPerWisp { base: 1 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_941 Starsurge — 3-mana Mage spell. Deal 1 damage to a minion.
/// (Improved by each friendly minion that died this game.) (The fallen count
/// reads the owner's graveyard minions — the death record facility.)
pub const STAR_SURGE: CardDef = CardDef {
    id: "EDR_941",
    name: "Starsurge",
    card_type: CardType::Spell,
    cost: 3,
    attack: 0,
    health: 0,
    durability: 0,
    battlecry: Some(CardEffect::DamageMinionScaledByFallen { base: 1 }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_942 Curious Cumulus — 4/3/5 Neutral Elemental. At the end of your
/// turn, give your hero Divine Shield.
pub const CURIOUS_CUMULUS: CardDef = CardDef {
    id: "EDR_942",
    name: "Curious Cumulus",
    card_type: CardType::Minion,
    cost: 4,
    attack: 3,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Elemental),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::GrantHeroDivineShield),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_971 Critter Caretaker — 1/2/2 Neutral. At the end of your turn,
/// restore 3 Health to both heroes.
pub const CRITTER_CARETAKER: CardDef = CardDef {
    id: "EDR_971",
    name: "Critter Caretaker",
    card_type: CardType::Minion,
    cost: 1,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: Some(CardEffect::RestoreBothHeroes { amount: 3 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_978 Meadowstrider — 8/6/11 Neutral Beast. Taunt. Deathrattle: Put a
/// Meadowstrider on the bottom of your deck. It costs (1). (The deck's
/// bottom is the end of the deck zone order — the draw order's far end.)
pub const MEADOWSTRIDER: CardDef = CardDef {
    id: "EDR_978",
    name: "Meadowstrider",
    card_type: CardType::Minion,
    cost: 8,
    attack: 6,
    health: 11,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::AddSelfToDeckBottomCost { cost: 1 }),
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_979 Ancient of Yore — 5/5/5 Neutral. Dormant for 2 turns. While
/// Dormant, gain 3 Armor and draw a card at the end of your turn.
/// (simplified: Dormant is not modeled — the Ancient never wakes, per the
/// Dreadseed precedent; the end-of-turn effect keeps running while it is in
/// play, §14.3.)
pub const ANCIENT_OF_YORE: CardDef = CardDef {
    id: "EDR_979",
    name: "Ancient of Yore",
    card_type: CardType::Minion,
    cost: 5,
    attack: 5,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    end_turn_effect: Some(CardEffect::GainArmorAndDraw { armor: 3, draw: 1 }),
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_999 Gnawing Greenfin — 1/1/1 Neutral Murloc. Battlecry: Get a random
/// Murloc. (The Murloc pool is a new `RandomPool` — filtered over the active
/// window, like the Beast/Dragon pools.)
pub const GNAWING_GREENFIN: CardDef = CardDef {
    id: "EDR_999",
    name: "Gnawing Greenfin",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Murloc,
    }),
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Murloc),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

// ---------------------------------------------------------------------------
// M1-W4a tokens (handwritten only — no generated baselines)
// ---------------------------------------------------------------------------

/// EDR_260t Dragon — the 4/5 Taunt Dragon Illusory Greenwing shuffles into
/// the deck. (4/5 Dragon with Taunt, per the card text.)
pub const GREENWING_DRAGON: CardDef = CardDef {
    id: "EDR_260t",
    name: "Dragon",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 5,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: true,
    stealth: false,
    elusive: false,
    race: Some(Race::Dragon),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_262t Wolf — the 3/2 Wolf with Rush that Spirit Bond summons when its
/// target dies. (Rush lands via `apply_card_keywords`.)
pub const SPIRIT_BOND_WOLF: CardDef = CardDef {
    id: "EDR_262t",
    name: "Wolf",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_271t Treant — the 2/2 Treant Grove Shaper summons. Deathrattle: Get a
/// random spell. (simplified: the real deathrattle copies the triggering
/// spell, which cannot be remembered per instance — §14.3.)
pub const GROVE_SHAPER_TREANT: CardDef = CardDef {
    id: "EDR_271t",
    name: "Treant",
    card_type: CardType::Minion,
    cost: 2,
    attack: 2,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::AddRandomCardToHand {
        pool: RandomPool::Spell,
    }),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_416t Sheep — the 3/3 Sheep Shepherd's Crook summons. (simplified:
/// Dormant is not modeled — the Sheep is a 3/3 that never wakes, per the
/// Dreadseed precedent, §14.3.)
pub const SHEPHERDS_CROOK_SHEEP: CardDef = CardDef {
    id: "EDR_416t",
    name: "Sheep",
    card_type: CardType::Minion,
    cost: 3,
    attack: 3,
    health: 3,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: true,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_454t Egg — the 0/2 Egg Clutch of Corruption summons. Deathrattle:
/// Hatch a copy of a random friendly Dragon. (simplified: the egg cannot
/// remember which Dragon was chosen — §14.3.)
pub const CLUTCH_OF_CORRUPTION_EGG: CardDef = CardDef {
    id: "EDR_454t",
    name: "Egg",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: Some(CardEffect::SummonCopyOfRandomFriendlyDragon),
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_457t Sword — the 2/2 Sword Brood Keeper equips while holding a
/// Dragon.
pub const BROOD_KEEPER_SWORD: CardDef = CardDef {
    id: "EDR_457t",
    name: "Sword",
    card_type: CardType::Weapon,
    cost: 2,
    attack: 2,
    health: 0,
    durability: 2,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_492t Duckling — the 1/1 Duckling with Rush Mother Duck summons.
/// (Rush lands via `apply_card_keywords`.)
pub const DUCKLING: CardDef = CardDef {
    id: "EDR_492t",
    name: "Duckling",
    card_type: CardType::Minion,
    cost: 1,
    attack: 1,
    health: 1,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_523t Spider — the 4/4 Spider with Stealth Web of Deception summons.
pub const WEB_OF_DECEPTION_SPIDER: CardDef = CardDef {
    id: "EDR_523t",
    name: "Spider",
    card_type: CardType::Minion,
    cost: 4,
    attack: 4,
    health: 4,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: true,
    elusive: false,
    race: Some(Race::Beast),
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};

/// EDR_810t Leech — the 0/2 Leech the Death-Knight leech cards summon.
pub const LEECH: CardDef = CardDef {
    id: "EDR_810t",
    name: "Leech",
    card_type: CardType::Minion,
    cost: 2,
    attack: 0,
    health: 2,
    durability: 0,
    battlecry: None,
    deathrattle: None,
    taunt: false,
    stealth: false,
    elusive: false,
    race: None,
    hero_power: None,
    aura: None,
    secret: None,
    divine_shield: false,
    windfury: false,
    charge: false,
    spell_damage: 0,
    cant_attack: false,
    end_turn_effect: None,
    start_turn_effect: None,
    spell_effect: None,
    spell_trigger: None,
    death_trigger: None,
    summon_trigger: None,
    choose_one_effect: None,
    combo_effect: None,
    attack_equals_health: false,
};
