//! Card constants generated by build.rs (source: `cards/cards.json`).
//!
//! Generated code covers static stats and keywords only; effects (battlecry/
//! deathrattle/aura/secret) stay hand-written.
//! Consistency between generated and hand-written consts is verified by tests in `cards/mod.rs`.

#![allow(missing_docs)]
#![allow(non_upper_case_globals)]

use crate::cards::def::{CardDef, CardSet};
use crate::core::component::{CardType, Race};

include!(concat!(env!("OUT_DIR"), "/cards_generated.rs"));
