//! Card lists — card collections grouped by class, plus ALL_CARDS.
#![allow(missing_docs)]

use crate::cards::def::CardDef;

// Import card constants directly from each module (avoiding circular references through def.rs)
use super::classic_druid::*;
use super::classic_hunter::*;
use super::classic_legendary::*;
use super::classic_mage::*;
use super::classic_neutral::*; // includes THE_COIN (GAME_005)
use super::classic_paladin::*;
use super::classic_priest::*;
use super::classic_rogue::*;
use super::classic_shaman::*;
use super::classic_warlock::*;
use super::classic_warrior::*;
use super::core_w1::*;
// ============================================================
// Card lists
// ============================================================

// ============================================================
// Core Set W1 (core-set-roadmap W1) — attack-pipeline primitives.
// Class affiliations: Demon Hunter / Death Knight cards go to their own
// groups (new in W1) so the pilfer-style other-class pools include them.
// ============================================================

/// Core Set W1 — Demon Hunter class cards.
pub const DEMON_HUNTER_W1: &[CardDef] = &[EYE_BEAM, ALDRACHI_WARBLADES, MYTHICAL_TERROR];

/// Core Set W1 — Death Knight class cards.
pub const DEATH_KNIGHT_W1: &[CardDef] = &[MALIGNANT_HORROR];

// Classic set grouped by class
pub const NEUTRAL_CLASSIC: &[CardDef] = &[
    BLOODFEN_RAPTOR,
    BLUEGILL_WARRIOR,
    ACIDIC_SWAMP_OOZE,
    IRONBEAK_OWL,
    KOBOLD_GEOMANCER,
    MURLOC_TIDEHUNTER,
    MURLOC_SCOUT,
    HARVEST_GOLEM,
    DAMAGED_GOLEM,
    SENJIN_SHIELDMASTA,
    DARK_IRON_DWARF,
    DEFENDER_OF_ARGUS,
    GNOMISH_INVENTOR,
    SPELLBREAKER,
    AZURE_DRAKE,
    SUNWALKER,
    ARGENT_COMMANDER,
    WINDFURY_HARPY,
    WOLFRIDER,
    AMANI_BERSERKER,
    FAERIE_DRAGON,
    ABUSIVE_SERGEANT,
    YOUTHFUL_BREWMASTER,
    MAD_BOMBER,
    ACOLYTE_OF_PAIN,
    EARTHEN_RING_FARSEER,
    INJURED_BLADEMASTER,
    IMP_MASTER,
    RAGING_WORGEN,
    SCARLET_CRUSADER,
    THRALLMAR_FARSEER,
    ANCIENT_BREWMASTER,
    CULT_MASTER,
    OGRE_MAGI,
    SILVERMOON_GUARDIAN,
    VIOLET_TEACHER,
    MOGUSHAN_WARDEN,
    ABOMINATION,
    FROSTWOLF_WARLORD,
    GADGETZAN_AUCTIONEER,
    SILVER_HAND_KNIGHT,
    SQUIRE,
    FROST_ELEMENTAL,
    LORD_OF_THE_ARENA,
    RECKLESS_ROCKETEER,
    ARCHMAGE,
    CORE_HOUND,
    SEA_GIANT,
    MOLTEN_GIANT,
    MOUNTAIN_GIANT,
    GRIMSCALE_ORACLE,
    MURLOC_RAIDER,
    STONETUSK_BOAR,
    VOODOO_DOCTOR,
    FROSTWOLF_GRUNT,
    DALARAN_MAGE,
    IRONFORGE_RIFLEMAN,
    IRONFUR_GRIZZLY,
    MAGMA_RAGER,
    RAZORFEN_HUNTER,
    BOAR,
    SILVERBACK_PATRIARCH,
    DRAGONLING_MECHANIC,
    MECHANICAL_DRAGONLING,
    OASIS_SNAPJAW,
    STORMWIND_KNIGHT,
    BOOTY_BAY_BODYGUARD,
    DARKSCALE_HEALER,
    NIGHTBLADE,
    STORMPIKE_COMMANDO,
    ARGENT_SQUIRE,
    LEPER_GNOME,
    SHIELDBEARER,
    YOUNG_DRAGONHAWK,
    FEN_CREEPER,
    PRIESTESS_OF_ELUNE,
    SOUTHSHORE_CAPTAIN,
    // Incomplete additions
    COLDLIGHT_SEER,
    MURLOC_WARLEADER,
    // Simplified additions
    GURUBASHI_BERSERKER,
    SOUTHSHORE_DECKHAND,
    WORGEN_INFILTRATOR,
    BLOODSAIL_RAIDER,
    JUNGLE_PANTHER,
    TAUREN_WARRIOR,
    FLESHEATING_GHOUL,
    DREAD_CORSAIR,
    VENTURE_CO_MERCENARY,
    SPITEFUL_SMITH,
    ANGRY_CHICKEN,
    BLOODSAIL_CORSAIR,
    LIGHTWARDEN,
    MURLOC_TIDECALLER,
    SECRETKEEPER,
    ANCIENT_WATCHER,
    CRAZED_ALCHEMIST,
    KNIFE_JUGGLER,
    MANA_ADDICT,
    SUNFURY_PROTECTOR,
    WILD_PYROMANCER,
    ALARM_O_BOT,
    ARCANE_GOLEM,
    DEMOLISHER,
    EMPEROR_COBRA,
    QUESTING_ADVENTURER,
    ANCIENT_MAGE,
    TWILIGHT_DRAKE,
    STAMPEDING_KODO,
    HUNGRY_CRAB,
    DOOMSAYER,
    BLOOD_KNIGHT,
    BIG_GAME_HUNTER,
    YOUNG_PRIESTESS,
    MANA_WRAITH,
    MASTER_SWORDSMITH,
    PINT_SIZED_SUMMONER,
    SI7_INFILTRATOR,
    EATER_OF_SECRETS,
    ARCANE_DEVOURER,
    VIOLET_APPRENTICE,
    FACELESS_MANIPULATOR,
    FACELESS_MANIPULATOR,
    // Tier 1 additions
    WISP,
    ELVEN_ARCHER,
    GOLDSHIRE_FOOTMAN,
    NOVICE_ENGINEER,
    RIVER_CROCOLISK,
    RAID_LEADER,
    SHATTERED_SUN_CLERIC,
    CHILLWIND_YETI,
    BOULDERFIST_OGRE,
    STORMWIND_CHAMPION,
    WAR_GOLEM,
    DIRE_WOLF_ALPHA,
    LOOT_HOARDER,
    STRANGLETHORN_TIGER,
    RAVENHOLDT_ASSASSIN,
    // Tier 2 additions
    KING_MUKLA,
    BANANA,
    TINKMASTER_OVERSPARK,
    DEVILSAUR,
    SQUIRREL,
    // Tier 3 additions
    BRIGHTWING,
    NOZDORMU,
    XAVIUS,
    YSERA,
    EMERALD_DRAKE,
    LAUGHING_SISTER,
    DREAM,
    NIGHTMARE,
    YSERA_AWAKENS,
    BARRENS_STABLEHAND,
    // Core Set W1 (core-set-roadmap W1) — neutral attack-pipeline cards
    IMPRISONED_VILEFIEND,
    EVASIVE_WYRM,
    FELRATTLER,
    SWAMP_LEECH,
    OBSIDIAN_STATUE,
    MURMY,
    LYNX,
];

pub const LEGENDARY_CLASSIC: &[CardDef] = &[
    CAIRNE_BLOODHOOF,
    BAINE_BLOODHOOF,
    HOGGER,
    GNOLL,
    ILLIDAN_STORMRAGE,
    FLAME_OF_AZZINOTH,
    THE_BEAST,
    FINKLE_EINHORN,
    BARON_GEDDON,
    GRUUL,
    RAGNAROS_THE_FIRELORD,
    ALEXSTRASZA,
    MALYGOS,
    ONYXIA,
    ONYXIA_WHELP,
    DEATHWING,
    BLOODMAGE_THALNOS,
    CAPTAIN_GREENSKIN,
    HARRISON_JONES,
    HIGH_INQUISITOR_WHITEMANE,
    THE_BLACK_KNIGHT,
    MILLHOUSE_MANASTORM,
    NAT_PAGLE,
    THE_BLACK_KNIGHT,
    MILLHOUSE_MANASTORM,
    NAT_PAGLE,
    // Pool-open (pool-open-cards-roadmap M3) — copies a cast spell
    LOREWALKER_CHO,
];
pub const DRUID_CLASSIC: &[CardDef] = &[
    INNERVATE,
    CLAW,
    MARK_OF_THE_WILD,
    WRATH,
    SWIPE,
    STARFIRE,
    DRUID_OF_THE_CLAW,
    ANCIENT_OF_LORE,
    ANCIENT_OF_WAR,
    SAVAGE_ROAR,
    MOONFIRE,
    WILD_GROWTH,
    HEALING_TOUCH,
    IRONBARK_PROTECTOR,
    FORCE_OF_NATURE,
    TREANT,
    GIFT_OF_THE_WILD,
    // Hero Attack
    BITE,
    SAVAGERY,
    POWER_OF_THE_WILD,
    PANTHER,
    MARK_OF_NATURE,
    NOURISH,
    STARFALL,
    // Tier 2 additions
    CENARIUS,
    CENARIUS_TREANT,
    KEEPER_OF_THE_GROVE,
    SOUL_OF_THE_FOREST,
    // Core Set W1 — Underking (Rush, battlecry/deathrattle armor)
    UNDERKING,
];

pub const HUNTER_CLASSIC: &[CardDef] = &[
    ARCANE_SHOT,
    HUNTERS_MARK,
    TRACKING,
    KILL_COMMAND,
    SAVANNAH_HIGHMANE,
    HYENA,
    EAGLEHORN_BOW,
    DEADLY_SHOT,
    EXPLOSIVE_SHOT,
    TIMBER_WOLF,
    KING_KRUSH,
    UNLEASH_THE_HOUNDS,
    MULTI_SHOT,
    SCAVENGING_HYENA,
    STARVING_BUZZARD,
    HOUNDMASTER,
    TUNDRA_RHINO,
    FLARE,
    // Tier 1 additions
    EXPLOSIVE_TRAP,
    FREEZING_TRAP,
    // Tier 2 additions
    MISDIRECTION,
    SNAKE_TRAP,
    SNAKE,
    SNIPE,
    BESTIAL_WRATH,
    GLADIATORS_LONGBOW,
    // Tier 3 additions
    ANIMAL_COMPANION,
    HUFFER,
    LEOKK,
    MISHA,
    // Core Set W1 — Halazzi, the Lynx (fill hand with 1/1 Lynxes)
    HALAZZI_THE_LYNX,
];

pub const MAGE_CLASSIC: &[CardDef] = &[
    ARCANE_MISSILES,
    FROSTBOLT,
    ARCANE_INTELLECT,
    FROST_NOVA,
    FIREBALL,
    POLYMORPH,
    WATER_ELEMENTAL,
    FLAMESTRIKE,
    PYROBLAST,
    ICE_BARRIER,
    ICE_BLOCK,
    MIRROR_ENTITY,
    COUNTERSPELL,
    BLIZZARD,
    ARCANE_EXPLOSION,
    CONE_OF_COLD,
    MANA_WYRM,
    MIRROR_IMAGE_MINION,
    ETHEREAL_ARCANIST,
    VAPORIZE,
    VAPORIZE,
    // Tier 2 additions
    SPELLBENDER,
    SPELLBENDER_TOKEN,
    SORCERERS_APPRENTICE,
    KIRIN_TOR_MAGE,
    ICICLE,
    // Tier 3 additions
    TOME_OF_INTELLECT,
    ARCHMAGE_ANTONIDAS,
];

pub const PALADIN_CLASSIC: &[CardDef] = &[
    BLESSING_OF_MIGHT,
    HUMILITY,
    HOLY_LIGHT,
    BLESSING_OF_KINGS,
    CONSECRATION,
    TRUESILVER_CHAMPION,
    GUARDIAN_OF_KINGS,
    TIRION_FORDRING,
    ASHBRINGER,
    ALDOR_PEACEKEEPER,
    EQUALITY,
    HAMMER_OF_WRATH,
    AVENGING_WRATH,
    LAY_ON_HANDS,
    HAND_OF_PROTECTION,
    LIGHTS_JUSTICE,
    ARGENT_PROTECTOR,
    HOLY_WRATH,
    RIGHTEOUSNESS,
    BLESSED_CHAMPION,
    SWORD_OF_JUSTICE,
    REPENTANCE,
    BLESSING_OF_WISDOM,
    EYE_FOR_AN_EYE,
    REDEMPTION,
    // Tier 2 additions
    NOBLE_SACRIFICE,
    DEFENDER,
];

pub const PRIEST_CLASSIC: &[CardDef] = &[
    HOLY_SMITE,
    MIND_BLAST,
    POWER_WORD_SHIELD,
    NORTHSHIRE_CLERIC,
    SHADOW_WORD_PAIN,
    SHADOW_WORD_DEATH,
    HOLY_NOVA,
    HOLY_FIRE,
    CIRCLE_OF_HEALING,
    AUCHENAI_SOULPRIEST,
    CABAL_SHADOW_PRIEST,
    PROPHET_VELEN,
    SILENCE,
    SHADOW_WORD_RUIN,
    TEMPLE_ENFORCER,
    RADIANCE,
    KUL_TIRAN_CHAPLAIN,
    MASS_DISPEL,
    DIVINE_SPIRIT,
    INNER_FIRE,
    LIGHTSPAWN,
    SCARLET_SUBJUGATOR,
    LIGHTWELL,
    // Tier 2 additions
    NATALIE_SELINE,
    SHADOW_MADNESS,
    MIND_CONTROL,
    // Pool-open (pool-open-cards-roadmap M2) — read the opponent's hand/deck
    MIND_VISION,
    THOUGHTSTEAL,
    MINDGAMES,
    // Core Set W1 — Lifesteal Priest spells
    DEVOURING_PLAGUE,
    DRAIN_SOUL,
    VOID_SHARD,
];

pub const ROGUE_CLASSIC: &[CardDef] = &[
    BACKSTAB,
    DEADLY_POISON,
    EVISCERATE,
    SAP,
    SI7_AGENT,
    ASSASSINATE,
    SPRINT,
    FAN_OF_KNIVES,
    PREPARATION,
    COLD_BLOOD,
    DEFIAS_RINGLEADER,
    EDWIN_VANCLEEF,
    SINISTER_STRIKE,
    SHIV,
    VANISH,
    ASSASSINS_BLADE,
    // Tier 2 additions
    HEADCRACK,
    KIDNAPPER,
    SHADOWSTEP,
    BETRAYAL,
    BLADE_FLURRY,
    PATIENT_ASSASSIN,
    PERDITIONS_BLADE,
    MASTER_OF_DISGUISE,
    // Tier 3 additions
    PILFER,
];

pub const SHAMAN_CLASSIC: &[CardDef] = &[
    EARTH_SHOCK,
    LIGHTNING_BOLT,
    ROCKBITER_WEAPON,
    FLAMETONGUE_TOTEM,
    HEX,
    LIGHTNING_STORM,
    FIRE_ELEMENTAL,
    BLOODLUST,
    FERAL_SPIRIT,
    MANA_TIDE_TOTEM,
    DOOMHAMMER,
    ALAKIR_THE_WINDLORD,
    TOTEMIC_MIGHT,
    FROST_SHOCK,
    DUST_DEVIL,
    FORKED_LIGHTNING,
    LAVA_BURST,
    STORMFORGED_AXE,
    EARTH_ELEMENTAL,
    WINDFURY,
    WINDSPEAKER,
    ANCESTRAL_HEALING,
    ANCESTRAL_SPIRIT,
    ANCESTRAL_SPIRIT,
    // Tier 2 additions
    FAR_SIGHT,
    UNBOUND_ELEMENTAL,
];

pub const WARLOCK_CLASSIC: &[CardDef] = &[
    SOULFIRE,
    FLAME_IMP,
    MORTAL_COIL,
    VOIDWALKER,
    HELLFIRE,
    DRAIN_LIFE,
    DOOMGUARD,
    SHADOW_BOLT,
    TWISTING_NETHER,
    LORD_JARAXXUS,
    BLOOD_FURY,
    DREAD_INFERNAL,
    PIT_LORD,
    FELSTALKER,
    SIPHON_SOUL,
    SHADOWFLAME,
    FELGUARD,
    SENSE_DEMONS,
    DEMONFIRE,
    VOID_TERROR,
    // Tier 1 additions
    SIEGEBREAKER,
    // Tier 2 additions
    SUMMONING_PORTAL,
    CORRUPTION,
    // Tier 3 additions
    CALL_OF_THE_VOID,
    BANE_OF_DOOM,
    BLOOD_IMP,
];

pub const WARRIOR_CLASSIC: &[CardDef] = &[
    EXECUTE,
    WHIRLWIND,
    SHIELD_BLOCK,
    CRUEL_TASKMASTER,
    KORKRON_ELITE,
    ARATHI_WEAPONSMITH,
    BATTLE_AXE,
    FROTHING_BERSERKER,
    WARSONG_COMMANDER,
    GOREHOWL,
    GROMMASH_HELLSCREAM,
    SLAM,
    CLEAVE,
    ARMORSMITH,
    INNER_RAGE,
    HEROIC_STRIKE,
    CHARGE_SPELL,
    SHIELD_SLAM,
    UPGRADE,
    BRAWL,
    MORTAL_STRIKE,
    BATTLE_RAGE,
    RAMPAGE,
    // Tier 1 additions
    FIERY_WAR_AXE,
    ARCANITE_REAPER,
    // Tier 2 additions
    COMMANDING_SHOUT,
];

pub const ALL_CARDS: &[CardDef] = &[
    // Neutral
    THE_COIN,
    BLOODFEN_RAPTOR,
    BLUEGILL_WARRIOR,
    ACIDIC_SWAMP_OOZE,
    IRONBEAK_OWL,
    KOBOLD_GEOMANCER,
    MURLOC_TIDEHUNTER,
    MURLOC_SCOUT,
    HARVEST_GOLEM,
    DAMAGED_GOLEM,
    SENJIN_SHIELDMASTA,
    DARK_IRON_DWARF,
    DEFENDER_OF_ARGUS,
    GNOMISH_INVENTOR,
    SPELLBREAKER,
    AZURE_DRAKE,
    SUNWALKER,
    ARGENT_COMMANDER,
    WINDFURY_HARPY,
    WOLFRIDER,
    AMANI_BERSERKER,
    FAERIE_DRAGON,
    ABUSIVE_SERGEANT,
    YOUTHFUL_BREWMASTER,
    MAD_BOMBER,
    ACOLYTE_OF_PAIN,
    EARTHEN_RING_FARSEER,
    INJURED_BLADEMASTER,
    IMP_MASTER,
    RAGING_WORGEN,
    SCARLET_CRUSADER,
    THRALLMAR_FARSEER,
    ANCIENT_BREWMASTER,
    CULT_MASTER,
    OGRE_MAGI,
    SILVERMOON_GUARDIAN,
    VIOLET_TEACHER,
    MOGUSHAN_WARDEN,
    ABOMINATION,
    FROSTWOLF_WARLORD,
    GADGETZAN_AUCTIONEER,
    SILVER_HAND_KNIGHT,
    SQUIRE,
    FROST_ELEMENTAL,
    LORD_OF_THE_ARENA,
    RECKLESS_ROCKETEER,
    ARCHMAGE,
    CORE_HOUND,
    SEA_GIANT,
    MOLTEN_GIANT,
    MOUNTAIN_GIANT,
    GRIMSCALE_ORACLE,
    MURLOC_RAIDER,
    STONETUSK_BOAR,
    VOODOO_DOCTOR,
    FROSTWOLF_GRUNT,
    DALARAN_MAGE,
    IRONFORGE_RIFLEMAN,
    IRONFUR_GRIZZLY,
    MAGMA_RAGER,
    RAZORFEN_HUNTER,
    BOAR,
    SILVERBACK_PATRIARCH,
    DRAGONLING_MECHANIC,
    MECHANICAL_DRAGONLING,
    OASIS_SNAPJAW,
    STORMWIND_KNIGHT,
    BOOTY_BAY_BODYGUARD,
    DARKSCALE_HEALER,
    NIGHTBLADE,
    STORMPIKE_COMMANDO,
    ARGENT_SQUIRE,
    LEPER_GNOME,
    SHIELDBEARER,
    YOUNG_DRAGONHAWK,
    FEN_CREEPER,
    PRIESTESS_OF_ELUNE,
    SOUTHSHORE_CAPTAIN,
    // Druid
    INNERVATE,
    CLAW,
    MARK_OF_THE_WILD,
    WRATH,
    SWIPE,
    STARFIRE,
    DRUID_OF_THE_CLAW,
    ANCIENT_OF_LORE,
    ANCIENT_OF_WAR,
    SAVAGE_ROAR,
    MOONFIRE,
    WILD_GROWTH,
    HEALING_TOUCH,
    IRONBARK_PROTECTOR,
    FORCE_OF_NATURE,
    TREANT,
    // Hunter
    ARCANE_SHOT,
    HUNTERS_MARK,
    TRACKING,
    KILL_COMMAND,
    SAVANNAH_HIGHMANE,
    HYENA,
    EAGLEHORN_BOW,
    DEADLY_SHOT,
    EXPLOSIVE_SHOT,
    TIMBER_WOLF,
    KING_KRUSH,
    UNLEASH_THE_HOUNDS,
    // Mage
    ARCANE_MISSILES,
    FROSTBOLT,
    ARCANE_INTELLECT,
    FROST_NOVA,
    FIREBALL,
    POLYMORPH,
    WATER_ELEMENTAL,
    FLAMESTRIKE,
    PYROBLAST,
    ICE_BARRIER,
    ICE_BLOCK,
    MIRROR_ENTITY,
    COUNTERSPELL,
    BLIZZARD,
    ARCANE_EXPLOSION,
    MANA_WYRM,
    MIRROR_IMAGE_MINION,
    ETHEREAL_ARCANIST,
    VAPORIZE,
    // Paladin
    BLESSING_OF_MIGHT,
    HUMILITY,
    HOLY_LIGHT,
    BLESSING_OF_KINGS,
    CONSECRATION,
    TRUESILVER_CHAMPION,
    GUARDIAN_OF_KINGS,
    TIRION_FORDRING,
    ASHBRINGER,
    ALDOR_PEACEKEEPER,
    EQUALITY,
    HAMMER_OF_WRATH,
    AVENGING_WRATH,
    LAY_ON_HANDS,
    HAND_OF_PROTECTION,
    LIGHTS_JUSTICE,
    ARGENT_PROTECTOR,
    BLESSED_CHAMPION,
    // Priest
    HOLY_SMITE,
    MIND_BLAST,
    POWER_WORD_SHIELD,
    NORTHSHIRE_CLERIC,
    SHADOW_WORD_PAIN,
    SHADOW_WORD_DEATH,
    HOLY_NOVA,
    HOLY_FIRE,
    CIRCLE_OF_HEALING,
    AUCHENAI_SOULPRIEST,
    CABAL_SHADOW_PRIEST,
    PROPHET_VELEN,
    SILENCE,
    SHADOW_WORD_RUIN,
    TEMPLE_ENFORCER,
    DIVINE_SPIRIT,
    INNER_FIRE,
    LIGHTSPAWN,
    SCARLET_SUBJUGATOR,
    LIGHTWELL,
    // Rogue
    BACKSTAB,
    DEADLY_POISON,
    EVISCERATE,
    SAP,
    SI7_AGENT,
    ASSASSINATE,
    SPRINT,
    FAN_OF_KNIVES,
    PREPARATION,
    COLD_BLOOD,
    DEFIAS_RINGLEADER,
    EDWIN_VANCLEEF,
    SINISTER_STRIKE,
    SHIV,
    VANISH,
    ASSASSINS_BLADE,
    // Tier 2
    HEADCRACK,
    KIDNAPPER,
    SHADOWSTEP,
    BETRAYAL,
    BLADE_FLURRY,
    PATIENT_ASSASSIN,
    PERDITIONS_BLADE,
    MASTER_OF_DISGUISE,
    // Shaman
    EARTH_SHOCK,
    LIGHTNING_BOLT,
    ROCKBITER_WEAPON,
    FLAMETONGUE_TOTEM,
    HEX,
    LIGHTNING_STORM,
    FIRE_ELEMENTAL,
    BLOODLUST,
    FERAL_SPIRIT,
    MANA_TIDE_TOTEM,
    DOOMHAMMER,
    ALAKIR_THE_WINDLORD,
    TOTEMIC_MIGHT,
    FROST_SHOCK,
    DUST_DEVIL,
    FORKED_LIGHTNING,
    LAVA_BURST,
    STORMFORGED_AXE,
    EARTH_ELEMENTAL,
    WINDFURY,
    WINDSPEAKER,
    ANCESTRAL_HEALING,
    ANCESTRAL_SPIRIT,
    // Warlock
    SOULFIRE,
    FLAME_IMP,
    MORTAL_COIL,
    VOIDWALKER,
    HELLFIRE,
    DRAIN_LIFE,
    DOOMGUARD,
    SHADOW_BOLT,
    TWISTING_NETHER,
    LORD_JARAXXUS,
    BLOOD_FURY,
    DREAD_INFERNAL,
    PIT_LORD,
    FELSTALKER,
    SIPHON_SOUL,
    SHADOWFLAME,
    FELGUARD,
    SENSE_DEMONS,
    DEMONFIRE,
    VOID_TERROR,
    // Warrior
    EXECUTE,
    WHIRLWIND,
    SHIELD_BLOCK,
    CRUEL_TASKMASTER,
    KORKRON_ELITE,
    ARATHI_WEAPONSMITH,
    BATTLE_AXE,
    FROTHING_BERSERKER,
    WARSONG_COMMANDER,
    GOREHOWL,
    GROMMASH_HELLSCREAM,
    SLAM,
    CLEAVE,
    ARMORSMITH,
    INNER_RAGE,
    // Hero Attack
    HEROIC_STRIKE,
    CHARGE_SPELL,
    SHIELD_SLAM,
    UPGRADE,
    BRAWL,
    MORTAL_STRIKE,
    BATTLE_RAGE,
    RAMPAGE,
    // Legendary
    CAIRNE_BLOODHOOF,
    BAINE_BLOODHOOF,
    HOGGER,
    GNOLL,
    ILLIDAN_STORMRAGE,
    FLAME_OF_AZZINOTH,
    THE_BEAST,
    FINKLE_EINHORN,
    BARON_GEDDON,
    GRUUL,
    RAGNAROS_THE_FIRELORD,
    ALEXSTRASZA,
    MALYGOS,
    ONYXIA,
    ONYXIA_WHELP,
    DEATHWING,
    BLOODMAGE_THALNOS,
    CAPTAIN_GREENSKIN,
    HARRISON_JONES,
    HIGH_INQUISITOR_WHITEMANE,
    THE_BLACK_KNIGHT,
    MILLHOUSE_MANASTORM,
    NAT_PAGLE,
    // Incomplete additions
    GIFT_OF_THE_WILD,
    MULTI_SHOT,
    CONE_OF_COLD,
    HOLY_WRATH,
    RIGHTEOUSNESS,
    RADIANCE,
    KUL_TIRAN_CHAPLAIN,
    MASS_DISPEL,
    COLDLIGHT_SEER,
    MURLOC_WARLEADER,
    // Hero Attack
    BITE,
    SAVAGERY,
    POWER_OF_THE_WILD,
    PANTHER,
    MARK_OF_NATURE,
    NOURISH,
    STARFALL,
    // Simplified additions
    GURUBASHI_BERSERKER,
    SOUTHSHORE_DECKHAND,
    WORGEN_INFILTRATOR,
    BLOODSAIL_RAIDER,
    JUNGLE_PANTHER,
    TAUREN_WARRIOR,
    FLESHEATING_GHOUL,
    DREAD_CORSAIR,
    VENTURE_CO_MERCENARY,
    SPITEFUL_SMITH,
    ANGRY_CHICKEN,
    BLOODSAIL_CORSAIR,
    LIGHTWARDEN,
    MURLOC_TIDECALLER,
    SECRETKEEPER,
    ANCIENT_WATCHER,
    CRAZED_ALCHEMIST,
    KNIFE_JUGGLER,
    MANA_ADDICT,
    SUNFURY_PROTECTOR,
    WILD_PYROMANCER,
    ALARM_O_BOT,
    ARCANE_GOLEM,
    DEMOLISHER,
    EMPEROR_COBRA,
    QUESTING_ADVENTURER,
    ANCIENT_MAGE,
    TWILIGHT_DRAKE,
    STAMPEDING_KODO,
    HUNGRY_CRAB,
    DOOMSAYER,
    BLOOD_KNIGHT,
    BIG_GAME_HUNTER,
    YOUNG_PRIESTESS,
    MANA_WRAITH,
    MASTER_SWORDSMITH,
    PINT_SIZED_SUMMONER,
    SI7_INFILTRATOR,
    EATER_OF_SECRETS,
    ARCANE_DEVOURER,
    VIOLET_APPRENTICE,
    FACELESS_MANIPULATOR,
    // Tier 1 additions
    WISP,
    ELVEN_ARCHER,
    GOLDSHIRE_FOOTMAN,
    NOVICE_ENGINEER,
    RIVER_CROCOLISK,
    RAID_LEADER,
    SHATTERED_SUN_CLERIC,
    CHILLWIND_YETI,
    BOULDERFIST_OGRE,
    STORMWIND_CHAMPION,
    WAR_GOLEM,
    DIRE_WOLF_ALPHA,
    LOOT_HOARDER,
    STRANGLETHORN_TIGER,
    RAVENHOLDT_ASSASSIN,
    EXPLOSIVE_TRAP,
    FREEZING_TRAP,
    SIEGEBREAKER,
    FIERY_WAR_AXE,
    ARCANITE_REAPER,
    // Tier 2 secrets
    MISDIRECTION,
    SNAKE_TRAP,
    SNAKE,
    SNIPE,
    SPELLBENDER,
    SPELLBENDER_TOKEN,
    NOBLE_SACRIFICE,
    DEFENDER,
    // Tier 2 cost reduction
    SORCERERS_APPRENTICE,
    KIRIN_TOR_MAGE,
    FAR_SIGHT,
    SUMMONING_PORTAL,
    // Tier 2 Druid
    CENARIUS,
    CENARIUS_TREANT,
    KEEPER_OF_THE_GROVE,
    SOUL_OF_THE_FOREST,
    KING_MUKLA,
    BANANA,
    // Tier 2 immunity
    BESTIAL_WRATH,
    GLADIATORS_LONGBOW,
    ICICLE,
    NATALIE_SELINE,
    // Tier 2 control/transform
    SHADOW_MADNESS,
    MIND_CONTROL,
    // Pool-open (pool-open-cards-roadmap M2) — read the opponent's hand/deck
    MIND_VISION,
    THOUGHTSTEAL,
    MINDGAMES,
    SHADOW_OF_NOTHING,
    LOREWALKER_CHO,
    CORRUPTION,
    COMMANDING_SHOUT,
    UNBOUND_ELEMENTAL,
    TINKMASTER_OVERSPARK,
    DEVILSAUR,
    SQUIRREL,
    // Tier 3 random pools
    BRIGHTWING,
    NOZDORMU,
    XAVIUS,
    YSERA,
    EMERALD_DRAKE,
    LAUGHING_SISTER,
    DREAM,
    NIGHTMARE,
    YSERA_AWAKENS,
    BARRENS_STABLEHAND,
    ANIMAL_COMPANION,
    HUFFER,
    LEOKK,
    MISHA,
    TOME_OF_INTELLECT,
    ARCHMAGE_ANTONIDAS,
    PILFER,
    CALL_OF_THE_VOID,
    BANE_OF_DOOM,
    BLOOD_IMP,
    // F-A4 additions (2026-08-06): implemented class cards that were missing from ALL_CARDS
    SCAVENGING_HYENA,
    STARVING_BUZZARD,
    HOUNDMASTER,
    TUNDRA_RHINO,
    FLARE,
    SWORD_OF_JUSTICE,
    REPENTANCE,
    BLESSING_OF_WISDOM,
    EYE_FOR_AN_EYE,
    REDEMPTION,
    // Core Set W1 (core-set-roadmap W1, 2026-08-08) — attack-pipeline
    // primitives: 15 cards + the Lynx token. Class affiliations follow the
    // group membership above (Druid/Hunter/Priest/Neutral/Demon Hunter/
    // Death Knight).
    UNDERKING,
    HALAZZI_THE_LYNX,
    LYNX,
    DEVOURING_PLAGUE,
    DRAIN_SOUL,
    VOID_SHARD,
    EYE_BEAM,
    ALDRACHI_WARBLADES,
    MYTHICAL_TERROR,
    MALIGNANT_HORROR,
    IMPRISONED_VILEFIEND,
    EVASIVE_WYRM,
    FELRATTLER,
    SWAMP_LEECH,
    OBSIDIAN_STATUE,
    MURMY,
];

// ============================================================
// Pool-open registry
// ============================================================

/// Pool-open cards — cards whose resolution can move a card into a zone
/// without that card having been sampled from a pool `cards/pool.rs` controls:
/// they read the opponent's actual hand/deck, or copy a cast spell.
///
/// The Classic pool is closed today (`ALL_CARDS` is Classic-only, so anything
/// in the opponent's zones is already in the pool), but this registry keeps the
/// closure invariant auditable for the day a second set is supported: the
/// zone-reading effect variants may appear only on registered cards (enforced
/// by `pool_open_effects_require_registry` in `trigger.rs`), and any new
/// zone-reading card must register here first. See `docs/pool-openness.md`.
pub const POOL_OPEN_CARDS: &[&str] = &[
    // Pool-open (pool-open-cards-roadmap M2/M3) — read the opponent's
    // actual hand/deck or copy a cast spell.
    "PRIEST_024",    // Mind Vision — enemy hand
    "PRIEST_025",    // Thoughtsteal — enemy deck
    "PRIEST_026",    // Mindgames — enemy deck
    "LEGENDARY_024", // Lorewalker Cho — copies a cast spell
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cards::def::card_by_id;

    /// The pool-open registry must be well-formed: every ID resolves to a real
    /// card, none is a derivative token (tokens are never pool-open — they are
    /// only produced by pools), and there are no duplicates.
    #[test]
    fn pool_open_registry_is_well_formed() {
        let mut seen = std::collections::HashSet::new();
        for id in POOL_OPEN_CARDS {
            assert!(card_by_id(id).is_some(), "{id} must resolve via card_by_id");
            assert!(
                !id.ends_with('t'),
                "{id} is a token — tokens are not pool-open"
            );
            assert!(seen.insert(id), "{id} is registered twice");
        }
    }

    /// Pool closure is enforced: the zone-reading effect variants (pool-open
    /// M1) may appear only on cards registered in `POOL_OPEN_CARDS`. A future
    /// card that reads an opponent zone cannot be added without either
    /// registering it or failing this test. The Cho trigger path (registered
    /// by ID in `apply_card_keywords`, not through a CardDef field) is
    /// covered by its debug_assert + `po_cho_*` scenarios.
    #[test]
    fn pool_open_effects_require_registry() {
        use crate::core::effect::CardEffect;

        let is_pool_open_effect = |effect: &CardEffect| {
            matches!(
                effect,
                CardEffect::CopyRandomEnemyHandCard { .. }
                    | CardEffect::CopyRandomEnemyDeckCards { .. }
                    | CardEffect::SummonRandomEnemyDeckMinion { .. }
                    | CardEffect::CopyCastSpellToOtherPlayerHand
            )
        };
        for card in ALL_CARDS {
            let uses_pool_open = [
                card.battlecry,
                card.deathrattle,
                card.spell_effect,
                card.end_turn_effect,
                card.start_turn_effect,
                card.spell_trigger,
                card.death_trigger,
                card.summon_trigger,
                card.choose_one_effect,
                card.combo_effect,
                card.hero_power,
            ]
            .into_iter()
            .flatten()
            .any(|effect| is_pool_open_effect(&effect));
            // Cho's pool-open trigger lives in the ID-keyword hook (no CardDef
            // field) — its ID is the second source of truth.
            let via_keyword_hook = crate::cards::POOL_OPEN_KEYWORD_IDS.contains(&card.id);
            assert_eq!(
                uses_pool_open || via_keyword_hook,
                POOL_OPEN_CARDS.contains(&card.id),
                "{}: a pool-open effect requires a POOL_OPEN_CARDS row (and vice versa)",
                card.id
            );
        }
    }
}
